### ISSUE TITLE
v2.1.0 IndentationError: unexpected indent in addic7ed.py

### ISSUE THREAD

**Issue by cpoppema** [Diaoul/subliminal#1005]
```
 $    pip install subliminal==2.0.5
 $    python -c 'from subliminal.providers import addic7ed'
<no output>
```

```
$    pip install subliminal==2.1.0
$    python -c 'from subliminal.providers import addic7ed'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "../site-packages/subliminal/providers/addic7ed.py", line 234
    r = self.session.get(self.server_url + 'show/%d' % show_id, params={'season': season}, timeout=10)
    ^
IndentationError: unexpected indent
```

Checking the git source file online it doesn't make any sense: https://github.com/Diaoul/subliminal/blob/master/subliminal/providers/addic7ed.py#L231-L237
Checking the installed file it illustrates the problem.

In v2.1.0
```
 $    grep -B3 -A3 "r = self.session.get(self.server_url + 'show/%d' % show_id, params={'season': season}, timeout=10)" subliminal/providers/addic7ed.py 
    def query(self, show_id, series, season, year=None, country=None):
        # get the page of the season of the show
        logger.info('Getting the page of show id %d, season %d', show_id, season)
            r = self.session.get(self.server_url + 'show/%d' % show_id, params={'season': season}, timeout=10)
        r.raise_for_status()

        if not r.content:
```

**Comment by ratoaq2** [comment]
Thanks, there's indeed an indentation problem.
But addic7ed provider doesn't work anyway because they introduced captcha for authentication and they blocked subliminal user agent. In the next release, a addic4ed provider will be disabled by default
