### ISSUE TITLE
ValueError: unused keyword argument 'children'

### ISSUE THREAD

**Issue by mbnoimi** [Diaoul/subliminal#1007]
Hi,

Whenever I call `subliminal` from CLI I get this error message. 
May you please guide me how to fix this issue?

```
$ subliminal download -v -l en The.Big.Bang.Theory.S05E18.HDTV.x264-LOL.mp4
The.Big.Bang.Theory.S05E18.HDTV.x264-LOL.mp4 errored
0 video collected / 0 video ignored / 1 error
$ subliminal --version
subliminal, version 2.1.0
$ cat /etc/issue
Linux Mint 20 Ulyana \n \l
$ subliminal --debug download -l en The.Big.Bang.Theory.S05E18.HDTV.x264-LOL.mp4
DEBUG:subliminal.cli:Collecting path The.Big.Bang.Theory.S05E18.HDTV.x264-LOL.mp4
ERROR:subliminal.cli:Unexpected error while collecting non-existing path The.Big.Bang.Theory.S05E18.HDTV.x264-LOL.mp4
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/python3/dist-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/python3/dist-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/home/mbnoimi/.local/lib/python3.8/site-packages/regex/regex.py", line 349, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/home/mbnoimi/.local/lib/python3.8/site-packages/regex/regex.py", line 586, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'conflict_solver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/subliminal/cli.py", line 349, in download
    video = Video.fromname(p)
  File "/usr/local/lib/python3.8/dist-packages/subliminal/video.py", line 114, in fromname
    return cls.fromguess(name, guessit(name))
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 71, in guessit
    return default_api.guessit(string, options)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 222, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=The.Big.Bang.Theory.S05E18.HDTV.x264-LOL.mp4
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/python3/dist-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/python3/dist-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/home/mbnoimi/.local/lib/python3.8/site-packages/regex/regex.py", line 349, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/home/mbnoimi/.local/lib/python3.8/site-packages/regex/regex.py", line 586, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'conflict_solver'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
0 video collected / 0 video ignored / 1 error
```

**Comment by mbnoimi** [comment]
log for real existing file:
```
$ subliminal --debug download -l en Malcolm.X.1992.360p.BluRay.H264.MyCima.TV.mkv 
DEBUG:subliminal.cli:Collecting path Malcolm.X.1992.360p.BluRay.H264.MyCima.TV.mkv
INFO:subliminal.core:Scanning video 'Malcolm.X.1992.360p.BluRay.H264.MyCima.TV.mkv' in ''
ERROR:subliminal.cli:Unexpected error while collecting path Malcolm.X.1992.360p.BluRay.H264.MyCima.TV.mkv
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/python3/dist-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/python3/dist-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/home/mbnoimi/.local/lib/python3.8/site-packages/regex/regex.py", line 349, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/home/mbnoimi/.local/lib/python3.8/site-packages/regex/regex.py", line 586, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/subliminal/cli.py", line 387, in download
    video = scan_video(p)
  File "/usr/local/lib/python3.8/dist-packages/subliminal/core.py", line 372, in scan_video
    video = Video.fromguess(path, guessit(path))
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 71, in guessit
    return default_api.guessit(string, options)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 222, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=Malcolm.X.1992.360p.BluRay.H264.MyCima.TV.mkv
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/lib/python3/dist-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/python3/dist-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/python3/dist-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/python3/dist-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/python3/dist-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/home/mbnoimi/.local/lib/python3.8/site-packages/regex/regex.py", line 349, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/home/mbnoimi/.local/lib/python3.8/site-packages/regex/regex.py", line 586, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'children'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
0 video collected / 0 video ignored / 1 error
```

**Comment by weber-s** [comment]
For those who have the same issue:

it's related to `guessit`, then to the `rebulk` package. https://github.com/guessit-io/guessit/issues/639

so:

```
pip install guessit --upgrade
pip install rebulk --upgrade
```

solved it for me.
