### ISSUE TITLE
Fresh install on Ubuntu 18 giving errors

### ISSUE THREAD

**Issue by skinnyzaz** [Diaoul/subliminal#1009]
Just installed subliminal on ubuntu 18 and am receiving the following error, anyone have any ideas why?

root@server:~# subliminal --help
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 7, in <module>
    from subliminal.cli import subliminal
  File "/usr/local/lib/python2.7/dist-packages/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 13, in <module>
    from rarfile import BadRarFile, NotRarFile, RarCannotExec, RarFile, Error, is_rarfile
  File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 946
    warnings.warn(f"Windows junction not supported - {info.filename}", UnsupportedWarning)
                                                                    ^
SyntaxError: invalid syntax

EDIT:  Figured out the issue, uninstalled it then installed it again using  pip3 install subliminal

**Comment by rubenhortas** [comment]
It didn't work for me. 
It doesn't work on a virtualenv either.
Maybe worth opening?

Environment: 

- OS: Raspbian 9.13 (stretch)
- Python: 3.5.3
- Subliminal: 2.1.0

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 7, in <module>
    from subliminal.cli import subliminal
  File "/usr/local/lib/python3.5/dist-packages/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/usr/local/lib/python3.5/dist-packages/subliminal/core.py", line 13, in <module>
    from rarfile import BadRarFile, NotRarFile, RarCannotExec, RarFile, Error, is_rarfile
  File "/home/ruben/.local/lib/python3.5/site-packages/rarfile.py", line 946
    warnings.warn(f"Windows junction not supported - {info.filename}", UnsupportedWarning)
                                                                    ^
SyntaxError: invalid syntax
```

**Comment by Diaoul** [comment]
I believe you need a more recent version of Python. Python 3.5 is OEL.

**Comment by rubenhortas** [comment]
I upgraded the whole system and works like a charm. Seemed a issue with rarfile, not subliminal related.
