### ISSUE TITLE
Issue on Ubuntu 21.10 and python 3.97

### ISSUE THREAD

**Issue by hyuma78** [Diaoul/subliminal#1044]
I'm trying to make some subititles download and this is the output with option debug command. This is the command I've launched:

subliminal --debug --addic7ed xxxxxx xxxxxxx download -l it Chucky.S01E07.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.mkv

(where the "x" are my login and password on addic7ed). Seems like that subliminal neither search on addic7ed and gave me all the ssl error/warning on podnapisi and doesn't download nothing. I tested subliminal on windows10 with python 3.9.1 and works good. I don't know if it's related to some python 3.9.7 library... any suggestion is appreciated. Thanks!

```
Collecting videos  [------------------------------------]    0%  Chucky.S01E07.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.mkvDEBUG:subliminal.cli:Collecting path Chucky.S01E07.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.mkv
INFO:subliminal.core:Scanning video 'Chucky.S01E07.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.mkv' in ''
DEBUG:subliminal.core:Size is 2750566536
DEBUG:subliminal.core:Found subtitles {'Chucky.S01E07.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.srt': <Language [und]>}
INFO:subliminal.core:Refining video with hash
DEBUG:subliminal.refiners.hash:Computing hashes for 'Chucky.S01E07.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.mkv'
DEBUG:subliminal.refiners.hash:Computed hashes {'opensubtitles': '3e7e888ca6831061', 'thesubdb': 'b97b1b88aa731e8ae5e520bb0ee2d474'}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found resolution 1080p
DEBUG:subliminal.refiners.metadata:Found video_codec H.264
DEBUG:subliminal.refiners.metadata:Embedded subtitle track name 'SDH' is not a valid language
DEBUG:subliminal.refiners.metadata:Found embedded subtitle {<Language [und]>}
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'Chucky'
DEBUG:subliminal.refiners.tvdb:Found 31 results
DEBUG:subliminal.refiners.tvdb:Found exact match on series 'Chucky'
DEBUG:subliminal.refiners.tvdb:Found series {'id': 349415, 'seriesId': '', 'seriesName': 'Chucky', 'aliases': ["Child's Play: The TV Series"], 'season': '1', 'poster': 'v4/series/349415/posters/613ac97f9cf74.jpg', 'banner': 'v4/series/349415/banners/6169581029e75.jpg', 'fanart': 'v4/series/349415/backgrounds/60f46f8e32922.jpg', 'status': 'Continuing', 'firstAired': '2021-10-12', 'network': 'USA Network', 'networkId': '306', 'runtime': '44', 'language': 'en', 'genre': ['Horror', 'Suspense', 'Thriller'], 'overview': 'After a vintage Chucky doll turns up at a suburban yard sale, an idyllic American town is thrown into chaos as a series of horrifying murders begin to expose the town hypocrisies and secrets. Meanwhile, the arrival of enemies and allies from Chucky past threatens to expose the truth behind the killings, as well as the demon doll untold origins.', 'lastUpdated': 1639632035, 'airsDayOfWeek': 'Tuesday', 'airsTime': '10:00 PM', 'rating': 'TV-MA', 'imdbId': 'tt8388390', 'zap2itId': '', 'added': '2018-06-22 13:11:28', 'addedBy': 161224, 'siteRating': 0, 'siteRatingCount': 0, 'slug': 'chucky'}
INFO:subliminal.refiners.tvdb:Getting series episode 1x7
DEBUG:subliminal.refiners.tvdb:Found episode {'id': 8558067, 'airedSeason': 1, 'airedSeasonID': 1917827, 'airedEpisodeNumber': 7, 'episodeName': 'Twice the Grieving, Double the Loss', 'firstAired': '2021-11-23', 'guestStars': ['Barbara Alyn Woods', 'Blaise Crocker', 'Carina Battrick', 'Devon Sawa', 'Michael Therriault', 'Nick A Fisher'], 'directors': ['Samir Rehem'], 'writers': ['Don Mancini', 'Isabella Gutierrez', 'Mallory Westfall'], 'overview': "The kids desperately try to figure out Chucky's mysterious endgame-before it's too late.", 'language': {'episodeName': 'en', 'overview': 'en'}, 'productionCode': '01007', 'showUrl': '', 'lastUpdated': 1639026760, 'dvdDiscid': '', 'dvdSeason': None, 'dvdEpisodeNumber': None, 'dvdChapter': None, 'absoluteNumber': 7, 'filename': 'v4/episode/8558067/screencap/619f9feb3157d.jpg', 'seriesId': 349415, 'lastUpdatedBy': 166434, 'airsAfterSeason': None, 'airsBeforeSeason': None, 'airsBeforeEpisode': None, 'imdbId': 'tt14413038', 'contentRating': 'TV-MA', 'thumbAuthor': 2247838, 'thumbAdded': '2021-11-25 14:38:35', 'thumbWidth': '640', 'thumbHeight': '360', 'siteRating': 0, 'siteRatingCount': 0, 'isMovie': 0}
INFO:subliminal.core:Refining video with omdb
WARNING:subliminal.refiners.omdb:No apikey. Skipping omdb refiner.
Collecting videos  [####################################]  100%                                                          
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [------------------------------------]    0%  Chucky.S01E07.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.mkvINFO:subliminal.core:Skipping provider 'argenteam': no language to search for
INFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages {<Language [it]>}
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [it]>}
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages {<Language [it]>}
INFO:subliminal.providers.opensubtitles:Logging in
INFO:subliminal.core:Skipping provider 'shooter': no language to search for
INFO:subliminal.core:Listing subtitles with provider 'thesubdb' and languages {<Language [it]>}
INFO:subliminal.core:Initializing provider podnapisi
INFO:subliminal.providers.podnapisi:Searching subtitles {'sXML': 1, 'sL': 'it', 'sK': 'Chucky', 'sTS': 1, 'sTE': 7, 'sY': 2021}
INFO:subliminal.core:Listing subtitles with provider 'tvsubtitles' and languages {<Language [it]>}
INFO:subliminal.core:Initializing provider thesubdb
INFO:subliminal.providers.legendastv:Getting archives for title 58833 and language 16
INFO:subliminal.core:Initializing provider tvsubtitles
INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': 'b97b1b88aa731e8ae5e520bb0ee2d474'}
ERROR:subliminal.providers.tvsubtitles:Episode 7 not found
ERROR:subliminal.utils:Unexpected error. Provider opensubtitles
Traceback (most recent call last):
  File "/home/hyuma/.local/lib/python3.9/site-packages/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/hyuma/.local/lib/python3.9/site-packages/subliminal/core.py", line 67, in __getitem__
    provider.initialize()
  File "/home/hyuma/.local/lib/python3.9/site-packages/subliminal/providers/opensubtitles.py", line 129, in initialize
    response = checked(self.server.LogIn(self.username, self.password, 'eng', self.user_agent))
  File "/home/hyuma/.local/lib/python3.9/site-packages/subliminal/providers/opensubtitles.py", line 278, in checked
    raise Unauthorized
subliminal.providers.opensubtitles.Unauthorized
ERROR:subliminal.utils:SSL error MaxRetryError("HTTPSConnectionPool(host='www.podnapisi.net', port=443): Max retries exceeded with url: /subtitles/search/old?sXML=1&sL=it&sK=Chucky&sTS=1&sTE=7&sY=2021 (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)')))"). Provider podnapisi
Traceback (most recent call last):
  File "/home/hyuma/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/hyuma/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/hyuma/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/hyuma/.local/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/home/hyuma/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/hyuma/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyuma/.local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/hyuma/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/hyuma/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.podnapisi.net', port=443): Max retries exceeded with url: /subtitles/search/old?sXML=1&sL=it&sK=Chucky&sTS=1&sTE=7&sY=2021 (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyuma/.local/lib/python3.9/site-packages/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/hyuma/.local/lib/python3.9/site-packages/subliminal/providers/podnapisi.py", line 160, in list_subtitles
    subtitles = [s for l in languages for s in
  File "/home/hyuma/.local/lib/python3.9/site-packages/subliminal/providers/podnapisi.py", line 161, in <listcomp>
    self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/home/hyuma/.local/lib/python3.9/site-packages/subliminal/providers/podnapisi.py", line 98, in query
    r = self.session.get(self.server_url + 'search/old', params=params, timeout=10)
  File "/home/hyuma/.local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/hyuma/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hyuma/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/hyuma/.local/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.podnapisi.net', port=443): Max retries exceeded with url: /subtitles/search/old?sXML=1&sL=it&sK=Chucky&sTS=1&sTE=7&sY=2021 (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)')))
DEBUG:subliminal.providers.legendastv:Found 0 archives
INFO:subliminal.providers.legendastv:No archives found for title 58833 and language 16
INFO:subliminal.providers.legendastv:Getting archives for title 58068 and language 16
DEBUG:subliminal.providers.legendastv:Found 0 archives
INFO:subliminal.providers.legendastv:No archives found for title 58068 and language 16
INFO:subliminal.providers.legendastv:Searching episode title 'childs play the tv series' for season 1
DEBUG:subliminal.providers.legendastv:Found 0 titles
INFO:subliminal.providers.legendastv:Searching episode title "child's play the tv series" for season 1
DEBUG:subliminal.providers.legendastv:Found 0 titles
INFO:subliminal.core:Discarding provider opensubtitles
INFO:subliminal.core:Discarding provider podnapisi
ERROR:subliminal.utils:Request timed out. Provider thesubdb
INFO:subliminal.core:Discarding provider thesubdb
Downloading subtitles  [####################################]  100%                                                          
Some providers have been discarded due to unexpected errors: opensubtitles, thesubdb, podnapisi
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.core:Terminating provider podnapisi
INFO:subliminal.core:Terminating provider thesubdb
INFO:subliminal.core:Terminating provider tvsubtitles
**Downloaded 0 subtitle**
```

**Comment by hyuma78** [comment]
And this is the debug output on windows10, at the end you can see that the download was succesful!

```
Collecting videos  [------------------------------------]    0%  Chucky.S01E05.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.mkvDEBUG:subliminal.cli:Collecting path Chucky.S01E05.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.mkv
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with hash
ERROR:subliminal.utils:Unexpected error. Failed to refine video 'Chucky.S01E05.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.mkv'
Traceback (most recent call last):
  File "C:\Users\sarahthrace\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\core.py", line 549, in refine
    refiner_manager[refiner].plugin(video, **dict((refiner_configs or {}).get(refiner, {}), **kwargs))
  File "C:\Users\sarahthrace\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\refiners\hash.py", line 26, in refine
    if video.size <= 10485760:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
INFO:subliminal.core:Refining video with metadata
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'Chucky'
DEBUG:subliminal.refiners.tvdb:Found 31 results
DEBUG:subliminal.refiners.tvdb:Found exact match on series 'Chucky'
DEBUG:subliminal.refiners.tvdb:Found series {'id': 349415, 'seriesId': '', 'seriesName': 'Chucky', 'aliases': ["Child's Play: The TV Series"], 'season': '1', 'poster': 'v4/series/349415/posters/613ac97f9cf74.jpg', 'banner': 'v4/series/349415/banners/6169581029e75.jpg', 'fanart': 'v4/series/349415/backgrounds/60f46f8e32922.jpg', 'status': 'Continuing', 'firstAired': '2021-10-12', 'network': 'USA Network', 'networkId': '306', 'runtime': '44', 'language': 'en', 'genre': ['Horror', 'Suspense', 'Thriller'], 'overview': 'After a vintage Chucky doll turns up at a suburban yard sale, an idyllic American town is thrown into chaos as a series of horrifying murders begin to expose the town hypocrisies and secrets. Meanwhile, the arrival of enemies and allies from Chucky past threatens to expose the truth behind the killings, as well as the demon doll untold origins.', 'lastUpdated': 1639632035, 'airsDayOfWeek': 'Tuesday', 'airsTime': '10:00 PM', 'rating': 'TV-MA', 'imdbId': 'tt8388390', 'zap2itId': '', 'added': '2018-06-22 13:11:28', 'addedBy': 161224, 'siteRating': 0, 'siteRatingCount': 0, 'slug': 'chucky'}
INFO:subliminal.refiners.tvdb:Getting series episode 1x5
DEBUG:subliminal.refiners.tvdb:Found episode {'id': 8558056, 'airedSeason': 1, 'airedSeasonID': 1917827, 'airedEpisodeNumber': 5, 'episodeName': 'Little Little Lies', 'firstAired': '2021-11-09', 'guestStars': ['Annie Briggs', 'Barbara Alyn Woods', 'Blaise Crocker', 'Carina Battrick', 'Devon Sawa', 'Eric Tzogas', 'Jana Peck', 'Joseph Daly', 'Lexa Doig', 'Marienne Castro', 'Michael Therriault', 'Neil Babcock', 'Nick A Fisher', 'Rachelle Casseus', 'Rosemary Dunsmore', 'Samantha Brown'], 'directors': ['Leslie Libman'], 'writers': ['Don Mancini', 'Harley Peyton', 'Rachael Paradis'], 'overview': "Jake and Devon progress their relationship. Enemies-and allies-from Chucky's past show up.", 'language': {'episodeName': 'en', 'overview': 'en'}, 'productionCode': '01005', 'showUrl': '', 'lastUpdated': 1638821065, 'dvdDiscid': '', 'dvdSeason': None, 'dvdEpisodeNumber': None, 'dvdChapter': None, 'absoluteNumber': 5, 'filename': 'v4/episode/8558056/screencap/618bc16da0e13.jpg', 'seriesId': 349415, 'lastUpdatedBy': 166434, 'airsAfterSeason': None, 'airsBeforeSeason': None, 'airsBeforeEpisode': None, 'imdbId': 'tt14413030', 'contentRating': 'TV-MA', 'thumbAuthor': 2247838, 'thumbAdded': '2021-11-10 12:56:13', 'thumbWidth': '640', 'thumbHeight': '360', 'siteRating': 0, 'siteRatingCount': 0, 'isMovie': 0}
INFO:subliminal.core:Refining video with omdb
WARNING:subliminal.refiners.omdb:No apikey. Skipping omdb refiner.
Collecting videos  [####################################]  100%  Chucky.S01E05.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.mkCollecting videos  [####################################]  100%                                                         
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [------------------------------------]    0%  Chucky.S01E05.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.mkvINFO:subliminal.core:Skipping provider 'argenteam': no language to search for
INFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages {<Language [it]>}
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [it]>}
ERROR:subliminal.utils:Unexpected error. Provider legendastv
Traceback (most recent call last):
  File "C:\Users\sarahthrace\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\sarahthrace\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\core.py", line 66, in __getitem__
    provider = provider_manager[name].plugin(**self.provider_configs.get(name, {}))
  File "C:\Users\sarahthrace\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\providers\legendastv.py", line 164, in __init__
    rarfile.custom_check([rarfile.UNRAR_TOOL], True)
AttributeError: module 'rarfile' has no attribute 'custom_check'
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages {<Language [it]>}
INFO:subliminal.core:Skipping provider 'shooter': no language to search for
INFO:subliminal.providers.opensubtitles:Logging in
INFO:subliminal.core:Skipping provider 'thesubdb': not a valid video
INFO:subliminal.core:Initializing provider podnapisi
INFO:subliminal.providers.podnapisi:Searching subtitles {'sXML': 1, 'sL': 'it', 'sK': 'Chucky', 'sTS': 1, 'sTE': 5, 'sY': 2021}
INFO:subliminal.core:Discarding provider legendastv
INFO:subliminal.core:Listing subtitles with provider 'tvsubtitles' and languages {<Language [it]>}
INFO:subliminal.core:Initializing provider tvsubtitles
INFO:subliminal.providers.tvsubtitles:Getting the page for episode 68575
ERROR:subliminal.utils:Unexpected error. Provider opensubtitles
Traceback (most recent call last):
  File "C:\Users\sarahthrace\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\sarahthrace\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\core.py", line 67, in __getitem__
    provider.initialize()
  File "C:\Users\sarahthrace\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\providers\opensubtitles.py", line 129, in initialize
    response = checked(self.server.LogIn(self.username, self.password, 'eng', self.user_agent))
  File "C:\Users\sarahthrace\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\providers\opensubtitles.py", line 278, in checked
    raise Unauthorized
subliminal.providers.opensubtitles.Unauthorized
INFO:subliminal.core:Discarding provider opensubtitles
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '155002' [pt]>
DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'mB9H' [it]>
INFO:subliminal.score:Computing score of <PodnapisiSubtitle 'mB9H' [it]> for video <Episode [Chucky2021 s01e05]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 809, 'series': 405, 'year': 135, 'country': 135, 'season': 45, 'episode': 45, 'release_group': 15, 'streaming_service': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'episode', 'season', 'series', 'video_codec', 'country', 'year', 'source'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 775 with final matches {'episode', 'season', 'series', 'video_codec', 'country', 'hearing_impaired', 'year', 'source'}
INFO:subliminal.core:Downloading subtitle <PodnapisiSubtitle 'mB9H' [it]>
INFO:subliminal.providers.podnapisi:Downloading subtitle <PodnapisiSubtitle 'mB9H' [it]>
INFO:subliminal.subtitle:Guessing encoding for language it
DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'latin-1']
INFO:subliminal.subtitle:Guessed encoding utf-8
INFO:subliminal.subtitle:Guessing encoding for language it
DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'latin-1']
INFO:subliminal.subtitle:Guessed encoding utf-8
DEBUG:subliminal.core:All languages downloaded
Downloading subtitles  [####################################]  100%  Chucky.S01E05.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViDownloading subtitles  [####################################]  100%                                                     
Some providers have been discarded due to unexpected errors: opensubtitles, legendastv
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider podnapisi
INFO:subliminal.core:Terminating provider tvsubtitles
INFO:subliminal.core:Saving <PodnapisiSubtitle 'mB9H' [it]> to 'Chucky.S01E05.1080p.AMZN.WEB-DL.DDP5.1.H.264-NOSiViD.it.srt'
Downloaded 1 subtitle
```

**Comment by tp0** [comment]
Apparently back in OpenSSL default security level was increased and this error comes up for sites using old type of certificates.

https://github.com/psf/requests/issues/4775

This bypassed the error podnapisi.net for me.

`man /usr/share/doc/libssl1.1/NEWS.Debian.gz`

```
  Changing  back the defaults in /etc/ssl/openssl.cnf to previous
system wide
  defaults can be by adding at the top of the file:

    # System default
    openssl_conf = default_conf

  and adding at the bottom of the file:

    [default_conf]
    ssl_conf = ssl_sect

    [ssl_sect]
    system_default = system_default_sect

    [system_default_sect]
    CipherString = DEFAULT:@SECLEVEL=1
```
