### ISSUE TITLE
Can't run on Mac Os X

### ISSUE THREAD

**Issue by Gsuz** [Diaoul/subliminal#184]
I get this error when trying to run on OS X mountain lion: 

subliminal
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 5, in <module>
    pkg_resources.run_script('subliminal==0.6.2', 'subliminal')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 489, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1214, in run_script
    exec script_code in namespace, namespace
  File "/Library/Python/2.7/site-packages/subliminal-0.6.2-py2.7.egg/EGG-INFO/scripts/subliminal", line 24, in <module>

  File "build/bdist.macosx-10.8-intel/egg/subliminal/**init**.py", line 18, in <module>
  File "build/bdist.macosx-10.8-intel/egg/subliminal/api.py", line 18, in <module>
  File "build/bdist.macosx-10.8-intel/egg/subliminal/core.py", line 22, in <module>
  File "build/bdist.macosx-10.8-intel/egg/subliminal/videos.py", line 21, in <module>
  File "build/bdist.macosx-10.8-intel/egg/enzyme/core.py", line 25, in <module>
  File "build/bdist.macosx-10.8-intel/egg/enzyme/strutils.py", line 27, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 496, in getdefaultlocale
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 428, in _parse_localename
ValueError: unknown locale: UTF-8

**Comment by raypatel** [comment]
To bump this issue. Attempting to grab subs for a file results in:

```
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==0.7.5', 'console_scripts', 'subliminal')()
  File "/Library/Python/2.7/site-packages/subliminal/cli.py", line 140, in subliminal
    if not os.path.exists(p)])
  File "/Library/Python/2.7/site-packages/subliminal/video.py", line 63, in fromguess
    return Episode.fromguess(name, guess)
  File "/Library/Python/2.7/site-packages/subliminal/video.py", line 110, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
```

On OSX Yosemite 10.10.2
