### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 12: ordinal not in range(128)

### ISSUE THREAD

**Issue by Ulrar** [Diaoul/subliminal#186]
Hi,

Since a few days, I can't get subliminal to download anything.
I don't understand why, as I didn't changed anything, but I got that : 

Traceback (most recent call last):
  File "/usr/bin/subliminal", line 5, in <module>
    pkg_resources.run_script('subliminal==0.6.3', 'subliminal')
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 500, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 1236, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib64/python2.7/site-packages/subliminal-0.6.3-py2.7.egg/EGG-INFO/scripts/subliminal", line 99, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/subliminal-0.6.3-py2.7.egg/EGG-INFO/scripts/subliminal", line 83, in main
    force=args.force, multi=args.multi, scan_filter=scan_filter)
  File "/usr/lib64/python2.7/site-packages/subliminal-0.6.3-py2.7.egg/subliminal/async.py", line 134, in download_subtitles
    subtitles_by_video = self.list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/usr/lib64/python2.7/site-packages/subliminal-0.6.3-py2.7.egg/subliminal/async.py", line 120, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/usr/lib64/python2.7/site-packages/subliminal-0.6.3-py2.7.egg/subliminal/core.py", line 57, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "/usr/lib64/python2.7/site-packages/subliminal-0.6.3-py2.7.egg/subliminal/videos.py", line 233, in scan
    return [(video, video.scan())]
  File "/usr/lib64/python2.7/site-packages/subliminal-0.6.3-py2.7.egg/subliminal/videos.py", line 140, in scan
    existing = [f for f in os.listdir(folder) if f.startswith(basename)]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 12: ordinal not in range(128)

That's not the usual unicode problem, that's actually located in an other file.
I have tried to pull the latest version, but it does the same.

**Comment by jandrioli** [comment]
Do you have a properly configured locale?
http://stackoverflow.com/a/10563157/4169615
