### ISSUE TITLE
Subliminal 0.7.0 SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by Crupuk** [Diaoul/subliminal#233]
I just updated subliminal on my server and now i get this error : 

```
subliminal --lang fr /var/lib/transmission/Downloads/en/The.Walking.Dead.S04E03.720p.HDTV.x264-KILLERS.mkv
Traceback (most recent call last):
  File "/usr/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==0.7.0', 'console_scripts', 'subliminal')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/subliminal/__init__.py", line 9, in <module>
    from .api import PROVIDERS_ENTRY_POINT, list_subtitles, download_subtitles, download_best_subtitles
  File "/usr/lib/python2.6/site-packages/subliminal/api.py", line 85
    providers_by_name = {ep.name: ep.load() for ep in pkg_resources.iter_entry_points(PROVIDERS_ENTRY_POINT)}
                                              ^
SyntaxError: invalid syntax
```

```
# rpm -qa | grep python
python-2.6.6-37.el6_4.x86_64
```

```
# pip freeze | grep subliminal
subliminal==0.7.0
```

```
# cat /etc/redhat-release
CentOS release 6.4 (Final)
```

if you need more info , just ask me.
I'm glad to help you with this error

Thanks for yuour job and for this release !!

**Comment by AdUki** [comment]
It is not said in `subliminal --help`!
Please update help text...
