### ISSUE TITLE
[0.7.3 W7x64] Sometimes my Date Modified is NULL/empty

### ISSUE THREAD

**Issue by DarkAllMan** [Diaoul/subliminal#281]
In very rare cases some of my downloaded files do not have a Date Modified property. It is null or empty and subliminal crashes on it.

'Traceback (most recent call last):
  File "C:\Python27\Scripts\subliminal-script.py", line 9, in <module>
    load_entry_point('subliminal==0.7.3', 'console_scripts', 'subliminal')()
  File "build\bdist.win-amd64\egg\subliminal\cli.py", line 146, in subliminal
  File "build\bdist.win-amd64\egg\subliminal\video.py", line 325, in scan_videos

ValueError: timestamp out of range for platform localtime()/gmtime() function'
##

**Comment by DarkAllMan** [comment]
Seems its back?
````
ERROR:subliminal.cli:Unexpected error while collecting directory path /media/dns323/TVSERIES
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 334, in download
    scanned_videos = scan_videos(p, age=age, archives=archives)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 495, in scan_videos
    if age and datetime.utcnow() - datetime.utcfromtimestamp(os.path.getmtime(filepath)) > age:
ValueError: year is out of range
````
This is on a file with date modified = NULL

**Comment by Diaoul** [comment]
What version are you using?

**Comment by Diaoul** [comment]
Issue spotted here: https://github.com/Diaoul/subliminal/blob/master/subliminal/core.py#L494-L497

**Comment by DarkAllMan** [comment]
Version 2.0.3
