### ISSUE TITLE
KeyError: u'type'

### ISSUE THREAD

**Issue by ferllings** [Diaoul/subliminal#348]
Hello,

I have an error on a fresh install of subliminal: 
```> subliminal -l fr -- The.Walking.Dead.S04E12.PROPER.HDTV.2HD.mp4
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==0.8.0-dev', 'console_scripts', 'subliminal')()
  File "build/bdist.macosx-10.9-x86_64/egg/subliminal/cli.py", line 177, in subliminal
  File "build/bdist.macosx-10.9-x86_64/egg/subliminal/video.py", line 72, in fromname
  File "build/bdist.macosx-10.9-x86_64/egg/subliminal/video.py", line 64, in fromguess
KeyError: u'type'```

Python 2.7.6 on OSX 10.9
Thanks

**Comment by sioban** [comment]
I thought the problem was corrected with pull request #377 
It seems it's not the case I had to go back to 0.7.0... (latest guessit is 0.10.3)
