### ISSUE TITLE
All of a sudden not downloading anymore

### ISSUE THREAD

**Issue by 10o** [Diaoul/subliminal#374]
Been running 0.8.0-dev for some weeks now. My cron script has been running fine up until five days ago. Since then no subs are downloaded anymore. My script:

/usr/local/bin/subliminal --log-file /home/myname/subliminal.log -l en -v -s -h /mnt/hitachi2tb2/Videos/TV-Series

My log file only show scannings since then.

In /var/mail/myname I notice:

Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==0.8.0-dev', 'console_scripts', 'subliminal')()
  File "/usr/local/lib/python2.7/dist-packages/subliminal-0.8.0_dev-py2.7.egg/subliminal/cli.py", line 174, in subliminal
    embedded_subtitles=not args.force, age=args.age)
  File "/usr/local/lib/python2.7/dist-packages/subliminal-0.8.0_dev-py2.7.egg/subliminal/video.py", line 359, in scan_videos
    video = scan_video(filepath, subtitles, embedded_subtitles)
  File "/usr/local/lib/python2.7/dist-packages/subliminal-0.8.0_dev-py2.7.egg/subliminal/video.py", line 203, in scan_video
    video = Video.fromguess(path, guessit.guess_file_info(path, 'autodetect'))
  File "/usr/local/lib/python2.7/dist-packages/guessit-0.7-py2.7.egg/guessit/__init__.py", line 137, in guess_file_info
    result.append(_guess_filename(filename, filetype))
  File "/usr/local/lib/python2.7/dist-packages/guessit-0.7-py2.7.egg/guessit/__init__.py", line 108, in _guess_filename
    mtree = IterativeMatcher(filename, filetype=filetype)
  File "/usr/local/lib/python2.7/dist-packages/guessit-0.7-py2.7.egg/guessit/matcher.py", line 120, in __init__
    self._apply_transfo(transformer)
  File "/usr/local/lib/python2.7/dist-packages/guessit-0.7-py2.7.egg/guessit/matcher.py", line 132, in _apply_transfo
    transformer.process(self.match_tree, *all_args, **all_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/guessit-0.7-py2.7.egg/guessit/transfo/guess_episodes_rexps.py", line 105, in process
    SingleNodeGuesser(self.guess_episodes_rexps, None, self.log).process(mtree)
  File "/usr/local/lib/python2.7/dist-packages/guessit-0.7-py2.7.egg/guessit/transfo/__init__.py", line 147, in process
    find_and_split_node(node, strategy, self.skip_nodes, self.logger)
  File "/usr/local/lib/python2.7/dist-packages/guessit-0.7-py2.7.egg/guessit/transfo/__init__.py", line 123, in find_and_split_node
    find_and_split_node(child, strategy, skip_nodes, logger)
  File "/usr/local/lib/python2.7/dist-packages/guessit-0.7-py2.7.egg/guessit/transfo/__init__.py", line 76, in find_and_split_node
    matcher_result = matcher(*all_args)
  File "/usr/local/lib/python2.7/dist-packages/guessit-0.7-py2.7.egg/guessit/transfo/guess_episodes_rexps.py", line 86, in guess_episodes_rexps
    guess.set('episodeNumber', eplist[0], confidence=confidence, input=string, span=span)
IndexError: list index out of range

**Comment by Diaoul** [comment]
Try latest stable 0.7.5
