### ISSUE TITLE
Can't download subs for some directories

### ISSUE THREAD

**Issue by mkools** [Diaoul/subliminal#420]
When I run subliminal on some directories especially the ones that contain a lot of movies it crashes with the error below. This is on FreeBSD 10.1.

Thanks!

Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==0.8.0-dev', 'console_scripts', 'subliminal')()
  File "build/bdist.freebsd-10.1-RELEASE-amd64/egg/subliminal/cli.py", line 174, in subliminal
  File "build/bdist.freebsd-10.1-RELEASE-amd64/egg/subliminal/video.py", line 316, in scan_videos
  File "/usr/local/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/local/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 13: ordinal not in range(128)

**Comment by Diaoul** [comment]
That's an issue with the encoding of your filesystem I think. Try latest stable release.
