### ISSUE TITLE
bierdopje and podnapsi providers throw errors

### ISSUE THREAD

**Issue by akatch** [Diaoul/subliminal#430]
When using the default providers list (which includes bierdopje and podnapsi), subliminal throws the following errors:
...
ERROR: Unexpected error in provider 'bierdopje'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/subliminal/api.py", line 216, in download_best_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_video_languages)
  File "/usr/lib/python3/dist-packages/subliminal/providers/bierdopje.py", line 121, in list_subtitles
    return [s for l in languages for s in self.query(l, video.season, video.episode, video.tvdb_id, video.series)]
  File "/usr/lib/python3/dist-packages/subliminal/providers/bierdopje.py", line 121, in <listcomp>
    return [s for l in languages for s in self.query(l, video.season, video.episode, video.tvdb_id, video.series)]
  File "/usr/lib/python3/dist-packages/subliminal/providers/bierdopje.py", line 104, in query
    show_id = self.find_show_id(series)
  File "/usr/lib/python3/dist-packages/dogpile/cache/region.py", line 1013, in decorate
    should_cache_fn)
  File "/usr/lib/python3/dist-packages/dogpile/cache/region.py", line 640, in get_or_create
    async_creator) as value:
  File "/usr/lib/python3/dist-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/lib/python3/dist-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/lib/python3/dist-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/usr/lib/python3/dist-packages/dogpile/cache/region.py", line 612, in gen_value
    created_value = creator()
  File "/usr/lib/python3/dist-packages/dogpile/cache/region.py", line 1009, in creator
    return fn(*arg, **kw)
  File "/usr/lib/python3/dist-packages/subliminal/providers/bierdopje.py", line 92, in find_show_id
    root = self.get('FindShowByName/{series}', series=urllib.quote(series))
AttributeError: 'module' object has no attribute 'quote'
...
ERROR: Unexpected error in provider 'podnapisi'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/subliminal/api.py", line 216, in download_best_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_video_languages)
  File "/usr/lib/python3/dist-packages/subliminal/providers/podnapisi.py", line 141, in list_subtitles
    return [s for l in languages for s in self.query(l, series=video.series, season=video.season,
  File "/usr/lib/python3/dist-packages/subliminal/providers/podnapisi.py", line 142, in <listcomp>
    episode=video.episode)]
  File "/usr/lib/python3/dist-packages/subliminal/providers/podnapisi.py", line 128, in query
    for s in root.findall('subtitle')])
  File "/usr/lib/python3/dist-packages/subliminal/providers/podnapisi.py", line 128, in <listcomp>
    for s in root.findall('subtitle')])
AttributeError: 'NoneType' object has no attribute 'split'
...

If I specify a providers list that excludes bierdopje and podnapsi, no errors are shown. Aside from the errors being thrown, subtitles appear to download fine, assuming any are found.

**Comment by G1zm0** [comment]
See https://github.com/Diaoul/subliminal/issues/337 for "Bierdopje".
