### ISSUE TITLE
Failure after upgrading to 0.7.5-11 - ImportError: No module named stevedore

### ISSUE THREAD

**Issue by tyxak** [Diaoul/subliminal#439]
Hi

First of all, thank you for your great work. It's much appreciated.
I have a issue after upgrading to 0.7.5-11, I get the following message:

tvipper01> /usr/local/subliminal/env/bin/subliminal /volume1/Tvipper/Movies/ -a
30d -l en
Traceback (most recent call last):
  File "/usr/local/subliminal/env/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/cli.py", line 136, in subliminal
    embedded_subtitles=not args.force, age=args.age)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/video.py", line 364, in scan_videos
    video = scan_video(filepath, subtitles, embedded_subtitles)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/video.py", line 218, in scan_video
    guessit.guess_file_info(path, info=['filename']),
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/guessit/__init__.py", line 291, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/guessit/__init__.py", line 111, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/guessit/__init__.py", line 118, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=options, **kwargs)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/guessit/matcher.py", line 109, in __init__
    from guessit.plugins import transformers
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 24, in <module>
    from stevedore import ExtensionManager
ImportError: No module named stevedore

//
- Hardware/OS: Synology 415+ DSM 5.2-5532
- Python: 2.7.8.-11

Please let me know, if you want me to do anything from CLI/interface.

**Comment by tyxak** [comment]
- Hardware/OS:
Synology 415+ DSM 5.2-5532
- All packages are up to date.

Please let me know, if you want me to do anything from CLI.

**Comment by rockisdead** [comment]
Hello,
Same here...

Traceback (most recent call last):
  File "/usr/local/subliminal/env/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/cli.py", line 136, in subliminal
    embedded_subtitles=not args.force, age=args.age)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/video.py", line 364, in scan_videos
    video = scan_video(filepath, subtitles, embedded_subtitles)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/subliminal/video.py", line 218, in scan_video
    guessit.guess_file_info(path, info=['filename']),
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/guessit/__init__.py", line 291, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/guessit/__init__.py", line 111, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/guessit/__init__.py", line 118, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=options, **kwargs)
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/guessit/matcher.py", line 109, in __init__
    from guessit.plugins import transformers
  File "/usr/local/subliminal/env/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 24, in <module>
    from stevedore import ExtensionManager
ImportError: No module named stevedore

//

Hardware/OS: DSM 5.1-5022 Update 3 , Synology DS213
Python 2.7.8-11

**Comment by SeeDborg** [comment]
Same here...

**Comment by caronc** [comment]
That would be a bug with guessit.  it's requirements.txt file (which pip uses to fetch dependencies) should have an entry reading:
```
stevedore>=0.14
```
You can easily fix this by just running:
```bash
pip install stevedore
```

**Comment by tyxak** [comment]
> tvipper01> pip install stevedore
> -ash: pip: not found

I don't think Synology boxes are ready for pip command.

**Comment by caronc** [comment]
That's too bad; sorry for the bad advice.  The bug is definitely part of [guessit](https://github.com/wackou/guessit) though. The patch will need to come from them.

**Comment by tyxak** [comment]
@caronc 
A new update has been released, and it fixed the problem. Sublimimal is now working as intended. :-)

Thank you for the advice anyway!

**Comment by caronc** [comment]
@tyxak : [Code and Syntax Highlightning](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting)

Glad you got it working! :)

**Comment by tyxak** [comment]
`Thanks` :-)
