### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cache_dir'

### ISSUE THREAD

**Issue by Stevestar** [Diaoul/subliminal#442]
Hi,

I'm using a Raspberry Pi 2 running Xbian and Sick Beard gives the following error.
I tried this solution (https://github.com/Diaoul/subliminal/issues/140#issuecomment-81847774) but it didn't work..

My error code:
2015-03-16 17:47:26 FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
File "/usr/local/share/sickbeard/sickbeard/tv.py", line 1194, in downloadSubtitles
subtitles = subliminal.download_subtitles([self.location], languages=need_languages, services=sickbeard.subtitles.getEnabledServiceList(), force=force, multi=True, cache_dir=sickbeard.CACHE_DIR)
File "/usr/local/share/sickbeard/lib/subliminal/api.py", line 95, in download_subtitles
subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
File "/usr/local/share/sickbeard/lib/subliminal/api.py", line 54, in list_subtitles
tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
File "/usr/local/share/sickbeard/lib/subliminal/core.py", line 80, in create_list_tasks
logger.debug(u'Created task %r' % task)
File "/usr/local/share/sickbeard/lib/subliminal/tasks.py", line 45, in repr
return 'ListTask(%r, %r, %s, %r)' % (self.video, self.languages, self.service, self.config)
File "/usr/local/share/sickbeard/lib/subliminal/services/init.py", line 259, in repr
return 'ServiceConfig(%r, %s)' % (self.multi, self.cache_dir)
AttributeError: 'NoneType' object has no attribute 'cache_dir'

**Comment by Stevestar** [comment]
anyone, please?
