### ISSUE TITLE
[0.7.5] Error with podnapisi 

### ISSUE THREAD

**Issue by slashy1302** [Diaoul/subliminal#445]
I get this error on every run.

ERROR: Unexpected error in provider 'podnapisi'
Traceback (most recent call last):
  File "C:\Python27\subliminal\api.py", line 256, in download_best_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_video_languages)
  File "C:\Python27\subliminal\providers\podnapisi.py", line 171, in list_subtitles
    episode=video.episode)]
  File "C:\Python27\subliminal\providers\podnapisi.py", line 139, in query
    root = self.get('/ppodnapisi/search', params)
  File "C:\Python27\subliminal\providers\podnapisi.py", line 120, in get
    return xml.etree.ElementTree.fromstring(r.content)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1281, in XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1623, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1487, in _raiseerror
    raise err
ParseError: mismatched tag: line 55, column 2

**Comment by caronc** [comment]
I think I've fixed this error [here](https://github.com/caronc/nzbget-subliminal/issues/12) in my fork. Here is the [commit](https://github.com/caronc/subliminal/commit/9651d767504f6306ae0177e9dfbaec0d68e3b029) itself. This is part of pull request #434.
