### ISSUE TITLE
Unexpected error in provider addic7ed

### ISSUE THREAD

**Issue by Jarown** [Diaoul/subliminal#447]
Hi,

I'm using subliminal version 0.8.0-dev. When I try to use 'addic7ed' as provider, I get this message:

INFO     [subliminal.api] Listing subtitles for < Episode [u'Hart of Dixie', 4x9] >
INFO     [subliminal.providers.addic7ed] Logged in
INFO     [subliminal.providers] Listing subtitles with provider 'addic7ed' and languages set([ < Language [nl] > ])
ERROR    [subliminal.providers] Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-intel/egg/subliminal/providers/__ init __.py", line 224, in list_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_languages)
  File "build/bdist.macosx-10.10-intel/egg/subliminal/providers/addic7ed.py", line 194, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
...

The login seems to work, so any idea what goes wrong here?

Thanks in advance,
Jeroen

**Comment by Jarown** [comment]
Found it! Looks like the problem is an invalid cache-file after my "subliminal -c" option
