### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by jorti** [Diaoul/subliminal#454]
I'm using subliminal as a library, and I hit this error when trying to download a subtitle:

```
Traceback (most recent call last):
  File "./extract-subs.py", line 110, in <module>
    main(sys.argv)
  File "./extract-subs.py", line 106, in main
    extract_subs(file_list)
  File "./extract-subs.py", line 68, in extract_subs
    download_subs(file)
  File "./extract-subs.py", line 49, in download_subs
    video = subliminal.scan_videos([file['full_path'], ], subtitles=False, embedded_subtitles=False)
  File "/usr/lib/python3.4/site-packages/subliminal/video.py", line 320, in scan_videos
    videos.append(scan_video(filepath, subtitles, embedded_subtitles))
  File "/usr/lib/python3.4/site-packages/subliminal/video.py", line 224, in scan_video
    video.hashes['opensubtitles'] = hash_opensubtitles(path)
  File "/usr/lib/python3.4/site-packages/subliminal/video.py", line 386, in hash_opensubtitles
    for _ in range(65536 / bytesize):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by Diaoul** [comment]
I cannot reproduce this with my local version. I made a lot of changes so this may be already fixed

**Comment by kakai248** [comment]
This error happens on python 3. Can be fixed by putting ```int(65536 / bytesize)``` on both line 386 and 392 of ```video.py```.

After fixing this there is also an error on line 416:
```
AttributeError: 'str' object has no attribute 'decode'
```

Can be fixed by removing ```.decode('ascii')```. I tested and the hashes match after these changes for both situations.

**Comment by Diaoul** [comment]
I will make a new release soon with those changes.
