### ISSUE TITLE
Traceback : TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by sioban** [Diaoul/subliminal#464]
Hi,

I'm trying the last subliminal version:
> # subliminal --version
subliminal, version 1.0.dev0

I'm getting an error when I try to download a srt:
> # subliminal download ./the.strain.2x01-bk.n.y-sd.tv-killers.mp4
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==1.0.dev0', 'console_scripts', 'subliminal')()
  File "/usr/local/lib/python2.7/dist-packages/click-4.1-py2.7.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-4.1-py2.7.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-4.1-py2.7.egg/click/core.py", line 988, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-4.1-py2.7.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-4.1-py2.7.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-i686/egg/subliminal/cli.py", line 100, in subliminal
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

Are you aware of that problem ?

**Comment by Diaoul** [comment]
Fixed with 43d02c349f4c1f26c27b66897356c024e0ff18df
