### ISSUE TITLE
setup.py test error

### ISSUE THREAD

**Issue by discoHR** [Diaoul/subliminal#476]
disco@lenovo subliminal-master$ subliminal --version
subliminal, version 1.0.1
disco@lenovo subliminal-master$ sudo python setup.py test
running test
Searching for mock
Reading https://pypi.python.org/simple/mock/
Best match: mock 1.3.0
Downloading https://pypi.python.org/packages/source/m/mock/mock-1.3.0.tar.gz#md5=73ee8a4afb3ff4da1b4afa287f39fdeb
Processing mock-1.3.0.tar.gz
Writing /tmp/easy_install-Wv3aDN/mock-1.3.0/setup.cfg
Running mock-1.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Wv3aDN/mock-1.3.0/egg-dist-tmp-zwpqoi

Installed /tmp/easy_install-Wv3aDN/mock-1.3.0/.eggs/pbr-1.3.0-py2.7.egg
creating /home/disco/downloads/subliminal-master/.eggs/mock-1.3.0-py2.7.egg
Extracting mock-1.3.0-py2.7.egg to /home/disco/downloads/subliminal-master/.eggs

Installed /home/disco/downloads/subliminal-master/.eggs/mock-1.3.0-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 102, in <module>
    cmdclass={'test': PyTest})
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/test.py", line 134, in run
    self.distribution.fetch_build_eggs(self.distribution.tests_require)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 847, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2602, in requires
    dm = self._dep_map
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2597, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2930, in parse_requirements
    "version spec")
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2895, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected version spec in funcsigs;python_version<"3.3" at ;python_version<"3.3"
disco@lenovo subliminal-master$ python --version
Python 2.7.6

**Comment by Diaoul** [comment]
It works with travis build, maybe try another install method. You don't need sudo to run tests. Maybe update your pip or setuptools.
Report this upstream (mock is causing the issue here it seems).

**Comment by discoHR** [comment]
You're right, mock is causing it. Sorry for misreporting it here.
