### ISSUE TITLE
subliminal download command: "download() got multiple values for keyword argument 'provider'"

### ISSUE THREAD

**Issue by vaz-ar** [Diaoul/subliminal#487]
Hello,

I'm having trouble with the last version of subliminal (1.0.1), here is the error I got:
```
Traceback (most recent call last):
  File "/root/.virtualenvs/odl/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/root/.virtualenvs/odl/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/root/.virtualenvs/odl/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/root/.virtualenvs/odl/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.virtualenvs/odl/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.virtualenvs/odl/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/root/.virtualenvs/odl/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.virtualenvs/odl/local/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
TypeError: download() got multiple values for keyword argument 'provider'
```

Here are the commands I tried:
`subliminal download -l en my_video.mkv`
`subliminal download -l en -p opensubtitles -p podnapisi my_video.mkv`

I have the problem on debian (python 2.7) and on windows (Cygwin, python 3.4 and 2.7).

Does anyone else have the same problem ? From what I see it seems to come from `click`, maybe a recent change in the library? My version of `click` is 5.0 .

**Comment by vaz-ar** [comment]
Ok so I just choose the worst time to upgrade, the version 5.0 of click was released an hour ago...

**Comment by Diaoul** [comment]
Can you reproduce with click 5.1?

**Comment by vaz-ar** [comment]
Yes I just saw, thanks. Nevertheless you should still change the setup to not use click "5.0", just in case.

**Comment by Diaoul** [comment]
Keeping track of all the dependency versions and bugfixes is a lot of work. If that kind of issues persist I will consider it but for now I use API-level compatibility requirements.
