### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by cpecquerie** [Diaoul/subliminal#499]
Hi, when running subliminal

``` subliminal download /mnt/series/Fear.the.Walking.Dead -l fr -v", ```

I get the following error.

It happens on this file : "Fear.the.Walking.Dead.S01E02.HDTV-720p.Proper.x264.AC3-KILLERS.mkv"

Best regards,
Christophe.

```
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 269, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/api.py", line 185, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/podnapisi.py", line 61, in get_matches
    matches |= guess_matches(video, guess_episode_info(release + '.mkv'))
  File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 370, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 302, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 114, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 127, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=merged_options, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/usr/local/lib/python2.7/dist-packages/guessit/transfo/guess_language.py", line 125, in process
    GuessFinder(self.guess_language, None, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 227, in process_nodes
    self.process_node(node)
  File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 269, in process_node
    self.process_node(node, partial_span=relative_span)
  File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 269, in process_node

.... REPEATING

File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 269, in process_node
    self.process_node(node, partial_span=relative_span)
  File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 269, in process_node
    self.process_node(node, partial_span=relative_span)
  File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 269, in process_node
    self.process_node(node, partial_span=relative_span)
  File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 236, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "/usr/local/lib/python2.7/dist-packages/guessit/transfo/guess_language.py", line 46, in guess_language
    guess = search_language(string, allowed_languages)
  File "/usr/local/lib/python2.7/dist-packages/guessit/language.py", line 277, in search_language
    for prop, language, lang, word in find_possible_languages(string, allowed_languages):
  File "/usr/local/lib/python2.7/dist-packages/guessit/language.py", line 251, in find_possible_languages
    elif lang == 'mul' or hasattr(lang, 'alpha2'):
  File "/usr/local/lib/python2.7/dist-packages/babelfish/language.py", line 159, in __eq__
    return str(self) == other
  File "/usr/local/lib/python2.7/dist-packages/babelfish/language.py", line 178, in __str__
    s = self.alpha2
  File "/usr/local/lib/python2.7/dist-packages/babelfish/language.py", line 150, in __getattr__
    return language_converters[name].convert(alpha3, country, script)
  File "/usr/local/lib/python2.7/dist-packages/babelfish/converters/__init__.py", line 159, in convert
    raise LanguageConvertError(alpha3, country, script)
RuntimeError: maximum recursion depth exceeded'''
```

**Comment by Diaoul** [comment]
This is an issue with guessit and should be reported to [guessit](https://github.com/wackou/guessit). Make sure you have latest version of guessit installed and searched guessit's closed issues first.
