### ISSUE TITLE
Error using subliminal

### ISSUE THREAD

**Issue by lbonacina** [Diaoul/subliminal#517]
Hi, i've just installed subliminal on my QNAP NAS, but when i try to download a subtitle i get the following error:

    ERROR:subliminal.cli:Unexpected error while collecting path TheStrains02e10.mkv
    Traceback (most recent call last):
      File "/Apps/opt/lib/python2.7/site-packages/subliminal-1.0.1-py2.7.egg/subliminal/cli.py", line 222, in       download
         video = scan_video(p, subtitles=not force, embedded_subtitles=not force)
      File "/Apps/opt/lib/python2.7/site-packages/subliminal-1.0.1-py2.7.egg/subliminal/video.py", line 322, in scan_video
        mkv = MKV(f)
      File "/Apps/opt/lib/python2.7/site-packages/enzyme-0.4.1-py2.7.egg/enzyme/mkv.py", line 39, in __init__
        specs = ebml.get_matroska_specs()
      File "/Apps/opt/lib/python2.7/site-packages/enzyme-0.4.1-py2.7.egg/enzyme/parsers/ebml/core.py", line 235, in get_matroska_specs
        with resource_stream(__name__, 'specs/matroska.xml') as resource:
    AttributeError: __exit__
    Collecting videos  [####################################]  100%
    0 video collected / 0 video ignored / 1 error

maybe something wrong with my installation ? 

thanks

Luigi

**Comment by Diaoul** [comment]
Yep, try reinstalling enzyme.

**Comment by lbonacina** [comment]
i've tried reinstalling enzyme but with no success.
problem is i cant use pip (openssl/certificates problem i think, got some errors while downloading packages on QNAP NAS) and i've resorted to install all the packages manually.

**Comment by Diaoul** [comment]
I don't know on QNap but on Synology NAS pip is available and works fine, subliminal too. I suggest you ask the QNap community for help as this doesn't seem to be releated to enzyme or subliminal in any way.
