### ISSUE TITLE
Invalid movie/series name guess with special characters in it

### ISSUE THREAD

**Issue by Crupuk** [Diaoul/subliminal#521]
Subliminal can't find a subtitle for a old file ( 25/09 )

```
# /opt/venv/bin/subliminal --debug --addic7ed xxxxxx xxxxxx download -v -s -f -l fr -- /dlna/shows/en/Greys\ Anatomy/S12/Greys.Anatomy.S12E01.REPACK.720p.HDTV.x264-KILLERS.mkv
/opt/venv/lib/python2.7/site-packages/subliminal/cli.py:115: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.pass_context
/opt/venv/lib/python2.7/site-packages/subliminal/cli.py:145: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.pass_context
/opt/venv/lib/python2.7/site-packages/subliminal/cli.py:172: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.pass_obj
Collecting videos  [####################################]  100%  /dlna/shows/en/Greys Anatomy/S12/Greys.Anatomy.S12E01.REPACK.720p.HDTV.x264-KILLERS.mkvDEBUG:subliminal.cli:Collecting path /dlna/shows/en/Greys Anatomy/S12/Greys.Anatomy.S12E01.REPACK.720p.HDTV.x264-KILLERS.mkv
INFO:subliminal.video:Scanning video u'Greys.Anatomy.S12E01.REPACK.720p.HDTV.x264-KILLERS.mkv' in u'/dlna/shows/en/Greys Anatomy/S12'
DEBUG:subliminal.video:Size is 1041943437
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'74a95f311bfabeda', u'thesubdb': '3772a98161b63d013e679970884036c3'}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:MKV has no subtitle track
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Greys.Anatomy.S12E01.REPACK.720p.HDTV.x264-KILLERS.mkvINFO:subliminal.api:Listing subtitles with provider 'thesubdb' and languages set([<Language [fr]>])
INFO:subliminal.api:Initializing provider thesubdb
INFO:subliminal.providers.thesubdb:Searching subtitles {u'action': u'search', u'hash': '3772a98161b63d013e679970884036c3'}
INFO:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '3772a98161b63d013e679970884036c3' [en]>
INFO:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '3772a98161b63d013e679970884036c3' [pt]>
INFO:subliminal.api:Listing subtitles with provider 'opensubtitles' and languages set([<Language [fr]>])
INFO:subliminal.api:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'keo4pt4j7ljpgugns2l5t3q4k0'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{u'moviebytesize': '1041943437', u'sublanguageid': u'fre', u'moviehash': u'74a95f311bfabeda'}, {u'query': u'Greys Anatomy', u'sublanguageid': u'fre', u'episode': 1, u'season': 12}]
INFO:subliminal.providers.opensubtitles:No subtitles found
INFO:subliminal.api:Listing subtitles with provider 'addic7ed' and languages set([<Language [fr]>])
INFO:subliminal.api:Initializing provider addic7ed
INFO:subliminal.providers.addic7ed:Logging in
DEBUG:subliminal.providers.addic7ed:Logged in
DEBUG:subliminal.providers.addic7ed:Getting show id
INFO:subliminal.providers.addic7ed:Getting the page of show id 30, season 12
ERROR:subliminal.api:Unexpected error in provider 'addic7ed', discarding it
Traceback (most recent call last):
  File "/opt/venv/lib/python2.7/site-packages/subliminal/api.py", line 117, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/opt/venv/lib/python2.7/site-packages/subliminal/providers/addic7ed.py", line 257, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/opt/venv/lib/python2.7/site-packages/subliminal/providers/addic7ed.py", line 227, in query
    series = match.group('series')
AttributeError: 'NoneType' object has no attribute 'group'
INFO:subliminal.api:Listing subtitles with provider 'podnapisi' and languages set([<Language [fr]>])
INFO:subliminal.api:Initializing provider podnapisi
INFO:subliminal.providers.podnapisi:Searching subtitles {u'sK': u'Greys Anatomy', u'sTE': 1, u'sXML': 1, u'sTS': 12, u'sL': 'fr'}
DEBUG:subliminal.providers.podnapisi:No subtitles found
INFO:subliminal.api:Listing subtitles with provider 'tvsubtitles' and languages set([<Language [fr]>])
INFO:subliminal.api:Initializing provider tvsubtitles
ERROR:subliminal.providers.tvsubtitles:No show id found for u'Greys Anatomy' ({u'year': None})
Downloading subtitles  [####################################]  100%
DEBUG:subliminal.api:Terminating initialized providers
INFO:subliminal.api:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
INFO:subliminal.api:Terminating provider thesubdb
INFO:subliminal.api:Terminating provider podnapisi
INFO:subliminal.api:Terminating provider addic7ed
INFO:subliminal.providers.addic7ed:Logging out
DEBUG:subliminal.providers.addic7ed:Logged out
INFO:subliminal.api:Terminating provider tvsubtitles
0 subtitle downloaded for Greys.Anatomy.S12E01.REPACK.720p.HDTV.x264-KILLERS.mkv
```

Manuel search : 
http://www.opensubtitles.org/fr/subtitles/6317363/grey-s-anatomy-sledgehammer-fr
http://www.addic7ed.com/serie/Grey%27s_Anatomy/12/1/Sledgehammer

I will open a new issue for the error with addic7ed .

Why this subtitles was not found ?

Thanks for your help

**Comment by Diaoul** [comment]
Because from the filename there is no way to tell it's `Grey's Anatomy` and not `Greys Anatomy`. The different searches yield no result.

**Comment by Crupuk** [comment]
Ok thank's for the reply.
I need to rename the file before calling subliminal.

**Comment by Diaoul** [comment]
No you don't, there are some improvements that can be made in subliminal to fix this issue. Like calling a webservice to retrieve the correct series name or search tvdb/moviedb/imdb/*db.

Let's leave this open for now until I investigate what can be done and if it's in subliminal's scope.

**Comment by Crupuk** [comment]
Ok, thanks

Just for info, subliminal just found two subtitles for any of the previous saison episodes 

```
# /opt/venv/bin/subliminal --debug --addic7ed xxxxxx xxxxxx download -v -s -f -l fr -- /dlna/shows/en/Greys\ Anatomy/S11/greys.anatomy.1119.hdtv-lol.mp4
/opt/venv/lib/python2.7/site-packages/subliminal/cli.py:115: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.pass_context
/opt/venv/lib/python2.7/site-packages/subliminal/cli.py:145: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.pass_context
/opt/venv/lib/python2.7/site-packages/subliminal/cli.py:172: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.pass_obj
Collecting videos  [####################################]  100%  /dlna/shows/en/Greys Anatomy/S11/greys.anatomy.1119.hdtv-lol.mp4DEBUG:subliminal.cli:Collecting path /dlna/shows/en/Greys Anatomy/S11/greys.anatomy.1119.hdtv-lol.mp4
INFO:subliminal.video:Scanning video u'greys.anatomy.1119.hdtv-lol.mp4' in u'/dlna/shows/en/Greys Anatomy/S11'
DEBUG:subliminal.video:Size is 242507566
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'88cbf02fa84d7665', u'thesubdb': '5d78eb8a92f3f97813404641c67c06c8'}
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  greys.anatomy.1119.hdtv-lol.mp4INFO:subliminal.api:Listing subtitles with provider 'thesubdb' and languages set([<Language [fr]>])
INFO:subliminal.api:Initializing provider thesubdb
INFO:subliminal.providers.thesubdb:Searching subtitles {u'action': u'search', u'hash': '5d78eb8a92f3f97813404641c67c06c8'}
INFO:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '5d78eb8a92f3f97813404641c67c06c8' [en]>
INFO:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '5d78eb8a92f3f97813404641c67c06c8' [es]>
INFO:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '5d78eb8a92f3f97813404641c67c06c8' [fr]>
INFO:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '5d78eb8a92f3f97813404641c67c06c8' [pt]>
INFO:subliminal.api:Listing subtitles with provider 'opensubtitles' and languages set([<Language [fr]>])
INFO:subliminal.api:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'a0pg50p7ueem51uv286nh5gu77'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{u'moviebytesize': '242507566', u'sublanguageid': u'fre', u'moviehash': u'88cbf02fa84d7665'}, {u'query': u'Greys Anatomy', u'sublanguageid': u'fre', u'episode': 19, u'season': 11}]
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1954691666' [fr]>
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1954693839' [fr]>
INFO:subliminal.api:Listing subtitles with provider 'addic7ed' and languages set([<Language [fr]>])
INFO:subliminal.api:Initializing provider addic7ed
INFO:subliminal.providers.addic7ed:Logging in
DEBUG:subliminal.providers.addic7ed:Logged in
DEBUG:subliminal.providers.addic7ed:Getting show id
INFO:subliminal.providers.addic7ed:Getting the page of show id 30, season 11
ERROR:subliminal.api:Unexpected error in provider 'addic7ed', discarding it
Traceback (most recent call last):
  File "/opt/venv/lib/python2.7/site-packages/subliminal/api.py", line 117, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/opt/venv/lib/python2.7/site-packages/subliminal/providers/addic7ed.py", line 257, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/opt/venv/lib/python2.7/site-packages/subliminal/providers/addic7ed.py", line 227, in query
    series = match.group('series')
AttributeError: 'NoneType' object has no attribute 'group'
INFO:subliminal.api:Listing subtitles with provider 'podnapisi' and languages set([<Language [fr]>])
INFO:subliminal.api:Initializing provider podnapisi
INFO:subliminal.providers.podnapisi:Searching subtitles {u'sK': u'Greys Anatomy', u'sTE': 19, u'sXML': 1, u'sTS': 11, u'sL': 'fr'}
DEBUG:subliminal.providers.podnapisi:No subtitles found
INFO:subliminal.api:Listing subtitles with provider 'tvsubtitles' and languages set([<Language [fr]>])
INFO:subliminal.api:Initializing provider tvsubtitles
ERROR:subliminal.providers.tvsubtitles:No show id found for u'Greys Anatomy' ({u'year': None})
INFO:subliminal.subtitle:Computing score for matches set([u'hash', u'hearing_impaired']) and <Episode [u'Greys Anatomy', 11x19]>
DEBUG:subliminal.subtitle:Final matches: set([u'hash', u'hearing_impaired'])
INFO:subliminal.subtitle:Computed score 138
INFO:subliminal.subtitle:Computing score for matches set([u'season', u'episode', u'hash', u'hearing_impaired', u'year']) and <Episode [u'Greys Anatomy', 11x19]>
DEBUG:subliminal.subtitle:Final matches: set([u'hash', u'hearing_impaired'])
INFO:subliminal.subtitle:Computed score 138
INFO:subliminal.subtitle:Computing score for matches set([u'episode', u'year', u'season', u'hash', u'hearing_impaired']) and <Episode [u'Greys Anatomy', 11x19]>
DEBUG:subliminal.subtitle:Final matches: set([u'hash', u'hearing_impaired'])
INFO:subliminal.subtitle:Computed score 138
INFO:subliminal.api:Downloading subtitle <TheSubDBSubtitle '5d78eb8a92f3f97813404641c67c06c8' [fr]> with score 138
INFO:subliminal.api:Downloading subtitle <TheSubDBSubtitle '5d78eb8a92f3f97813404641c67c06c8' [fr]>
INFO:subliminal.providers.thesubdb:Downloading subtitle %r
INFO:subliminal.subtitle:Guessing encoding for language fr
DEBUG:subliminal.subtitle:Trying encodings [u'utf-8', u'latin-1']
INFO:subliminal.subtitle:Guessed encoding utf-8
INFO:subliminal.subtitle:Guessing encoding for language fr
DEBUG:subliminal.subtitle:Trying encodings [u'utf-8', u'latin-1']
INFO:subliminal.subtitle:Guessed encoding utf-8
DEBUG:subliminal.api:All languages downloaded
Downloading subtitles  [####################################]  100%
DEBUG:subliminal.api:Terminating initialized providers
INFO:subliminal.api:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
INFO:subliminal.api:Terminating provider thesubdb
INFO:subliminal.api:Terminating provider podnapisi
INFO:subliminal.api:Terminating provider addic7ed
INFO:subliminal.providers.addic7ed:Logging out
DEBUG:subliminal.providers.addic7ed:Logged out
INFO:subliminal.api:Terminating provider tvsubtitles
INFO:subliminal.api:Saving <TheSubDBSubtitle '5d78eb8a92f3f97813404641c67c06c8' [fr]> to u'/dlna/shows/en/Greys Anatomy/S11/greys.anatomy.1119.hdtv-lol.srt'
1 subtitle downloaded for greys.anatomy.1119.hdtv-lol.mp4
```

I guess it's because they find a match with the hash ?

**Comment by Diaoul** [comment]
Yes, that's the reason.

**Comment by pannal** [comment]
I've hot-patched a similar issue in Sub-Zero by normalizing punctuation in series names (e.g. Mr. Namehere was never found as a show ID on addic7ed and tvsubtitles): https://github.com/pannal/Sub-Zero/blob/master/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_providers/mixins.py

I guess extending this with single quote support would help.

**Comment by Diaoul** [comment]
This has nothing to do with punctuation here as the information passed to subliminal has no quotes (guessit extracted the series name from title without quotes).

This search yields no suggestion: http://www.addic7ed.com/search.php?search=greys+anatomy&Submit=Search and that's perfectly normal.

There is no way for subliminal to know `greys anatomy` is in fact `grey's anatomy` unless using a webservice.

**Comment by Diaoul** [comment]
This is implemented with refiners
