### ISSUE TITLE
TypeError: %d format: a number is required, not tuple

### ISSUE THREAD

**Issue by fernandog** [Diaoul/subliminal#543]
running cli: `subliminal --debug download "/data/Media/TV Shows/Homeland/S04/Homeland.S04E03.720p.HDTV.x264-DIMENSION.mkv" --min-score 100 --provider opensubtitles -l 'de'`

Also not downloading subs in SickRageeven score > score_min
From SickRage:
`DEBUG    FINDSUBTITLES :: [opensubtitles] Subtitle score for 1954636740 is: 115 (min=111)`

```
INFO:subliminal.video:Scanning video u'Homeland.S04E03.720p.HDTV.x264-DIMENSION.mkv' in u'/data/Media/TV Shows/Homeland/S04'
DEBUG:subliminal.video:Size is 1053495466
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'0278fb95cbfa51d7', u'thesubdb': '2fe57c4bcb568b68e285ba4d70e8c84d'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found resolution 720p with enzyme
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:MKV has no subtitle track
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Homeland.S04E03.720p.HDTV.x264-DIMENSION.mkvINFO:subliminal.api:Listing subtitles with provider 'opensubtitles' and languages set([<Language [de]>])
INFO:subliminal.api:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'eldt8fcb0ubp1irmlk0rftis85'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{u'moviebytesize': '1053495466', u'sublanguageid': u'ger', u'moviehash': u'0278fb95cbfa51d7'}, {u'query': u'Homeland', u'sublanguageid': u'ger', u'episode': 3, u'season': 4}]
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1954636740' [de]>
INFO:subliminal.subtitle:Computing score for matches set([u'episode', u'series', u'year', u'season', u'resolution', u'hearing_impaired']) and <Episode [u'Homeland', 4x3]>
DEBUG:subliminal.subtitle:Final matches: set([u'episode', u'hearing_impaired', u'year', u'series', u'resolution', u'season'])
INFO:subliminal.subtitle:Computed score 115
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not tuple
Logged from file api.py, line 192
Downloading subtitles  [####################################]  100%
DEBUG:subliminal.api:Terminating initialized providers
INFO:subliminal.api:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
Downloaded 0 subtitle
```

**Comment by Diaoul** [comment]
Seems to be from https://github.com/Diaoul/subliminal/blob/develop/subliminal/api.py#L191 but I cannot see where this comes from and I cannot reproduce with develop branch.

```
subliminal --debug download "/data/Media/TV Shows/Homeland/S04/Homeland.S04E03.720p.HDTV.x264-DIMENSION.mkv" --min-score 100 --provider opensubtitles -l 'de'
Collecting videos  [####################################]  100%  /data/Media/TV Shows/Homeland/S04/Homeland.S04E03.720p.HDTV.x264-DIMENSION.mkvDEBUG:subliminal.cli:Collecting path /data/Media/TV Shows/Homeland/S04/Homeland.S04E03.720p.HDTV.x264-DIMENSION.mkv
Collecting videos  [####################################]  100%                                                                                
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Homeland.S04E03.720p.HDTV.x264-DIMENSION.mkvINFO:subliminal.api:Listing subtitles with provider 'opensubtitles' and languages set([<Language [de]>])
INFO:subliminal.api:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'piug3nic964sgom4gdels15db1'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{'query': u'Homeland', 'sublanguageid': u'ger', 'episode': 3, 'season': 4}]
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1954636740' [de]>
INFO:subliminal.subtitle:Computing score for matches set(['episode', 'series', 'year', 'season', 'resolution', 'hearing_impaired']) and <Episode [u'Homeland', 4x3]>
DEBUG:subliminal.subtitle:Final matches: set(['episode', 'hearing_impaired', 'year', 'series', 'resolution', 'season'])
INFO:subliminal.subtitle:Computed score 115
INFO:subliminal.api:Score 115 is below min_score (137)
Downloading subtitles  [####################################]  100%                                              
DEBUG:subliminal.api:Terminating initialized providers
INFO:subliminal.api:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
Downloaded 0 subtitle
```

**Comment by fernandog** [comment]
Ok. Thanks!

@medariox
