### ISSUE TITLE
ProviderPool() doesn't support registered providers?

### ISSUE THREAD

**Issue by medariox** [Diaoul/subliminal#552]
manager = ProviderManager()
manager.register('legendastv = subliminal.providers.legendastv:LegendasTvProvider')

pool = ProviderPool(providers=manager.names(), provider_configs=provider_configs)
pool.list_subtitles(video, languages)

```
AAKeyError: 'legendastv'
AA    return self._extensions_by_name[name]
AA  File "/home/******/.sickrage/lib/stevedore/extension.py", line 284, in __getitem__
AA    if not provider_manager[name].plugin.check(video):
AA  File "/home/******/.sickrage/lib/subliminal/api.py", line 186, in list_subtitles
AA    subtitles_list = pool.list_subtitles(video, languages)
AA  File "/home/******/.sickrage/sickbeard/subtitles.py", line 169, in download_subtitles
AATraceback (most recent call last):
AA [b965cc8]
```

Is this expected?

Thank you

**Comment by Diaoul** [comment]
Yes, the `ProviderPool` uses the `provider_manager` instance. You don't need to run another instance of `ProviderManager` just use the one provided by subliminal.

**Comment by Diaoul** [comment]
```python
from subliminal import ProviderPool, provider_manager

provider_manager.register('legendastv = subliminal.providers.legendastv:LegendasTvProvider')
pool = ProviderPool(provider_configs=provider_configs)
```
