### ISSUE TITLE
Last update Error : pkg_resources.DistributionNotFound: subliminal==1.0.1

### ISSUE THREAD

**Issue by Scendari** [Diaoul/subliminal#554]
Hello, 

After updating to last version :  
 sudo pip install -U subliminal

I try to launch sublimal and get these errors : 
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: subliminal==1.0.1

Any fix or something I can do ? 

I try to uninstall : 
 sudo pip uninstall subliminal
and re-install, but I get the same errors.

**Comment by Scendari** [comment]
Ok I managed to get it to work : 

sudo pip uninstall subliminal
easy_install --upgrade pip
sudo pip install -U subliminal

:D

**Comment by Diaoul** [comment]
Hmm ok, I didn't know an outdated pip could cause such an issue. Thanks for sharing.
