### ISSUE TITLE
Last resort

### ISSUE THREAD

**Issue by CrisBRM** [Diaoul/subliminal#555]
Can't seem to troubleshoot this anymore. OS is gentoo. This was working 3 days ago, before I reinstalled the system. All dependencies are satisfied, but I get this whenever I try to fetch subtitles:

```
λ space scripts → subliminal download -l en ~/Downloads/the.blacklist.s03e07.internal.hdtv.x264-killers.mp4
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/subliminal", line 9, in <module>
    load_entry_point('subliminal==0.7.4', 'console_scripts', 'subliminal')()
  File "/usr/lib64/python2.7/site-packages/subliminal/cli.py", line 84, in subliminal
    args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
  File "/usr/lib64/python2.7/site-packages/subliminal/cli.py", line 84, in <setcomp>
    args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
  File "/usr/lib64/python2.7/site-packages/babelfish/language.py", line 112, in fromietf
    language = cls(language_subtag)
  File "/usr/lib64/python2.7/site-packages/babelfish/language.py", line 68, in __init__
    raise ValueError('%r is not a valid language' % language)
ValueError: u'/home/home/downloads/the.blacklist.s03e07.internal.hdtv.x264' is not a valid language
```

It was working 3 days ago (same file), so if anyone could help me troubleshoot this, I would really appreciate it.

**Comment by Diaoul** [comment]
Seems like you're using an old version of subliminal. Please install latest.

**Comment by CrisBRM** [comment]
You're right, when I first set this up I installed the live ebuild, and not the super outdated one. Oops.

Thanks!
