### ISSUE TITLE
ERROR:subliminal.api:Unexpected error in provider 'opensubtitles', discarding it

### ISSUE THREAD

**Issue by cioflica** [Diaoul/subliminal#559]
Hi,

This error has just started to appear. Is there a way to work around it?

ERROR:subliminal.api:Unexpected error in provider 'opensubtitles', discarding it
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/subliminal/api.py", line 116, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/usr/local/lib/python2.7/site-packages/subliminal/api.py", line 61, in __getitem__
    provider.initialize()
  File "/usr/local/lib/python2.7/site-packages/subliminal/providers/opensubtitles.py", line 109, in initialize
    'subliminal v%s' % get_version(__version__)))
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/local/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/local/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/local/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/local/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/local/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

**Comment by Diaoul** [comment]
It's most likely a misconfiguration of your environment or a temporary failure of OpenSubtitles. If you can access https://api.opensubtitles.org/xml-rpc without SSL warning you should be able to use subliminal without issue.
