### ISSUE TITLE
Podnapisi stopped working

### ISSUE THREAD

**Issue by kakai248** [Diaoul/subliminal#565]
```
Traceback (most recent call last):
  File "/home/user/stuff/lib/python3.5/site-packages/subliminal/api.py", line 116, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/home/user/stuff/lib/python3.5/site-packages/subliminal/providers/podnapisi.py", line 157, in list_subtitles
    return [s for l in languages for s in self.query(l, video.series, season=video.season,
  File "/home/user/stuff/lib/python3.5/site-packages/subliminal/providers/podnapisi.py", line 158, in <listcomp>
    episode=video.episode, year=video.year)]
  File "/home/user/stuff/lib/python3.5/site-packages/subliminal/providers/podnapisi.py", line 105, in query
    xml = etree.fromstring(self.session.get(self.server_url + 'search/old', params=params, timeout=10).content)
  File "/usr/local/lib/python3.5/xml/etree/ElementTree.py", line 1321, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 6, column 2
```

I think this started happening a while back but only now I tried to see whats wrong. I have Subliminal 1.1.1.

**Comment by Diaoul** [comment]
I cannot reproduce this. Please provide more details: https://github.com/Diaoul/subliminal/blob/develop/CONTRIBUTING.md

**Comment by Diaoul** [comment]
Please reopen with the logs.
