### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 6: invalid start byte

### ISSUE THREAD

**Issue by medariox** [Diaoul/subliminal#570]
Hello! One user over at SickRage got the following error:

```
2016-01-31 09:37:51 INFO     POSTPROCESSER :: Error occurred when downloading subtitles for: Sealab 2021 [2000]\Season 02\Sealab 2021 - S02E03 - Swimming in Oblivion.mp4
2016-01-31 09:37:51 ERROR    POSTPROCESSER :: Traceback (most recent call last):
  File "sickrage\sickbeard\subtitles.py", line 188, in download_subtitles
    min_score=user_score, only_one=not sickbeard.SUBTITLES_MULTI)
  File "sickrage\lib\subliminal\api.py", line 267, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "sickrage\lib\subliminal\providers\opensubtitles.py", line 69, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "sickrage\lib\guessit\api.py", line 29, in guessit
    return default_api.guessit(string, options)
  File "sickrage\lib\guessit\api.py", line 80, in guessit
    match.value = match.value.decode("utf-8")
  File "python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 6: invalid start byte
 [6c0c91d]
```

And the following warning from the post processor:
```
2016-01-31 09:37:50 POSTPROCESSER :: An error occurred while getting a subtitle match for: Sealab 2021 [2000]\Season 02\Sealab 2021 - S02E03 - Swimming in Oblivion.mp4. Error: utf8 : Glups  ! Apparition d'un faux Goku  !! : error 6 : error 7 : invalid start byte [6c0c91d]
```

Apparently opensubtitles provider got more than just the requested subtitle. ```Glups  ! Apparition d'un faux Goku  !!``` is not present in the users library at all. We are trying to use unicode with subliminal, is there any problem about that? This happened with latest subliminal develop and guessit2. Thank you!

**Comment by Diaoul** [comment]
It seems it's an issue with guessit.

    guessit(self.movie_release_name, {'type': 'episode'})

Can you reproduce by manually passing the `movie_release_name` as in OpenSubtitle's result?
Also, you might want to try a newer rebulk/guessit release.

**Comment by medariox** [comment]
I personally never had this issue, maybe @labrys can reproduce it?
We've had a few other reports about this error in the past days, but we aren't up-to-date with latest subliminal develop changes in master yet. I've updated all libs (subliminal, guessit and rebulk) now and once we are on master, we'll see how it goes. Will update the issue asap, thanks for the help so far.
