### ISSUE TITLE
[Windows] Script hangs on certain show episode

### ISSUE THREAD

**Issue by DarkAllMan** [Diaoul/subliminal#589]
My script hangs everyday on with this as the last information in my log:

2016-03-01 08:04:40,105 INFO     [subliminal.api] Listing subtitles for < Episode [u'Vikings', 4x1] >
2016-03-01 08:04:40,194 INFO     [subliminal.providers] Listing subtitles with provider 'opensubtitles' and languages set([<Language [en]>])
2016-03-01 08:04:40,319 INFO     [subliminal.providers] Found 1 subtitles
2016-03-01 08:04:40,319 INFO     [subliminal.providers] Listing subtitles with provider 'thesubdb' and languages set([<Language [en]>])
2016-03-01 08:04:40,579 INFO     [subliminal.providers] Found 0 subtitles
2016-03-01 08:04:40,579 INFO     [subliminal.providers] Listing subtitles with provider 'podnapisi' and languages set([<Language [en]>])
2016-03-01 08:04:42,160 INFO     [subliminal.providers] Found 11 subtitles
2016-03-01 08:04:42,359 INFO     [subliminal.providers.addic7ed] Logged in
2016-03-01 08:04:42,359 INFO     [subliminal.providers] Listing subtitles with provider 'addic7ed' and languages set([<Language [en]>])
2016-03-01 08:04:42,734 INFO     [subliminal.providers] Found 4 subtitles
2016-03-01 08:04:42,734 INFO     [subliminal.providers] Listing subtitles with provider 'tvsubtitles' and languages set([<Language [en]>])
2016-03-01 08:04:43,634 INFO     [subliminal.providers] Found 0 subtitles
2016-03-01 08:04:43,634 INFO     [subliminal.api] Found 16 subtitles total
2016-03-01 08:04:43,654 INFO     [subliminal.subtitle] Computed score 71 with matches set([u'episode', u'season', u'series', u'video_codec', u'year', u'hash'])

Any idea what is happening here?

Sometimes something else happens:
2016-03-01 20:36:57,538 INFO     [subliminal.api] Listing subtitles for < Episode [u'Vikings', 4x1] >
2016-03-01 20:36:57,723 INFO     [subliminal.providers] Listing subtitles with provider 'opensubtitles' and languages set([<Language [en]>])
2016-03-01 20:36:57,812 INFO     [subliminal.providers] Found 1 subtitles
2016-03-01 20:36:57,812 INFO     [subliminal.providers] Listing subtitles with provider 'thesubdb' and languages set([<Language [en]>])
2016-03-01 20:36:58,078 INFO     [subliminal.providers] Found 0 subtitles
2016-03-01 20:36:58,078 INFO     [subliminal.providers] Listing subtitles with provider 'podnapisi' and languages set([<Language [en]>])
2016-03-01 20:37:30,757 INFO     [subliminal.providers] Found 11 subtitles
2016-03-01 20:37:30,858 INFO     [subliminal.providers.addic7ed] Logged in
2016-03-01 20:37:30,858 INFO     [subliminal.providers] Listing subtitles with provider 'addic7ed' and languages set([<Language [en]>])
2016-03-01 20:37:30,947 ERROR    [subliminal.providers] Unexpected error in provider 'addic7ed', discarding it
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\subliminal\providers\__init__.py", line 227, in list_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_languages)
  File "build\bdist.win-amd64\egg\subliminal\providers\addic7ed.py", line 184, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "build\bdist.win-amd64\egg\subliminal\providers\addic7ed.py", line 169, in query
    soup = self.get(link)
  File "build\bdist.win-amd64\egg\subliminal\providers\addic7ed.py", line 108, in get
    raise ProviderError('Request failed with status code %d' % r.status_code)
ProviderError: Request failed with status code 304
2016-03-01 20:37:30,947 INFO     [subliminal.providers] Listing subtitles with provider 'tvsubtitles' and languages set([<Language [en]>])
2016-03-01 20:37:31,822 INFO     [subliminal.providers] Found 0 subtitles
2016-03-01 20:37:31,822 INFO     [subliminal.api] Found 12 subtitles total
2016-03-01 20:37:31,842 INFO     [subliminal.subtitle] Computed score 71 with matches set([u'episode', u'season', u'series', u'video_codec', u'year', u'hash'])

**Comment by Diaoul** [comment]
What command do you use? It seems no language is provided.

**Comment by DarkAllMan** [comment]
``
pythonw C:\Python27\Scripts\subliminal-script.py -l en -c C:\Python27\subliminalCache\subliminal.cache.dbm -a 8w --addic7ed-username ######### --addic7ed-password ######## -v --log-file "C:\subliminallogs\tv_sd_log_%date:~3,2%_%date:~6,2%_%date:~9,4%.txt" -- "N:\TVSERIES\SD"

**Comment by DarkAllMan** [comment]
Any idea?

**Comment by Diaoul** [comment]
That's a weird way of running subliminal. Why isn't the script called `subliminal` ?

**Comment by DarkAllMan** [comment]
I've been running it from windows like this for a long time....... maybe your script evolved.... 
And as long as its running ok...... why change it...
Is there a better way to run it scheduled from windows?

**Comment by DarkAllMan** [comment]
Migrated to Ubuntu Server. Installed latest version and rolledback guessit. Al seems to be working.
