### ISSUE TITLE
TVDB refiner: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#601]
Using the latest develop version, when running:
```
subliminal.py --debug download -l pt-BR -p opensubtitles 
```

We get this output:
```
Marvels.Agents.of.S.H.I.E.L.D.S03E14.Watchdogs.1080p.WEB-DL.DD5.1.H.264-MAoS.mkv
Collecting videos  [####################################]  100%  Marvels.Agents.of.S.H.I.E.L.D.S03E14.Watchdogs.1080p.WEB-DL.DD5.1.H.264-MAoS.mkvDEBUG:subliminal.cli:Collecting path Marvels.Agents.of.S.H.I.E.L.D.S03E14.Watchdogs.1080p.WEB-DL.DD5.1.H.264-MAoS.mkv
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'Marvels Agents of S H I E L D'
ERROR:subliminal.core:Failed to refine video
Traceback (most recent call last):
  File "/home/user/workspace/git/subliminal/subliminal/core.py", line 541, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/home/user/workspace/git/subliminal/subliminal/refiners/tvdb.py", line 274, in refine
    results = search_series(video.series.lower())
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 625, in gen_value
    created_value = creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1049, in creator
    return fn(*arg, **kw)
  File "/home/user/workspace/git/subliminal/subliminal/refiners/tvdb.py", line 213, in search_series
    return sorted(tvdb_client.search_series(name), key=match)
TypeError: 'NoneType' object is not iterable
INFO:subliminal.core:Refining video with omdb
WARNING:subliminal.refiners.omdb:No result for series
```
The method `tvdb_client.search_series(...)` returns None and it causes this issue.

The above exception happens in TVDB refiner, but subliminal finishes successfully anyway.

**Comment by Diaoul** [comment]
Should be fixed with 79de8e7f93d9ba7e306eb60c0f855bd1262aed7c
Please tests, I didn't unittest that part because it's supposed to be a dumb wrapper.
