### ISSUE TITLE
TVDB refiner: ValueError: time data '' does not match format '%Y-%m-%d'

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#602]
For the latest develop version (2.0-rc1)
`subliminal --debug --legendastv user pass download -f -l pt-BR -p legendastv -m 97 The.100.S03E09.720p.HDTV.x264-AVS.mkv`

```
Collecting videos  [####################################]  100%  The.100.S03E09.720p.HDTV.x264-AVS.mkvDEBUG:subliminal.cli:Collecting path The.100.S03E09.720p.HDTV.x264-AVS.mkv
INFO:subliminal.core:Refining video with metadata
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'The 100'
DEBUG:subliminal.refiners.tvdb:Found 45 results
DEBUG:subliminal.refiners.tvdb:Found result for original series without year
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'', u'status': u'Continuing', u'added': u'2013-08-10 11:43:14', u'airsTime': u'', u'network': u'', u'rating': u'', u'overview': u'Planet Earth is stacked with amazing feats of engineering and construction, a dazzling array of machines and vehicles, an awe inspiring great outdoors and a near limitless number super skilled, super humans\r\nWhat we want to know exactly how much of all this we\u2019ve got, where it all is and what it exactly it does\u2026\r\nIn each episode we will carry out the ultimate, exhaustive stock take of that particular category (from skyscrapers to mountains, boats to special forces, railways to fire-fighters\u2026discovering exactly where every single example is located and in doing so answer those questions we have about the world that have never been answered until now.\r\nA fast paced entertaining mix of graphics, archive and location reports together will be the ultimate information countdown.', u'lastUpdated': 1385372430, u'id': 272209, u'seriesName': u'100%', u'firstAired': u'', u'addedBy': 391110, u'banner': u'graphical/272209-g.jpg', u'networkId': u'', u'genre': [u'Documentary'], u'airsDayOfWeek': u'', u'runtime': u'1', u'siteRating': 0, u'zap2itId': u'', u'imdbId': u'', u'aliases': []}
ERROR:subliminal.core:Failed to refine video
Traceback (most recent call last):
  File "/home/user/workspace/git/subliminal/subliminal/core.py", line 541, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/home/user/workspace/git/subliminal/subliminal/refiners/tvdb.py", line 306, in refine
    video.year = datetime.strptime(result['firstAired'], '%Y-%m-%d').year
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:Found 127 results
DEBUG:subliminal.refiners.omdb:Found result for original series without year
DEBUG:subliminal.refiners.omdb:Found series {u'imdbID': u'tt0314970', u'Title': u'100%', u'Type': u'series', u'Poster': u'N/A', u'Year': u'1997\u20132001'}
Collecting videos  [####################################]  100%                                       
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  The.100.S03E09.720p.HDTV.x264-AVS.mkvINFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages set([<Language [pt-BR]>])
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.providers.legendastv:Logging in
DEBUG:subliminal.providers.legendastv:Logged in
INFO:subliminal.providers.legendastv:Searching title u'100%'
ERROR:subliminal.core:Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/home/user/workspace/git/subliminal/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/user/workspace/git/subliminal/subliminal/providers/legendastv.py", line 408, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/home/user/workspace/git/subliminal/subliminal/providers/legendastv.py", line 312, in query
    titles = self.search_titles(sanitize(title))
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 625, in gen_value
    created_value = creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1049, in creator
    return fn(*arg, **kw)
  File "/home/user/workspace/git/subliminal/subliminal/providers/legendastv.py", line 203, in search_titles
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request for url: http://legendas.tv/legenda/sugestao/100%
INFO:subliminal.core:Discarding provider legendastv
Downloading subtitles  [####################################]  100%                                       
Some providers have been discarded due to unexpected errors: legendastv
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.providers.legendastv:Logging out
DEBUG:subliminal.providers.legendastv:Logged out
Downloaded 0 subtitle
```

**Comment by Diaoul** [comment]
Fixed with latest develop. Clear cache before testing.
