### ISSUE TITLE
error scanning archive

### ISSUE THREAD

**Issue by CyberMew** [Diaoul/subliminal#606]
Hi, my server is back up again and I've just pulled the latest dev branch. Not sure if it's a code issue or if unrar is not a prerequisite issue. If it's the former I think it should continue on checking and skip the rar file, and if it's the latter I think unrar(?) should be added during install

INFO:subliminal.core:Scanning archive 'NFOs.rar' in '/smallville s06'
ERROR:subliminal.core:Error scanning archive
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/subliminal/core.py", line 507, in scan_videos
    video = scan_archive(filepath)
  File "build/bdist.linux-x86_64/egg/subliminal/core.py", line 424, in scan_archive
    raise ValueError('No video in archive')
ValueError: No video in archive
INFO:subliminal.core:Scanning archive 'smallville-sixth-season_english-166318.rar' in '/smallville s06'
ERROR:subliminal.cli:Unexpected error while collecting directory path /mnt/user/TV Shows/US/Series/
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/subliminal/cli.py", line 329, in download
    scanned_videos = scan_videos(p, age=age, archives=archives)
  File "build/bdist.linux-x86_64/egg/subliminal/core.py", line 507, in scan_videos
    video = scan_archive(filepath)
  File "build/bdist.linux-x86_64/egg/subliminal/core.py", line 417, in scan_archive
    rar = RarFile(path)
  File "build/bdist.linux-x86_64/egg/rarfile.py", line 523, in __init__
    self._parse()
  File "build/bdist.linux-x86_64/egg/rarfile.py", line 778, in _parse
    self._parse_real()
  File "build/bdist.linux-x86_64/egg/rarfile.py", line 844, in _parse_real
    self._process_entry(h)
  File "build/bdist.linux-x86_64/egg/rarfile.py", line 768, in _process_entry
    cmt = self._read_comment_v3(item, self._password)
  File "build/bdist.linux-x86_64/egg/rarfile.py", line 1174, in _read_comment_v3
    inf.file_size, inf.flags, inf.CRC, psw, inf.salt)
  File "build/bdist.linux-x86_64/egg/rarfile.py", line 1848, in rar_decompress
    p = custom_popen(cmd)
  File "build/bdist.linux-x86_64/egg/rarfile.py", line 1914, in custom_popen
    raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)
RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')

**Comment by Diaoul** [comment]
You need the unrar binary for the archive scanning to work.
Unrar isn't a pip module so I cannot put that as a prerequisite.
However I need to handle the case where unrar isn't installed and exit
properly. That applies to scanning and legendastv.

**Comment by CyberMew** [comment]
Is it possible to skip archive scanning now (and hence the error I'm currently facing)?

**Comment by CyberMew** [comment]
Yea I think there needs to be a flag to skip archive scanning. For now I've installed unrar package to make it work.

P.S good news, marvels agents of shields is working :+1:

**Comment by Diaoul** [comment]
Fixed with 14707b68ca1f8ed6cdd78697c6bf6055a861ca2d
