### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '19 M' (legendastv provider)

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#621]
latest develop: 
```
commit 7c2023b4b308f78d3907e9f10b11f96289dea56c
Author: Antoine Bertin <diaoulael@gmail.com>
Date:   Fri Apr 8 21:09:06 2016 +0200
```

After the fix for #603, the following error happens:

```
subliminal --debug --legendastv user pass download -f -l pt-BR -p legendastv -m 97 "CSI.S15E18.720p.HDTV.X264.DIMENSION.mkv"
Collecting videos  [####################################]  100%  CSI.S15E18.720p.HDTV.X264.DIMENSION.mkvDEBUG:subliminal.cli:Collecting path CSI.S15E18.720p.HDTV.X264.DIMENSION.mkv
INFO:subliminal.core:Refining video with metadata
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'CSI'
DEBUG:subliminal.refiners.tvdb:Found 10 results
DEBUG:subliminal.refiners.tvdb:Found exact match on series u'CSI' (2000)
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'19', u'status': u'Ended', u'added': u'', u'airsTime': u'10:00 PM', u'network': u'CBS', u'rating': u'TV-14', u'overview': u"CSI is a crime drama in which the characters use cutting-edge forensic tools to examine the evidence to solve the case.  Rather than asking 'whodunnit' (investigating witnesses/suspects), CSI explores the 'howdunnit'.", u'lastUpdated': 1459797587, u'zap2itId': u'EP00380341', u'seriesName': u'CSI: Crime Scene Investigation', u'siteRating': 8.4, u'firstAired': u'2000-10-06', u'addedBy': None, u'networkId': u'', u'genre': [u'Crime', u'Drama'], u'airsDayOfWeek': u'Sunday', u'runtime': u'45', u'banner': u'graphical/72546-g13.jpg', u'id': 72546, u'imdbId': u'tt0247082', u'aliases': [u'CSI', u'CSI: Las Vegas']}
INFO:subliminal.refiners.tvdb:Getting series episode 15x18
DEBUG:subliminal.refiners.tvdb:Found episode {u'seriesId': 72546, u'airsAfterSeason': None, u'dvdEpisodeNumber': None, u'productionCode': u'', u'overview': u'The CSI unit faces the final showdown with the Gig Harbor killer whose motives are finally revealed. Meanwhile, Nick Stokes makes a decision that will affect the entire team moving forward.', u'airedSeasonID': None, u'thumbAdded': u'2015-04-29 09:32:58', u'episodeName': u'The End Game', u'airedSeason': 15, u'airsBeforeSeason': None, u'showUrl': u'', u'id': 5104359, u'dvdDiscid': u'', u'filename': u'episodes/72546/5104359.jpg', u'dvdSeason': None, u'writers': [u'Christopher Barbour'], u'airedEpisodeNumber': 18, u'absoluteNumber': 335, u'thumbHeight': u'225', u'imdbId': u'tt4145952', u'lastUpdated': 1435293588, u'director': u'Alec Smight', u'lastUpdatedBy': 397640, u'dvdChapter': None, u'airsBeforeEpisode': None, u'language': {u'overview': u'en', u'episodeName': u'en'}, u'thumbAuthor': 345634, u'firstAired': u'2015-02-15', u'guestStars': [u'Eric Roberts', u'Barry Bostwick', u'Mark Valley', u'Brandon P Bell', u'Kathryn McCormick', u'Marc Vann', u'Mark-Paul Gosselaar'], u'siteRating': 7.8, u'thumbWidth': u'400'}
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:No need to search
Collecting videos  [####################################]  100%                                         
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  CSI.S15E18.720p.HDTV.X264.DIMENSION.mkvINFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages set([<Language [pt-BR]>])
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.providers.legendastv:Logging in
DEBUG:subliminal.providers.legendastv:Logged in
INFO:subliminal.providers.legendastv:Searching title u'csi crime scene investigation'
ERROR:subliminal.core:Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/home/user/workspace/git/subliminal/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/user/workspace/git/subliminal/subliminal/providers/legendastv.py", line 408, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/home/user/workspace/git/subliminal/subliminal/providers/legendastv.py", line 312, in query
    titles = self.search_titles(sanitize(title))
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 625, in gen_value
    created_value = creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1049, in creator
    return fn(*arg, **kw)
  File "/home/user/workspace/git/subliminal/subliminal/providers/legendastv.py", line 216, in search_titles
    'year': int(source['dsc_data_lancamento'])}
ValueError: invalid literal for int() with base 10: '19 M'
INFO:subliminal.core:Discarding provider legendastv
Downloading subtitles  [####################################]  100%                                         
Some providers have been discarded due to unexpected errors: legendastv
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.providers.legendastv:Logging out
DEBUG:subliminal.providers.legendastv:Logged out
Downloaded 0 subtitle
```

Related PR: #615

**Comment by ratoaq2** [comment]
This was fixed by #615
