### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' (legendastv provider)

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#622]
latest develop: 
```
commit 7c2023b4b308f78d3907e9f10b11f96289dea56c
Author: Antoine Bertin <diaoulael@gmail.com>
Date:   Fri Apr 8 21:09:06 2016 +0200
```

We get the following exception when searching for this specific tv show:
```
subliminal --debug --legendastv user pass download -f -l pt-BR -p legendastv -m 97 "Pretty.Little.Liars.S06E20.720p.HDTV.X264-DIMENSION.mkv"
Collecting videos  [####################################]  100%  Pretty.Little.Liars.S06E20.720p.HDTV.X264-DIMENSION.mkvDEBUG:subliminal.cli:Collecting path Pretty.Little.Liars.S06E20.720p.HDTV.X264-DIMENSION.mkv
INFO:subliminal.core:Refining video with metadata
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'Pretty Little Liars'
DEBUG:subliminal.refiners.tvdb:Found 1 results
DEBUG:subliminal.refiners.tvdb:Found exact match on series u'Pretty Little Liars' (2010)
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'78650', u'status': u'Continuing', u'added': u'2010-03-06 06:38:39', u'airsTime': u'8:00 PM', u'network': u'Freeform', u'rating': u'TV-14', u'overview': u'Based on the Pretty Little Liars series of young adult novels by Sara Shepard, the series follows the lives of four girls \u2014 Spencer, Hanna, Aria, and Emily \u2014 whose clique falls apart after the disappearance of their queen bee, Alison. One year later, they begin receiving messages from someone using the name "A" who threatens to expose their secrets \u2014 including long-hidden ones they thought only Alison knew. The show stars Lucy Hale and Holly Marie Combs', u'lastUpdated': 1460091783, u'zap2itId': u'SH01264720', u'seriesName': u'Pretty Little Liars', u'siteRating': 8.3, u'firstAired': u'2010-06-08', u'addedBy': 6560, u'networkId': u'', u'genre': [u'Drama', u'Mystery', u'Soap', u'Thriller'], u'airsDayOfWeek': u'Tuesday', u'runtime': u'45', u'banner': u'graphical/146711-g17.jpg', u'id': 146711, u'imdbId': u'tt1578873', u'aliases': []}
INFO:subliminal.refiners.tvdb:Getting series episode 6x20
DEBUG:subliminal.refiners.tvdb:Found episode {u'seriesId': 146711, u'airsAfterSeason': None, u'dvdEpisodeNumber': 20, u'productionCode': u'', u'overview': u'With the stalker threatening to kill all of them if they don\u2019t divulge Charlotte\u2019s killer by the election, the PLLs and company, at wit\u2019s end, must boldly fight back. As Spencer and Toby work together to catch Sara Harvey, Yvonne wonders where Toby\u2019s true affections lie. Ezra finishes the last chapter of his book, finally ready to say goodbye to Nicole; Aria comforts him during this emotional time and old feelings bubble to the surface. While Caleb works intently on his plan to protect Hanna, they reflect on what could have been.\r\n\r\nMeanwhile, Alison experiences strange visions and starts to question her sanity; Emily keeps tabs on her to make sure she\u2019s okay.', u'airedSeasonID': None, u'thumbAdded': u'2016-02-25 13:02:41', u'episodeName': u'Hush Hush Sweet Liars', u'airedSeason': 6, u'airsBeforeSeason': None, u'showUrl': u'', u'id': 5330427, u'dvdDiscid': u'', u'filename': u'episodes/146711/5330427.jpg', u'dvdSeason': 6, u'writers': [u'I. Marlene King'], u'airedEpisodeNumber': 20, u'absoluteNumber': 140, u'thumbHeight': u'225', u'imdbId': u'tt4656880', u'lastUpdated': 1459024213, u'director': u'', u'lastUpdatedBy': 427771, u'dvdChapter': None, u'airsBeforeEpisode': None, u'language': {u'overview': u'en', u'episodeName': u'en'}, u'thumbAuthor': 436153, u'firstAired': u'2016-03-15', u'guestStars': [], u'siteRating': 8, u'thumbWidth': u'400'}
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:No need to search
Collecting videos  [####################################]  100%                                                         
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Pretty.Little.Liars.S06E20.720p.HDTV.X264-DIMENSION.mkvINFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages set([<Language [pt-BR]>])
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.providers.legendastv:Logging in
DEBUG:subliminal.providers.legendastv:Logged in
INFO:subliminal.providers.legendastv:Searching title u'pretty little liars'
ERROR:subliminal.core:Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/home/user/workspace/git/subliminal/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/user/workspace/git/subliminal/subliminal/providers/legendastv.py", line 408, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/home/user/workspace/git/subliminal/subliminal/providers/legendastv.py", line 312, in query
    titles = self.search_titles(sanitize(title))
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 625, in gen_value
    created_value = creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1049, in creator
    return fn(*arg, **kw)
  File "/home/user/workspace/git/subliminal/subliminal/providers/legendastv.py", line 231, in search_titles
    title['season'] = int(match.group('season'))
AttributeError: 'NoneType' object has no attribute 'group'
INFO:subliminal.core:Discarding provider legendastv
Downloading subtitles  [####################################]  100%                                                         
Some providers have been discarded due to unexpected errors: legendastv
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.providers.legendastv:Logging out
DEBUG:subliminal.providers.legendastv:Logged out
Downloaded 0 subtitle
```

This happens with any "The Walking Dead" episode as well.

Related PR: #610

**Comment by ratoaq2** [comment]
Fixed by #610
