### ISSUE TITLE
No module named 'guessit.matchtree'

### ISSUE THREAD

**Issue by JPFrancoia** [Diaoul/subliminal#630]
Hi,

I used subliminal maybe 2 weeks ago, and it worked perfectly (great tool, btw).

Today I tried to use it, but I got this exception:

```
sub The.Big.Bang.Theory.S09E19.HDTV.x264-LOL\[eztv\].mp4
Traceback (most recent call last):
  File "/usr/bin/subliminal", line 7, in <module>
    from subliminal.cli import subliminal
  File "/usr/lib/python3.5/site-packages/subliminal/__init__.py", line 10, in <module>
    from .api import (ProviderPool, check_video, provider_manager, download_best_subtitles, download_subtitles,
  File "/usr/lib/python3.5/site-packages/subliminal/api.py", line 13, in <module>
    from .subtitle import compute_score, get_subtitle_path
  File "/usr/lib/python3.5/site-packages/subliminal/subtitle.py", line 7, in <module>
    from guessit.matchtree import MatchTree
ImportError: No module named 'guessit.matchtree'
```

What is the matter ? guessit changed its imports paths ?

**Comment by JPFrancoia** [comment]
Nevermind, solved by uninstalling/reinstalling/updating guessit. Sorry for the inconvenience.
