### ISSUE TITLE
Can't process subdirs

### ISSUE THREAD

**Issue by FreshKunami** [Diaoul/subliminal#637]
Hi, I've been trying to get subliminal to download subtitles for my series folders, but here is what I am getting:

subliminal -l pt-BR -s "/home/osmc/tv shows/*" --age 1w

Traceback (most recent call last):
  File "/usr/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==0.7.4', 'console_scripts', 'subliminal')()
  File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 150, in subliminal
    videos.extend([Video.fromguess(os.path.split(p)[1], guessit.guess_file_info(p)) for p in args.paths
  File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 151, in <listcomp>
    if not os.path.exists(p)])
  File "/usr/lib/python3/dist-packages/subliminal/video.py", line 63, in fromguess
    return Episode.fromguess(name, guess)
  File "/usr/lib/python3/dist-packages/subliminal/video.py", line 106, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess

**Comment by Diaoul** [comment]
Please update to latest version and report back. You're using 0.7.4 while 1.x is out and 2.0 on its way.

**Comment by Diaoul** [comment]
Also, should you encounter any bug, make sure to follow the [contributing guidelines](https://github.com/Diaoul/subliminal/blob/master/CONTRIBUTING.md)
