### ISSUE TITLE
 babelfish.exceptions.LanguageReverseError: u're'

### ISSUE THREAD

**Issue by btrd** [Diaoul/subliminal#640]
Hi !
First thanks for your work, subliminal is very useful :smile: 
I tried to use the example script on the Readme of this repo, but I get this error :

```
Traceback (most recent call last):
  File "script_subtitles.py", line 11, in <module>
    videos = [v for v in scan_videos('/home/jean/public_html/Downloads') if v.age < timedelta(days=1)]
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 447, in scan_videos
    subtitles_dir=subtitles_dir)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 316, in scan_video
    video.subtitle_languages |= set(search_external_subtitles(path, directory=subtitles_dir).values())
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 267, in search_external_subtitles
    language = Language.fromietf(language_code)
  File "/usr/local/lib/python2.7/dist-packages/babelfish/language.py", line 124, in fromietf
    language = cls.fromalpha2(language_subtag)
  File "/usr/local/lib/python2.7/dist-packages/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/usr/local/lib/python2.7/dist-packages/babelfish/converters/__init__.py", line 165, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: u're'
```
If I understand well, babefish didn't recognise the language 're'. But I don't understand why it's an error and not just a warning.

And how can I do to see weech movie it come from ?

Thanks !

**Comment by Diaoul** [comment]
Fixed with 431f71fb646a0294d3588a5cb057a1c3fd1c77bf
