### ISSUE TITLE
2.1.0.dev: Insufficient data to process the guess

### ISSUE THREAD

**Issue by fernandog** [Diaoul/subliminal#645]
```
$ subliminal --version
subliminal, version 2.0.rc1
```

```
 subliminal --debug download -l pt-BR -p legendastv "/media/SAMSUNG/media/series/Black Sails/Season 2/Black.Sails.S02E02.X.1080p.WEB-DL.DD5.1.H.264-BS.mkv"
Collecting videos  [####################################]  100%  /media/SAMSUNG/media/series/Black Sails/Season 2/Black.Sails.S02E02.X.1080p.WEB-DL.DD5.1.H.264-BS.mkvDEBUG:subliminal.cli:Collecting path /media/SAMSUNG/media/series/Black Sails/Season 2/Black.Sails.S02E02.X.1080p.WEB-DL.DD5.1.H.264-BS.mkv
INFO:subliminal.core:Scanning video 'Black.Sails.S02E02.X.1080p.WEB-DL.DD5.1.H.264-BS.mkv' in '/media/SAMSUNG/media/series/Black Sails/Season 2'
ERROR:subliminal.cli:Unexpected error while collecting path /media/SAMSUNG/media/series/Black Sails/Season 2/Black.Sails.S02E02.X.1080p.WEB-DL.DD5.1.H.264-BS.mkv
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 350, in download
    video = scan_video(p)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 380, in scan_video
    video = Video.fromguess(path, guessit(path))
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 93, in fromguess
    return Episode.fromguess(name, guess)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 166, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
Collecting videos  [####################################]  100%               
0 video collected / 0 video ignored / 1 error
```
https://github.com/pymedusa/SickRage/issues/403

**Comment by fernandog** [comment]
```
guessit "/media/SAMSUNG/media/series/Black Sails/Season 2/Black.Sails.S02E02.X.1080p.WEB-DL.DD5.1.H.264-BS.mkv"
For: /media/SAMSUNG/media/series/Black Sails/Season 2/Black.Sails.S02E02.X.1080p.WEB-DL.DD5.1.H.264-BS.mkv
GuessIt found: {
    "title": "Black Sails",
    "season": 2,
    "screen_size": "1080p",
    "format": "WEB-DL",
    "audio_codec": "DolbyDigital",
    "audio_channels": "5.1",
    "video_codec": "h264",
    "release_group": "BS",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

**Comment by fernandog** [comment]
@Diaoul 

version 2.1.0.dev

```
'subliminal --debug download -l pt-BR -p legendastv  user pass "/downloaded/series/The.Night.Of.Part.8.INTERNAL.720p.HDTV.x264                  
DEBUG:subliminal.cli:Collecting path fernandog
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
INFO:subliminal.core:Refining video with omdb
WARNING:subliminal.refiners.omdb:No results
DEBUG:subliminal.cli:Collecting path
ERROR:subliminal.cli:Unexpected error while collecting non-existing path
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 318, in download
    video = Video.fromname(p)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 107, in fromname
    return cls.fromguess(name, guessit(name))
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 96, in fromguess
    return Movie.fromguess(name, guess)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 207, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
DEBUG:subliminal.cli:Collecting path /downloaded/series/The.Night.Of.Part.8.INTERNAL.720p.HDTV.x264-BATV[rarbg]/The.Night.Of.Part.8.INTERNAL.720p.HDTV.x264-BATV.mkv
INFO:subliminal.core:Scanning video 'The.Night.Of.Part.8.INTERNAL.720p.HDTV.x264-BATV.mkv' in '/downloaded/series/The.Night.Of.Part.8.INTERNAL.720p.HDTV.x264-BATV[rarbg]'
DEBUG:subliminal.core:Size is 1519461629
DEBUG:subliminal.core:Computed hashes {'thesubdb': 'fa1994e5337bc1edfccdb1abbaadd04a', 'opensubtitles': '3ee5896f34159641', 'shooter': '5e59596c683338e656d53e0e6b4114c7;2966307c69159e73869743ebb830a5a0;6d21e638eaaaa3e45bb52c559d0902b4;d9f685d017f1900121344a8881a5c628', 'napiprojekt': '9932268ec3e8f358305a25e7fcc07eef'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found video_codec h264
DEBUG:subliminal.refiners.metadata:Found audio_codec AC3
DEBUG:subliminal.refiners.metadata:MKV has no subtitle track
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:Found 774 results
WARNING:subliminal.refiners.omdb:No matching movie found
INFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages set([<Language [pt-BR]>])
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages set([<Language [pt-BR]>])
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
```

guessit:
```
GuessIt found: {
    "title": "The Night Of",
    "part": 8,
    "screen_size": "720p",
    "format": "HDTV",
    "video_codec": "h264",
    "release_group": "BATV[rarbg]",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "movie"
}
```

**Comment by fernandog** [comment]
@diaoul please?

**Comment by Diaoul** [comment]
`subliminal --debug download -l en The.Night.Of.Part.8.INTERNAL.720p.HDTV.x264-BATV.mkv` works for me

**Comment by Diaoul** [comment]
I'm guessing you did some tweaks because `DEBUG:subliminal.cli:Collecting path fernandog` and then `ERROR:subliminal.cli:Unexpected error while collecting non-existing path` which seems normal to me given the path you sent to subliminal was fernandog...

As for the fact that it's a show not a movie, report to guessit and wait for a fix or use some other means to collect the videos and create the Episode objects.

**Comment by fernandog** [comment]
Ok
My ltv user and password was in the logs so I removed it.
But didnt changed the subliminal code

**Comment by fernandog** [comment]
@Diaoul looks like my command to run subliminal was wrong so it was trying to scan the folder but in fact it was the user and pass from ltv.

Will open guessit issue. thanks
