### ISSUE TITLE
Error finding subtitle

### ISSUE THREAD

**Issue by CyberMew** [Diaoul/subliminal#646]
```
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  The.Flash.2014.S02E18.720p.HDTV.X264-DIMENSION.mkvINFO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages set([<Language [en]>])
INFO:subliminal.core:Initializing provider addic7ed
INFO:subliminal.providers.addic7ed:Logging in
DEBUG:subliminal.providers.addic7ed:Logged in
DEBUG:subliminal.providers.addic7ed:Getting show id with year
ERROR:subliminal.core:Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "build/bdist.linux-x86_64/egg/subliminal/providers/addic7ed.py", line 269, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "build/bdist.linux-x86_64/egg/subliminal/providers/addic7ed.py", line 224, in query
    show_id = self.get_show_id(series, year, country)
  File "build/bdist.linux-x86_64/egg/subliminal/providers/addic7ed.py", line 208, in get_show_id
    show_id = show_ids.get('%s %d' % (series_sanitized, year))
TypeError: %d format: a number is required, not unicode
INFO:subliminal.core:Discarding provider addic7ed

```
I'm using the latest dev commit

**Comment by Diaoul** [comment]
I cannot reproduce this. It would seem that `year` is some string instead of being a number however I have no idea how that could happen.

**Comment by CyberMew** [comment]
Maybe the requirement dependencies I have is different from what you are using? Could you post your pip list? I'll try to match yours and test again when I get home.

**Comment by Diaoul** [comment]
```
Babel==2.2.0
CacheControl==0.11.6
Jinja2==2.8
MarkupSafe==0.23
PyYAML==3.11
Pygments==2.0.2
Sphinx==1.3.3
alabaster==0.7.7
apipkg==1.4
appdirs==1.4.0
argparse==1.2.1
babelfish==0.5.5
beautifulsoup4==4.4.1
chardet==2.3.0
click==6.2
contextlib2==0.4.0
coverage==4.0.3
docutils==0.12
dogpile.cache==0.5.7
dogpile.core==0.4.1
enzyme==0.4.1
execnet==1.4.1
funcsigs==0.4
futures==3.0.4
guessit==2.0.4
httplib2==0.9.2
lockfile==0.12.2
lxml==3.5.0
mock==1.3.0
pbr==1.8.1
pep8==1.6.2
pluggy==0.3.1
py==1.4.31
pyflakes==1.0.0
pysrt==1.0.1
pytest==2.8.5
pytest-cache==1.0
pytest-cov==2.2.0
pytest-flakes==1.0.1
pytest-pep8==1.0.6
pytest-xdist==1.14
python-dateutil==2.4.2
pytvdbapi==0.5.0
pytz==2015.7
rarfile==2.7
rebulk==0.7.1
requests==2.9.1
six==1.10.0
snowballstemmer==1.2.1
sphinx-rtd-theme==0.1.9
sphinxcontrib-programoutput==0.8
stevedore==1.10.0
-e .
sympy==0.7.6.1
tox==2.3.1
transifex-client==0.11
urllib3==1.14
vcrpy==1.7.4
virtualenv==13.1.2
wheel==0.26.0
wrapt==1.10.6
wsgiref==0.1.2
```

**Comment by CyberMew** [comment]
My list is mostly same as yours except for these versions (where mine is all newer): stevedore is 1.12.0, pytz 2016.3, Python date util 2.5.2, pysrt 1.1.0, futures 3.0.5, click 6.4. I still get the error for some reason.. 

Edit: nvm your latest 2 commits fixed it. :) I reverted the pip versions and it still works. Cheers!
