### ISSUE TITLE
ERROR:subliminal.core:Error scanning video

### ISSUE THREAD

**Issue by izeen** [Diaoul/subliminal#673]
Having problems with many movies, not all but a lot of them, whats going wrong? Is my naming scheme bad?

Im running ubuntu 16.04 and the latest stable subliminal,

`INFO:subliminal.core:Scanning video 'Whiskey Tango Foxtrot.2016.1080p.Blu-ray.H264-DRONES.mkv' in '/media/NAS01/Movies/Whiskey Tango Foxtrot.2016.1080p.Blu-ray.H264-DRONES'

ERROR:subliminal.core:Error scanning video

Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/subliminal/core.py", line 502, in scan_videos
    video = scan_video(filepath)
  
File "/home/user/.local/lib/python2.7/site-packages/subliminal/core.py", line 380, in scan_video
    video = Video.fromguess(path, guessit(path))
 
 File "/home/user/.local/lib/python2.7/site-packages/subliminal/video.py", line 93, in fromguess
    return Episode.fromguess(name, guess)
 
 File "/home/user/.local/lib/python2.7/site-packages/subliminal/video.py", line 166, in fromguess
    raise ValueError('Insufficient data to process the guess')

ValueError: Insufficient data to process the guess
`

Im not sure when exactly it stopped working or why, any help would be appreciated.

**Comment by izeen** [comment]
i tried uninstalling it and setting it up again with virtualenv but same results:

`INFO:subliminal.core:Scanning video 'The Divergent Series Allegiant.2016.1080p.Blu-ray.H264-Obfuscated.mkv' in '/media/NAS01/Movies/The Divergent Series Allegiant.2016.1080p.Blu-ray.H264-Obfuscated'
ERROR:subliminal.core:Error scanning video
Traceback (most recent call last):
  File "/home/user/.subliminal/env/local/lib/python2.7/site-packages/subliminal/core.py", line 502, in scan_videos
    video = scan_video(filepath)
  File "/home/user/.subliminal/env/local/lib/python2.7/site-packages/subliminal/core.py", line 380, in scan_video
    video = Video.fromguess(path, guessit(path))
  File "/home/user/.subliminal/env/local/lib/python2.7/site-packages/subliminal/video.py", line 93, in fromguess
    return Episode.fromguess(name, guess)
  File "/home/user/.subliminal/env/local/lib/python2.7/site-packages/subliminal/video.py", line 166, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
`

**Comment by izeen** [comment]
Tried installing on another system running ubuntu 14.04, installing the latest subliminal with pip and setting up with virtualenv. Same result.

**Comment by Diaoul** [comment]
Report this to guessit:

```
GuessIt found: {
    "season": 1, 
    "title": "Whiskey Tango Foxtrot", 
    "year": 2016, 
    "screen_size": "1080p", 
    "format": "BluRay", 
    "video_codec": "h264", 
    "release_group": "DRONES", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
```
