### ISSUE TITLE
Subliminal doesn't support ogv

### ISSUE THREAD

**Issue by wildeyes** [Diaoul/subliminal#675]
```
~/Downloads ❯❯❯ subliminal --debug download -l en Rebelde\ Way\ -\ Episode\ 1-RebeldeWay-Episode1.ogv
Collecting videos  [####################################]  100%  Rebelde Way - Episode 1-RebeldeWay-Episode1.ogvDEBUG:subliminal.cli:Collecting path Rebelde Way - Episode 1-RebeldeWay-Episode1.ogv
ERROR:subliminal.cli:Unexpected error while collecting path Rebelde Way - Episode 1-RebeldeWay-Episode1.ogv
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/subliminal/cli.py", line 352, in download
    video = scan_video(p)
  File "/usr/local/lib/python2.7/site-packages/subliminal/core.py", line 374, in scan_video
    raise ValueError('%r is not a valid video extension' % os.path.splitext(path)[1])
ValueError: '.ogv' is not a valid video extension
Collecting videos  [####################################]  100%
0 video collected / 0 video ignored / 1 error
```

**Comment by Diaoul** [comment]
Fixed with 4268ab69edceb60e3b101152e8a5e88a98929636
