### ISSUE TITLE
'No language to search for' when downloading subtitles

### ISSUE THREAD

**Issue by DandyDev** [Diaoul/subliminal#681]
Lately, when I try to download subs with Subliminal, it doesn't download anything, even though it recognizes the videos (it can collect them) and subtitles are available at opensubtitles.org when I look manually. Using `--debug` I've discovered that it complains that there is "No language to search for". I have no idea what that means. Any help would be appreciated.

Debug log:

```
λ ~/Downloads/watch/ subliminal --debug download -l en Dark\ Matter\ -\ S02E07\ -\ She’s\ One\ of\ Them\ Now.mkv
Collecting videos  [####################################]  100%  Dark Matter - S02E07 - She’s One of Them Now.mkvDEBUG:subliminal.cli:Collecting path Dark Matter - S02E07 - She’s One of Them Now.mkv
INFO:subliminal.core:Scanning video 'Dark Matter - S02E07 - She\xe2\x80\x99s One of Them Now.mkv' in ''
DEBUG:subliminal.core:Size is 774528389
DEBUG:subliminal.core:Computed hashes {'thesubdb': '63da69afd15cbe4f90a04101cb8cdb08', 'opensubtitles': '8d3779358a60b963', 'shooter': '5e119c1e9fa708640b228b94851a65d3;fca31602c2df53b0821787dd3b454c16;da3c94a36412c01e71b06e1498e2af82;088a9f65339becb0308bdcce8311a007', 'napiprojekt': '0a1eaee62883975d4b2973e1344dc36a'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found resolution 720p
DEBUG:subliminal.refiners.metadata:Found video_codec h264
DEBUG:subliminal.refiners.metadata:Found audio_codec AC3
DEBUG:subliminal.refiners.metadata:Found embedded subtitle set([<Language [en]>])
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'Dark Matter'
DEBUG:subliminal.refiners.tvdb:Found 2 results
DEBUG:subliminal.refiners.tvdb:Found exact match on series u'Dark Matter'
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'', u'rating': u'TV-14', u'overview': u'The six-person crew of a derelict spaceship awakens from stasis in the farthest reaches of space. Their memories wiped clean, they have no recollection of who they are or how they got on board. The only clue to their identities is a cargo bay full of weaponry and a destination: a remote mining colony that is about to become a war zone. With no idea whose side they are on, they face a deadly decision. Will these amnesiacs turn their backs on history, or will their pasts catch up with them?', u'firstAired': u'2015-06-13', u'id': 292174, u'aliases': [], u'networkId': u'', u'network': u'Space', u'zap2itId': u'EP02164263', u'seriesName': u'Dark Matter', u'status': u'Continuing', u'added': u'2015-02-16 15:46:41', u'imdbId': u'tt4159076', u'lastUpdated': 1471289393, u'addedBy': 63541, u'genre': [u'Drama', u'Mystery', u'Science-Fiction'], u'banner': u'graphical/292174-g2.jpg', u'airsTime': u'10:00 PM', u'siteRatingCount': 51, u'airsDayOfWeek': u'Friday', u'runtime': u'45', u'siteRating': 8.3}
INFO:subliminal.refiners.tvdb:Getting series episode 2x7
DEBUG:subliminal.refiners.tvdb:Found episode {u'seriesId': 292174, u'airsAfterSeason': None, u'dvdEpisodeNumber': 7, u'productionCode': u'', u'overview': u'Three crew members infiltrate a highly secure facility with the help of their handler.', u'airedSeasonID': 648603, u'thumbAdded': u'2016-08-12 21:35:19', u'episodeName': u'She\u2019s One of Them Now', u'airedSeason': 2, u'airsBeforeSeason': None, u'showUrl': u'', u'id': 5443961, u'dvdDiscid': u'', u'filename': u'episodes/292174/5443961.jpg', u'dvdSeason': 2, u'writers': [u'Harley Peyton'], u'airedEpisodeNumber': 7, u'absoluteNumber': 20, u'thumbHeight': u'225', u'imdbId': u'tt5770094', u'lastUpdated': 1471083425, u'director': u'Jason Priestley', u'lastUpdatedBy': 348094, u'dvdChapter': None, u'airsBeforeEpisode': None, u'language': {u'overview': u'en', u'episodeName': u'en'}, u'thumbAuthor': 345634, u'siteRatingCount': 0, u'directors': [u'Jason Priestley'], u'firstAired': u'2016-08-12', u'guestStars': [u'David Hewlett'], u'siteRating': 0, u'thumbWidth': u'400'}
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:No need to search
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Dark Matter - S02E07 - She’s One of Them Now.mkvINFO:subliminal.core:Skipping provider 'legendastv': no language to search for
INFO:subliminal.core:Skipping provider 'shooter': no language to search for
INFO:subliminal.core:Skipping provider 'podnapisi': no language to search for
INFO:subliminal.core:Skipping provider 'tvsubtitles': no language to search for
INFO:subliminal.core:Skipping provider 'opensubtitles': no language to search for
INFO:subliminal.core:Skipping provider 'addic7ed': no language to search for
INFO:subliminal.core:Skipping provider 'subscenter': no language to search for
INFO:subliminal.core:Skipping provider 'thesubdb': no language to search for
Downloading subtitles  [####################################]  100%
DEBUG:subliminal.core:Terminating initialized providers
Downloaded 0 subtitle
```

**Comment by evandrojr** [comment]
I get a similar error:

 subliminal --debug download -l en .                                      1 ↵
Traceback (most recent call last):
  File "/usr/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==0.7.4', 'console_scripts', 'subliminal')()
  File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 85, in subliminal
    args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
  File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 85, in <setcomp>
    args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
  File "/usr/lib/python3/dist-packages/babelfish/language.py", line 126, in fromietf
    language = cls(language_subtag)
  File "/usr/lib/python3/dist-packages/babelfish/language.py", line 82, in __init__
    raise ValueError('%r is not a valid language' % language)
ValueError: '.' is not a valid language

**Comment by Diaoul** [comment]
@evandrojr : install latest version of subliminal, you're using a really old one.

`no language to search for` means that either the provider doesn't support the given language. Obviously there is an error here for some reason.
Please provide a `pip freeze` and try to upgrade subliminal and its dependencies to their latest versions.

**Comment by DandyDev** [comment]
@evandrojr your error is not similar to mine at all. Your problem stems from the fact that you're trying to give Subliminal `.` as a language, which Subliminal (or rather Babelfish) doesn't recognize as a language code, so it throws an actual error.
In my case, the language code is recognised by Subliminal, but apparently Opensubtitles doesn't understand English 😂

**Comment by evandrojr** [comment]
Dear Daan,

This command used to work in Linux mint 17 and is not working anymore in
Linux mint 18. The dot is the movie path.

Thanks for your help anyway!


*“O rio atinge seus objetivos porque aprendeu a contornar obstáculos.”
Lao-Tsé (século VI a. C.), filósofo e aforista chinês.*

Tentado fazer alguma diferença
*http://evandro.org/reagindo/* <http://evandro.org/reagindo/>
(71) 98888-0635 (Oi)
(71) 98623-0017 (Vivo)

2016-08-16 4:25 GMT-03:00 Daan Debie <notifications@github.com>:

**Comment by Diaoul** [comment]
See #683

**Comment by gwillem** [comment]
FYI this is also broken in Ubuntu LTS (16.04). Installing latest version using pip works:
```
sudo apt purge subliminal
sudo apt install python-pip
sudo pip install subliminal
```
