### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Cylae** [Diaoul/subliminal#690]
/usr/local/bin/subliminal download -l en -l fr -l es -l de -l it -l zh /home/plex/Narcos/ -v
Collecting videos  [####################################]  100%
14 videos collected / 6 videos ignored / 0 error
Downloading subtitles  [##----------------------------------]    7%  Narcos - S02E10 - Al Fin Cayó! - 720p.WEB.DL.x264.mp4
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/tvsubtitles.py", line 64, in get_matches
    for r in get_equivalent_release_groups(sanitize_release_group(video.release_group)))):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/tvsubtitles.py", line 64, in <genexpr>
    for r in get_equivalent_release_groups(sanitize_release_group(video.release_group)))):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

**Comment by Cylae** [comment]
Bump

**Comment by Diaoul** [comment]
Can you try with python3?

**Comment by Cylae** [comment]
@Diaoul There is any way to for the script to use python3 instead of python2 ?

**Comment by Cylae** [comment]
installed python3 with 
`apt-get install python3` and it works ! :)

Merci l'ami pour le support et pour ce super outil 😄

**Comment by Cylae** [comment]
Hey,

Don't know why but subliminal still using python2.7...

`apt-get install python3
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

`subliminal download -l fr /home/plex/Narcos/
Collecting videos  [####################################]  100%
15 videos collected / 0 video ignored / 0 error
Downloading subtitles  [#########---------------------------]   26%  0d 00:00:09  Narcos - S02E10 - Al Fin Cayó! -      720p.WEB.DL.x264.mp4
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/tvsubtitles.py", line 64, in get_matches
    for r in get_equivalent_release_groups(sanitize_release_group(video.release_group)))):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/tvsubtitles.py", line 64, in <genexpr>
    for r in get_equivalent_release_groups(sanitize_release_group(video.release_group)))):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)`

Any way to force Subliminal to use python3 ? I don't want to delete python2.7...

**Comment by Cylae** [comment]
Sorry for closing/reopening, the issue still here.

**Comment by Cylae** [comment]
Bump @Diaoul

**Comment by Diaoul** [comment]
What is the output of `which pip` ? My guess is that it still points to pip from python 2.7. If so, run `pip uninstall subliminal` to uninstall subliminal on python 2.7.

Then install it with python3 with `pip3 install subliminal`
