### ISSUE TITLE
Add support for Air By Date releases

### ISSUE THREAD

**Issue by duramato** [Diaoul/subliminal#692]
Currently when searching for subs for a release with air by date numbering , subliminal just errors
Like so:
```
subliminal --debug download -l en Panorama.2016.06.29.Iraq.The.Final.Judgement.720p.WEB-DL.h264-OmarMateen.mkv
Collecting videos  [####################################]  100%  Panorama.2016.06.29.Iraq.The.Final.Judgement.720p.WEB-DL.h264-OmarMateen.mkvDEBUG:subliminal.cli:Collecting path Panorama.2016.06.29.Iraq.The.Final.Judgement.720p.WEB-DL.h264-OmarMateen.mkv
INFO:subliminal.core:Scanning video 'Panorama.2016.06.29.Iraq.The.Final.Judgement.720p.WEB-DL.h264-OmarMateen.mkv' in ''
ERROR:subliminal.cli:Unexpected error while collecting path Panorama.2016.06.29.Iraq.The.Final.Judgement.720p.WEB-DL.h264-OmarMateen.mkv
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 352, in download
    video = scan_video(p)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 380, in scan_video
    video = Video.fromguess(path, guessit(path))
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 93, in fromguess
    return Episode.fromguess(name, guess)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 166, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
Collecting videos  [####################################]  100%
0 video collected / 0 video ignored / 1 error
```

It shoud also search for them .

**Comment by ratoaq2** [comment]
This is not that simple since the providers requires episode information. Even tvdb refiner can only search episode information with the episode number.
