### ISSUE TITLE
Subliminal stuck at file

### ISSUE THREAD

**Issue by fooper** [Diaoul/subliminal#700]
Subliminal gets stuck on a specific file, Lethal.Weapon.S01E03.720p.HDTV.X264-DIMENSION.mkv.

If I remove this file, subliminal does its trick and download subs for movies and tv-shows. If the file is present, subliminal keep running with CPU at 100%. Had it running for 12h until I canceled it.

Same problem installing subliminal with python 2.7 or 3.5.

Command with extension I use:
subliminal --addic7ed user password download /Path/TV/ /Path/Movies/ -l eng -l swe -m 75 -a 1w -v

When canceled, it throws this exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/guessit/api.py", line 102, in guessit
    matches = self.rebulk.matches(string, options)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rebulk.py", line 275, in matches
    self._execute_rules(matches, context)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rebulk.py", line 306, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rules.py", line 122, in then
    cons.then(matches, next(iterator), context)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rules.py", line 161, in then
    if match not in matches:
  File "/usr/lib/python3.5/_collections_abc.py", line 823, in __contains__
    if v == value:
  File "/usr/local/lib/python3.5/dist-packages/rebulk/match.py", line 738, in __eq__
    return self.span == other.span and self.value == other.value and self.name == other.name and \
  File "/usr/local/lib/python3.5/dist-packages/rebulk/match.py", line 569, in value
    if self._value:
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/core.py", line 211, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/providers/opensubtitles.py", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/usr/local/lib/python3.5/dist-packages/guessit/api.py", line 54, in guessit
    return default_api.guessit(string, options)
  File "/usr/local/lib/python3.5/dist-packages/guessit/api.py", line 113, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.0
string= lethal-weapon.s1e3-774763-tv3play
options={'type': 'episode'}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/guessit/api.py", line 102, in guessit
    matches = self.rebulk.matches(string, options)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rebulk.py", line 275, in matches
    self._execute_rules(matches, context)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rebulk.py", line 306, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rules.py", line 122, in then
    cons.then(matches, next(iterator), context)
  File "/usr/local/lib/python3.5/dist-packages/rebulk/rules.py", line 161, in then
    if match not in matches:
  File "/usr/lib/python3.5/_collections_abc.py", line 823, in __contains__
    if v == value:
  File "/usr/local/lib/python3.5/dist-packages/rebulk/match.py", line 738, in __eq__
    return self.span == other.span and self.value == other.value and self.name == other.name and \
  File "/usr/local/lib/python3.5/dist-packages/rebulk/match.py", line 569, in value
    if self._value:
KeyboardInterrupt

**Comment by Diaoul** [comment]
Isn't that a guessit issue? @miigotu

**Comment by miigotu** [comment]
rebulk I believe, not quite sure. I updated rebulk and guessit and subliminal and the problem seems to have gone away.

**Comment by Diaoul** [comment]
Can we close this then?

**Comment by miigotu** [comment]
I guess, as long as the OP knows to update guessit. OP wasnt SR related.

**Comment by fooper** [comment]
Problem seems gone now, good work :)
