### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 27:

### ISSUE THREAD

**Issue by screamerbg** [Diaoul/subliminal#706]
Hi,

Subliminal is crashing with Python traceback when processing file "Family Guy - S14E20 - Road to India WEBDL-720p.mp4"

```
Collecting videos  [####################################]  100%  Family Guy - S14E20 - Road to India WEBDL-720p.mp4
Traceback (most recent call last):
  File "c:\program files (x86)\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\program files (x86)\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Progra~2\Python27\scripts\subliminal.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files (x86)\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\program files (x86)\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files (x86)\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files (x86)\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\program files (x86)\python27\lib\site-packages\click\decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\program files (x86)\python27\lib\site-packages\subliminal\cli.py", line 358, in download
    video.subtitle_languages |= set(search_external_subtitles(video.name, directory=directory).values())
  File "c:\program files (x86)\python27\lib\site-packages\subliminal\core.py", line 341, in search_external_subtitles
    if not p.startswith(fileroot) or not p.endswith(SUBTITLE_EXTENSIONS):
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 27: ordinal not in range(128)
```

Command used `subliminal download -l bg -s "Family Guy - S14E20 - Road to India WEBDL-720p.mp4"`
Platform: Windows 7

I've noticed that it works normally if the file is named "Family.Guy.S14E20.WEBDL.720p.mp4"

**Comment by ratoaq2** [comment]
Is this still an issue with latest develop?

**Comment by ratoaq2** [comment]
Closing due to no reply
