### ISSUE TITLE
Subliminal is not launching, "ValueError: insecure string pickle"

### ISSUE THREAD

**Issue by rocktane** [Diaoul/subliminal#710]
When I updated to macOS Sierra, Subliminal continued to work perfectly.
But recently it is not working at all, I have this text when I execute it:

```
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    load_entry_point('subliminal==2.0.5', 'console_scripts', 'subliminal')()
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 567, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2604, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2264, in load
    return self.resolve()
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2270, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/subliminal/core.py", line 14, in <module>
    from rarfile import NotRarFile, RarCannotExec, RarFile
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/rarfile.py", line 1989, in <module>
    custom_check([UNRAR_TOOL], True)
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/rarfile.py", line 1917, in custom_check
    p = custom_popen(cmd)
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/rarfile.py", line 1908, in custom_popen
    creationflags = creationflags)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

**Comment by Diaoul** [comment]
Try to clear the cache with `subliminal cache --clear-subliminal`

**Comment by Rocktane** [comment]
Can I do it manually? Because I have the same error as I explained (subliminal is not working at all).

**Comment by Diaoul** [comment]
Actually it seems related to rarfile. Try python3.

**Comment by ale275** [comment]
I've similar problem if used in main envirionment (subliminal doesn't work also with flexget). If I create a virtualenv everything start to work smoothly

**Comment by Rocktane** [comment]
I tried with python3, the issue is the same.

**Comment by Diaoul** [comment]
The fact that it works with a virtualenv shows that it's not an issue with subliminal itself but more likely with your Python setup. I'll leave the issue open so more people can jump into this issue and provide feedback however I don't think I'll be able to "fix" this.

**Comment by Donkeyfish87** [comment]
I had the same problem. Although I didn't understand why or how, the following trick solved it for me:

- brew uninstall subliminal
- pip install subliminal

And it works again. It takes 30seconds to try, so worth a shot if you experience the same issue..

**Comment by alanorth** [comment]
Tested in a Python 3.6 virtualenv on macOS. Works.

**Comment by getzze** [comment]
There has been no response for a long time, this can be closed. Open a new issue if the problem persists.
