### ISSUE TITLE
I'm getting a bunch of errors.

### ISSUE THREAD

**Issue by DrWiebe** [Diaoul/subliminal#719]
```
Traceback (most recent call last):
  File "./instaRaider.py", line 480, in <module>
    main()
  File "./instaRaider.py", line 470, in main
    process_number=args.process_number)
  File "./instaRaider.py", line 87, in __init__
    self.setup_webdriver()
  File "./instaRaider.py", line 113, in setup_webdriver
    self.webdriver = webdriver.Firefox(self.profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x101ee0910>> ignored
Exception AttributeError: "'InstaRaider' object has no attribute 'webdriver'" in <bound method InstaRaider.__del__ of <__main__.InstaRaider object at 0x101ebbfd0>> ignored
```

**Comment by DrWiebe** [comment]
Wrong repo. Sorry
