### ISSUE TITLE
Cannot import name 'Lock'.

### ISSUE THREAD

**Issue by luigino** [Diaoul/subliminal#721]
Subliminal 2.0.5 stopped working for me, dogpile.cache seems to be the same as usual.

```
> subliminal download --single --language en --force myclip.mp4 
Traceback (most recent call last):
  File "/usr/bin/subliminal", line 11, in <module>
    load_entry_point('subliminal==2.0.5', 'console_scripts', 'subliminal-3.4')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2627, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2287, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/subliminal/__init__.py", line 13, in <module>
    from .cache import region
  File "/usr/lib/python3.4/site-packages/subliminal/cache.py", line 4, in <module>
    from dogpile.cache import make_region
  File "/usr/lib/python3.4/site-packages/dogpile/cache/__init__.py", line 1, in <module>
    from .region import CacheRegion, register_backend, make_region  # noqa
  File "/usr/lib/python3.4/site-packages/dogpile/cache/region.py", line 2, in <module>
    from .. import Lock, NeedRegenerationException
ImportError: cannot import name 'Lock'
 ```

**Comment by vishnu430** [comment]
How you resolved this error?

**Comment by luigino** [comment]
> How you resolved this error?

I think it was a conflict between dogpile.core and dogpile.cache, they can't be installed together.

**Comment by vishnu430** [comment]
Thanks dude!!! After uninstalling dogpile.core, it is working fine.

**Comment by scr4bble** [comment]
Thanks a lot !
