### ISSUE TITLE
ImportError: No module named subliminal.cli

### ISSUE THREAD

**Issue by CyberMew** [Diaoul/subliminal#723]
Recently had to reinstall subliminal again. I'm using Python 2.7.12. Installed without issues, not sure why I'm having this problem now. Any help is appreciated.
```
Traceback (most recent call last):
  File "/usr/bin/subliminal", line 11, in <module>
    load_entry_point('subliminal==2.1.0.dev0', 'console_scripts', 'subliminal')()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named subliminal.cli
```
pip list

> appdirs (1.4.0)
> babelfish (0.5.5)
> beautifulsoup4 (4.5.1)
> chardet (2.3.0)
> click (6.6)
> dogpile.cache (0.6.2)
> enzyme (0.4.1)
> futures (3.0.5)
> guessit (2.1.1)
> pbr (1.10.0)
> pip (9.0.1)
> pyOpenSSL (0.15.1)
> pysrt (1.1.1)
> python-dateutil (2.6.0)
> pytz (2016.10)
> rarfile (2.8)
> rebulk (0.8.2)
> requests (2.12.4)
> setuptools (32.3.0)
> six (1.10.0)
> stevedore (1.19.1)
> subliminal (2.1.0.dev0)
> 
If I installed via `pip install subliminal` then it installs 2.0.5 (reusing the same installed dependencies) which works fine.

**Comment by CyberMew** [comment]
Weird, I did a `pip uninstall subliminal` right after that, and reinstalled the dev branch again, runs without issue now.
```
>pip uninstall subliminal
Uninstalling subliminal-2.0.5:
  /usr/bin/subliminal
  /usr/lib64/python2.7/site-packages/subliminal-2.0.5.dist-info/DESCRIPTION.rst
  /usr/lib64/python2.7/site-packages/subliminal-2.0.5.dist-info/INSTALLER
  /usr/lib64/python2.7/site-packages/subliminal-2.0.5.dist-info/METADATA
  /usr/lib64/python2.7/site-packages/subliminal-2.0.5.dist-info/RECORD
  /usr/lib64/python2.7/site-packages/subliminal-2.0.5.dist-info/WHEEL
  /usr/lib64/python2.7/site-packages/subliminal-2.0.5.dist-info/entry_points.txt
  /usr/lib64/python2.7/site-packages/subliminal-2.0.5.dist-info/metadata.json
  /usr/lib64/python2.7/site-packages/subliminal-2.0.5.dist-info/top_level.txt
  /usr/lib64/python2.7/site-packages/subliminal/__init__.py
  /usr/lib64/python2.7/site-packages/subliminal/__init__.pyc
  /usr/lib64/python2.7/site-packages/subliminal/cache.py
  /usr/lib64/python2.7/site-packages/subliminal/cache.pyc
  /usr/lib64/python2.7/site-packages/subliminal/cli.py
  /usr/lib64/python2.7/site-packages/subliminal/cli.pyc
  /usr/lib64/python2.7/site-packages/subliminal/converters/__init__.py
  /usr/lib64/python2.7/site-packages/subliminal/converters/__init__.pyc
  /usr/lib64/python2.7/site-packages/subliminal/converters/addic7ed.py
  /usr/lib64/python2.7/site-packages/subliminal/converters/addic7ed.pyc
  /usr/lib64/python2.7/site-packages/subliminal/converters/legendastv.py
  /usr/lib64/python2.7/site-packages/subliminal/converters/legendastv.pyc
  /usr/lib64/python2.7/site-packages/subliminal/converters/shooter.py
  /usr/lib64/python2.7/site-packages/subliminal/converters/shooter.pyc
  /usr/lib64/python2.7/site-packages/subliminal/converters/thesubdb.py
  /usr/lib64/python2.7/site-packages/subliminal/converters/thesubdb.pyc
  /usr/lib64/python2.7/site-packages/subliminal/converters/tvsubtitles.py
  /usr/lib64/python2.7/site-packages/subliminal/converters/tvsubtitles.pyc
  /usr/lib64/python2.7/site-packages/subliminal/core.py
  /usr/lib64/python2.7/site-packages/subliminal/core.pyc
  /usr/lib64/python2.7/site-packages/subliminal/exceptions.py
  /usr/lib64/python2.7/site-packages/subliminal/exceptions.pyc
  /usr/lib64/python2.7/site-packages/subliminal/extensions.py
  /usr/lib64/python2.7/site-packages/subliminal/extensions.pyc
  /usr/lib64/python2.7/site-packages/subliminal/providers/__init__.py
  /usr/lib64/python2.7/site-packages/subliminal/providers/__init__.pyc
  /usr/lib64/python2.7/site-packages/subliminal/providers/addic7ed.py
  /usr/lib64/python2.7/site-packages/subliminal/providers/addic7ed.pyc
  /usr/lib64/python2.7/site-packages/subliminal/providers/legendastv.py
  /usr/lib64/python2.7/site-packages/subliminal/providers/legendastv.pyc
  /usr/lib64/python2.7/site-packages/subliminal/providers/napiprojekt.py
  /usr/lib64/python2.7/site-packages/subliminal/providers/napiprojekt.pyc
  /usr/lib64/python2.7/site-packages/subliminal/providers/opensubtitles.py
  /usr/lib64/python2.7/site-packages/subliminal/providers/opensubtitles.pyc
  /usr/lib64/python2.7/site-packages/subliminal/providers/podnapisi.py
  /usr/lib64/python2.7/site-packages/subliminal/providers/podnapisi.pyc
  /usr/lib64/python2.7/site-packages/subliminal/providers/shooter.py
  /usr/lib64/python2.7/site-packages/subliminal/providers/shooter.pyc
  /usr/lib64/python2.7/site-packages/subliminal/providers/subscenter.py
  /usr/lib64/python2.7/site-packages/subliminal/providers/subscenter.pyc
  /usr/lib64/python2.7/site-packages/subliminal/providers/thesubdb.py
  /usr/lib64/python2.7/site-packages/subliminal/providers/thesubdb.pyc
  /usr/lib64/python2.7/site-packages/subliminal/providers/tvsubtitles.py
  /usr/lib64/python2.7/site-packages/subliminal/providers/tvsubtitles.pyc
  /usr/lib64/python2.7/site-packages/subliminal/refiners/__init__.py
  /usr/lib64/python2.7/site-packages/subliminal/refiners/__init__.pyc
  /usr/lib64/python2.7/site-packages/subliminal/refiners/metadata.py
  /usr/lib64/python2.7/site-packages/subliminal/refiners/metadata.pyc
  /usr/lib64/python2.7/site-packages/subliminal/refiners/omdb.py
  /usr/lib64/python2.7/site-packages/subliminal/refiners/omdb.pyc
  /usr/lib64/python2.7/site-packages/subliminal/refiners/tvdb.py
  /usr/lib64/python2.7/site-packages/subliminal/refiners/tvdb.pyc
  /usr/lib64/python2.7/site-packages/subliminal/score.py
  /usr/lib64/python2.7/site-packages/subliminal/score.pyc
  /usr/lib64/python2.7/site-packages/subliminal/subtitle.py
  /usr/lib64/python2.7/site-packages/subliminal/subtitle.pyc
  /usr/lib64/python2.7/site-packages/subliminal/subtitles/__init__.py
  /usr/lib64/python2.7/site-packages/subliminal/subtitles/__init__.pyc
  /usr/lib64/python2.7/site-packages/subliminal/subtitles/subrip.py
  /usr/lib64/python2.7/site-packages/subliminal/utils.py
  /usr/lib64/python2.7/site-packages/subliminal/utils.pyc
  /usr/lib64/python2.7/site-packages/subliminal/video.py
  /usr/lib64/python2.7/site-packages/subliminal/video.pyc
Proceed (y/n)? y
  Successfully uninstalled subliminal-2.0.5

> python /path/to/subliminal/setup.py install
/usr/lib64/python2.7/site-packages/setuptools/dist.py:333: UserWarning: Normalizing '2.1.0.dev' to '2.1.0.dev0'
  normalized_version,
running install
running bdist_egg
running egg_info
writing requirements to subliminal.egg-info/requires.txt
writing subliminal.egg-info/PKG-INFO
writing top-level names to subliminal.egg-info/top_level.txt
writing dependency_links to subliminal.egg-info/dependency_links.txt
writing entry points to subliminal.egg-info/entry_points.txt
reading manifest file 'subliminal.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'subliminal.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/core.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/exceptions.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/cache.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/score.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/cli.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/subtitle.py -> build/bdist.linux-x86_64/egg/subliminal
creating build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/converters/addic7ed.py -> build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/converters/legendastv.py -> build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/converters/shooter.py -> build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/converters/thesubdb.py -> build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/converters/__init__.py -> build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/converters/tvsubtitles.py -> build/bdist.linux-x86_64/egg/subliminal/converters
copying build/lib/subliminal/extensions.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/__init__.py -> build/bdist.linux-x86_64/egg/subliminal
copying build/lib/subliminal/video.py -> build/bdist.linux-x86_64/egg/subliminal
creating build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/addic7ed.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/legendastv.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/subscenter.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/opensubtitles.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/shooter.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/podnapisi.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/thesubdb.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/__init__.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/tvsubtitles.py -> build/bdist.linux-x86_64/egg/subliminal/providers
copying build/lib/subliminal/providers/napiprojekt.py -> build/bdist.linux-x86_64/egg/subliminal/providers
creating build/bdist.linux-x86_64/egg/subliminal/refiners
copying build/lib/subliminal/refiners/metadata.py -> build/bdist.linux-x86_64/egg/subliminal/refiners
copying build/lib/subliminal/refiners/tvdb.py -> build/bdist.linux-x86_64/egg/subliminal/refiners
copying build/lib/subliminal/refiners/omdb.py -> build/bdist.linux-x86_64/egg/subliminal/refiners
copying build/lib/subliminal/refiners/__init__.py -> build/bdist.linux-x86_64/egg/subliminal/refiners
copying build/lib/subliminal/utils.py -> build/bdist.linux-x86_64/egg/subliminal
byte-compiling build/bdist.linux-x86_64/egg/subliminal/core.py to core.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/exceptions.py to exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/cache.py to cache.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/score.py to score.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/cli.py to cli.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/subtitle.py to subtitle.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/converters/addic7ed.py to addic7ed.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/converters/legendastv.py to legendastv.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/converters/shooter.py to shooter.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/converters/thesubdb.py to thesubdb.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/converters/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/converters/tvsubtitles.py to tvsubtitles.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/extensions.py to extensions.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/video.py to video.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/addic7ed.py to addic7ed.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/legendastv.py to legendastv.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/subscenter.py to subscenter.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/opensubtitles.py to opensubtitles.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/shooter.py to shooter.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/podnapisi.py to podnapisi.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/thesubdb.py to thesubdb.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/tvsubtitles.py to tvsubtitles.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/providers/napiprojekt.py to napiprojekt.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/refiners/metadata.py to metadata.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/refiners/tvdb.py to tvdb.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/refiners/omdb.py to omdb.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/refiners/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/subliminal/utils.py to utils.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying subliminal.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/subliminal-2.1.0.dev0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing subliminal-2.1.0.dev0-py2.7.egg
Copying subliminal-2.1.0.dev0-py2.7.egg to /usr/lib64/python2.7/site-packages
Adding subliminal 2.1.0.dev0 to easy-install.pth file
Installing subliminal script to /usr/bin

Installed /usr/lib64/python2.7/site-packages/subliminal-2.1.0.dev0-py2.7.egg
Processing dependencies for subliminal==2.1.0.dev0
Searching for futures==3.0.5
Best match: futures 3.0.5
Processing futures-3.0.5-py2.7.egg
futures 3.0.5 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/futures-3.0.5-py2.7.egg
Searching for pytz==2016.10
Best match: pytz 2016.10
Processing pytz-2016.10-py2.7.egg
pytz 2016.10 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/pytz-2016.10-py2.7.egg
Searching for rarfile==2.8
Best match: rarfile 2.8
Processing rarfile-2.8-py2.7.egg
rarfile 2.8 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/rarfile-2.8-py2.7.egg
Searching for appdirs==1.4.0
Best match: appdirs 1.4.0
Processing appdirs-1.4.0-py2.7.egg
appdirs 1.4.0 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/appdirs-1.4.0-py2.7.egg
Searching for six==1.10.0
Best match: six 1.10.0
Processing six-1.10.0-py2.7.egg
six 1.10.0 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/six-1.10.0-py2.7.egg
Searching for pysrt==1.1.1
Best match: pysrt 1.1.1
Processing pysrt-1.1.1-py2.7.egg
pysrt 1.1.1 is already the active version in easy-install.pth
Installing srt script to /usr/bin

Using /usr/lib64/python2.7/site-packages/pysrt-1.1.1-py2.7.egg
Searching for chardet==2.3.0
Best match: chardet 2.3.0
Processing chardet-2.3.0-py2.7.egg
chardet 2.3.0 is already the active version in easy-install.pth
Installing chardetect script to /usr/bin

Using /usr/lib64/python2.7/site-packages/chardet-2.3.0-py2.7.egg
Searching for stevedore==1.19.1
Best match: stevedore 1.19.1
Processing stevedore-1.19.1-py2.7.egg
stevedore 1.19.1 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/stevedore-1.19.1-py2.7.egg
Searching for dogpile.cache==0.6.2
Best match: dogpile.cache 0.6.2
Processing dogpile.cache-0.6.2-py2.7.egg
dogpile.cache 0.6.2 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/dogpile.cache-0.6.2-py2.7.egg
Searching for click==6.6
Best match: click 6.6
Processing click-6.6-py2.7.egg
click 6.6 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/click-6.6-py2.7.egg
Searching for requests==2.12.4
Best match: requests 2.12.4
Processing requests-2.12.4-py2.7.egg
requests 2.12.4 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/requests-2.12.4-py2.7.egg
Searching for beautifulsoup4==4.5.1
Best match: beautifulsoup4 4.5.1
Processing beautifulsoup4-4.5.1-py2.7.egg
beautifulsoup4 4.5.1 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/beautifulsoup4-4.5.1-py2.7.egg
Searching for enzyme==0.4.1
Best match: enzyme 0.4.1
Processing enzyme-0.4.1-py2.7.egg
enzyme 0.4.1 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/enzyme-0.4.1-py2.7.egg
Searching for babelfish==0.5.5
Best match: babelfish 0.5.5
Processing babelfish-0.5.5-py2.7.egg
babelfish 0.5.5 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/babelfish-0.5.5-py2.7.egg
Searching for guessit==2.1.1
Best match: guessit 2.1.1
Processing guessit-2.1.1-py2.7.egg
guessit 2.1.1 is already the active version in easy-install.pth
Installing guessit script to /usr/bin

Using /usr/lib64/python2.7/site-packages/guessit-2.1.1-py2.7.egg
Searching for pbr==1.10.0
Best match: pbr 1.10.0
Processing pbr-1.10.0-py2.7.egg
pbr 1.10.0 is already the active version in easy-install.pth
Installing pbr script to /usr/bin

Using /usr/lib64/python2.7/site-packages/pbr-1.10.0-py2.7.egg
Searching for python-dateutil==2.6.0
Best match: python-dateutil 2.6.0
Processing python_dateutil-2.6.0-py2.7.egg
python-dateutil 2.6.0 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/python_dateutil-2.6.0-py2.7.egg
Searching for rebulk==0.8.2
Best match: rebulk 0.8.2
Processing rebulk-0.8.2-py2.7.egg
rebulk 0.8.2 is already the active version in easy-install.pth

Using /usr/lib64/python2.7/site-packages/rebulk-0.8.2-py2.7.egg
Finished processing dependencies for subliminal==2.1.0.dev0
```

**Comment by CyberMew** [comment]
Instead of going through python manually I used pip which appears to have fixed it `pip install https://github.com/Diaoul/subliminal/archive/develop.zip`
