### ISSUE TITLE
Support WebM video extension

### ISSUE THREAD

**Issue by haarts** [Diaoul/subliminal#725]
I beg to differ. :smile: :
```
$  subliminal --debug download -l en some.webm                                                                                                       
Collecting videos  [####################################]  100%  .some.webmDEBUG:subliminal.cli:Collecting path some.webm
ERROR:subliminal.cli:Unexpected error while collecting path some.webm
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 325, in download
    video = scan_video(p, subtitles=not force, embedded_subtitles=not force, subtitles_dir=directory)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 295, in scan_video
    raise ValueError('%s is not a valid video extension' % os.path.splitext(path)[1])
ValueError: .webm is not a valid video extension
Collecting videos  [####################################]  100%                                                   
0 video collected / 0 video ignored / 1 error
```

**Comment by fernandog** [comment]
Will be in the next release. Fixed in develop
