### ISSUE TITLE
Distribution Not Found error

### ISSUE THREAD

**Issue by fjnieto15** [Diaoul/subliminal#730]
I'm using Arch Linux and after some packages update I'm getting the following error with subliminal:

`subliminal download -l en video.mkv `
```
Traceback (most recent call last):
  File "/usr/bin/subliminal", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'subliminal==2.0.5' distribution was not found and is required by the application

```

Is there any way to fix it?

**Comment by tribly** [comment]
I'm encountering the same problem.

**Comment by Diaoul** [comment]
Have you tried installing in a fresh virtualenv?

**Comment by tribly** [comment]
Ah, that was the solution! Thanks.

**Comment by fjnieto15** [comment]
Didn't know what exactly means "install in a fresh virtualenv", so I just reinstalled the whole thing using the setup.py script and it seems to work now.
Thanks!
