### ISSUE TITLE
AttributeError: 'Rebulk' object has no attribute 'chain_defaults'

### ISSUE THREAD

**Issue by S2-** [Diaoul/subliminal#735]
Just installed subliminal with `pip install subliminal`, and when I execute it I get

```
$ subliminal
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 7, in <module>
    from subliminal.cli import subliminal
  File "/usr/local/lib/python2.7/dist-packages/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 13, in <module>
    from guessit import guessit
  File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 6, in <module>
    from .api import guessit, GuessItApi
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 150, in <module>
    default_api = GuessItApi(rebulk_builder())
  File "/usr/local/lib/python2.7/dist-packages/guessit/rules/__init__.py", line 49, in rebulk_builder
    rebulk.rebulk(episodes())
  File "/usr/local/lib/python2.7/dist-packages/guessit/rules/properties/episodes.py", line 50, in episodes
    rebulk.chain_defaults(chain_breaker=episodes_season_chain_breaker)
AttributeError: 'Rebulk' object has no attribute 'chain_defaults'
```

is there something wrong with the install? or my python version?

**Comment by Diaoul** [comment]
Maybe you're using an old version of rebulk? Please try `pip install -U subliminal` so dependencies are updated along the way.

**Comment by S2-** [comment]
I swear I did pip install -U subliminal a few hundred times before opening this issue, I did it again now and it works now. Go figure...
