### ISSUE TITLE
ImportError: cannot import name integer_types on Fedora 25

### ISSUE THREAD

**Issue by grizonnetm** [Diaoul/subliminal#737]
I've installed subliminal with pip on fedora 25

All subliminal commands failed with the Python error "ImportError: cannot import name integer_types"

After some research, perhaps need to update subliminal dependencies to a recent version of six.

Regards,

**Comment by Diaoul** [comment]
Can you post the full error stack please? I'll update the requirements.

**Comment by grizonnetm** [comment]
the full error stack:

Traceback (most recent call last):
  File "/usr/bin/subliminal", line 7, in <module>
    from subliminal.cli import subliminal
  File "/usr/lib/python2.7/site-packages/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/usr/lib/python2.7/site-packages/subliminal/core.py", line 15, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from .compat import (
ImportError: cannot import name integer_types

**Comment by Diaoul** [comment]
It seems it's an issue with your requests module. Try `pip install -U requests`

**Comment by grizonnetm** [comment]
I uninstalled and reinstalled requests and it works now. It seems that I had 2 versions installed 2.10 and 2.13.

It works now with only 2.13, thanks. Sorry for the false alarm.
