### ISSUE TITLE
Change scores value of Score.py

### ISSUE THREAD

**Issue by verahert** [Diaoul/subliminal#753]
Hi, i'm trying to change the value of movie scores in file score.py:

#: Scores for movies
movie_scores = {'hash': 119, 'title': 60, 'year': 30, 'release_group': 15,
                'format': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}

The idea is to increase the format to 100 but when i save the changes and re run subliminal i get this error:

Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/score.py", line 146, in compute_score
    assert 0 <= score <= scores['hash'] + scores['hearing_impaired']
AssertionError

**Comment by pannal** [comment]
Well, the error tells you what's wrong. The maximum score has to be smaller than or equal to hash + hearing_impaired.

**Comment by Diaoul** [comment]
Either increase hash or substitude compute_score with your own function altogether.

**Comment by pannal** [comment]
@Diaoul related idea: support environment variables for most of the internals. such as score.

**Comment by Diaoul** [comment]
I don't want to bind the library to some env variables, explicit is better than implicit. For the CLI that's an insteresting idea but a configuration file would be best suited.
