### ISSUE TITLE
unorderable types

### ISSUE THREAD

**Issue by G1zm0** [Diaoul/subliminal#758]
Referencing https://github.com/Diaoul/subliminal/issues/739

I call subliminal in a docker on my synology. That part works.
I download some subtitles, but then is stops with the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 9, in <module>
   load_entry_point('subliminal', 'console_scripts', 'subliminal')()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/src/app/subliminal/cli.py", line 456, in download
    matches=', '.join(sorted(matches, key=scores.get, reverse=True))
TypeError: unorderable types: NoneType() < int()
```

I export the results to a txt file so I can do some more debugging if necessary.

**Comment by ratoaq2** [comment]
Is this still an issue? Did you try reinstalling it?

**Comment by G1zm0** [comment]
I stopped using this, I'm using Bazarr at the moment wich uses subliminal in it's core.
