### ISSUE TITLE
Error when using "subscenter" in windows

### ISSUE THREAD

**Issue by shlomiLan** [Diaoul/subliminal#806]
I have tried to use the "subscenter" provider by running this cunfigurtion:
`subtitles = download_best_subtitles(new_videos, set([Language('heb'), Language('eng')]), providers=['subscenter'])`

But I get the following error:
```
Traceback (most recent call last):
  File "d:\private\tvsort_sl\venv\lib\site-packages\subliminal\core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "d:\private\tvsort_sl\venv\lib\site-packages\subliminal\providers\subscenter.py", line 219, in list_subtitles
    return [s for s in self.query(title, season, episode) if s.language in languages]
  File "d:\private\tvsort_sl\venv\lib\site-packages\subliminal\providers\subscenter.py", line 155, in query
    url_titles = self._search_url_titles(title)
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\cache\region.py", line 1231, in decorate
    should_cache_fn)
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\cache\region.py", line 833, in get_or_create
    async_creator) as value:
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\lock.py", line 154, in __enter__
    return self._enter()
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\lock.py", line 87, in _enter
    value = value_fn()
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\cache\region.py", line 788, in get_value
    value = self.backend.get(key)
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\cache\backends\file.py", line 220, in get
    with self._dbm_file(False) as dbm:
  File "c:\python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\cache\backends\file.py", line 212, in _dbm_file
    with self._use_rw_lock(write):
  File "c:\python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\cache\backends\file.py", line 207, in _use_rw_lock
    with self._rw_lock.read():
  File "c:\python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\cache\backends\file.py", line 327, in read
    self.acquire_read_lock(True)
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\cache\backends\file.py", line 408, in acquire_read_lock
    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\util\langhelpers.py", line 66, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "d:\private\tvsort_sl\venv\lib\site-packages\dogpile\cache\backends\file.py", line 400, in _module
    import fcntl
ImportError: No module named fcntl
```

I'm using `subliminal==2.0.5`
I don't get the same error when I tried to use "opensubtitles".
What am I doing wrong?

**Comment by morpheus65535** [comment]
I got the same problem with Python 2.7 on Windows 10. Got this error message with legandastv, tvsubtitles and addic7ed. Have you found a solution?

**Comment by shlomiLan** [comment]
any news or changes?

**Comment by bablat** [comment]
fcntl doesn't exist in Windows. Apparently there is not simple drop-in solution for this library, subliminal isn't expected to work in Windows.

The quickest way to resolve this would be to run subliminal under Cygwin, it will provide the missing APIs and you can expect it to work.

Good luck!

**Comment by morpheus65535** [comment]
If it’s not suppose to work on Windows, why do we have an EXE compiled version? It’s been working for years now.

**Comment by bablat** [comment]
@morpheus65535: Well, it's a simple fact. Subliminal's libraries require fcntl to lock accessed files and as you can see it's unavailable in windows.
I'm not sure which .exe build you're referring to, as I don't see an official one on the release page. Perhaps someone already packaged subliminal with Cygwin, I'm not sure.
In any case, this is the unfortunate situation, it's a rather straightforward fix but I believe this repository has not been updated by @Diaoul in quite a while, so even if someone bothers with a pull request I'm not sure it would be merged.

Cygwin will solve your problem if you must use windows.

**Comment by shlomiLan** [comment]
I'm trying to intergrate "subliminal" to my app, not by using the CLI. Does Cygwin should help me as well? 
I have installed it and run my program but I still get the 
`ModuleNotFoundError: No module named 'fcntl'`
 error.

**Comment by bablat** [comment]
Shlomi,

I don’t think there should be a difference.
Make sure you use python compiled on Cygwin (do not run the same python interpreter from a Cygwin shell).

There are alternatives that could help if you’re writing your own app. You can try and override the fcntl call. Take a look at the suggestions over at: https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows

Good luck

**Comment by bablat** [comment]
Try this approach and override the fcntl module (no Cygwin, but make sure this module is in your PYTHONPATH:
https://stackoverflow.com/a/25471508

**Comment by shlomiLan** [comment]
I have added the following code to my app
```
# Variables with simple values

FASYNC = 64

FD_CLOEXEC = 1

F_DUPFD = 0
F_FULLFSYNC = 51
F_GETFD = 1
F_GETFL = 3
F_GETLK = 7
F_GETOWN = 5
F_RDLCK = 1
F_SETFD = 2
F_SETFL = 4
F_SETLK = 8
F_SETLKW = 9
F_SETOWN = 6
F_UNLCK = 2
F_WRLCK = 3

LOCK_EX = 2
LOCK_NB = 4
LOCK_SH = 1
LOCK_UN = 8


def fcntl(fd, op, arg=0):
    return 0


def ioctl(fd, op, arg=0, mutable_flag=True):
    if mutable_flag:
        return 0
    else:
        return ""


def flock(fd, op):
    return


def lockf(fd, operation, length=0, start=0, whence=0):
    return

```

as `fcntl.py` module.
Maybe this can be added to the library as well?

**Comment by ratoaq2** [comment]
Is this still an issue in Windows? Can someone confirm please?
