### ISSUE TITLE
AttributeError: 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by ComputingFroggy** [Diaoul/subliminal#813]
Hello,

when running subliminal on file "Suicide Squad (2016) 1080P WEB-DL Extended cut Hevc Bluury.mkv" I get the given error.

Full error trace : 
`$ subliminal download -l fr "Suicide Squad (2016) 1080P WEB-DL Extended cut Hevc Bluury.mkv" 
Collecting videos  [####################################]  100%                                                                
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Suicide Squad (2016) 1080P WEB-DL Extended cut Hevc Bluury.mkv
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/opensubtitles.py", line 98, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'movie'}))
  File "/usr/local/lib/python2.7/dist-packages/subliminal/subtitle.py", line 235, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
`

**Comment by CyberMew** [comment]
I'm also getting this error a while ago.

**Comment by Stibbons** [comment]
+1 on latest version as well

**Comment by ComputingFroggy** [comment]
it works with Deathspike patch !
Thanks to him

**Comment by fernandog** [comment]
Duplicate: https://github.com/Diaoul/subliminal/issues/761
