### ISSUE TITLE
AttributeError while downloading subtitle

### ISSUE THREAD

**Issue by jarun** [Diaoul/subliminal#827]
Hi,

I am hitting the following error while downloading subtitles:

```
$ subliminal download -l en Lost\ in\ Translation\ 2003\ 1080p\ Bluray\ x265\ 10Bit\ AAC\ 5.1\ -\ GetSchwifty.mkv 
Collecting videos  [####################################]  100%  Lost in Translation 2003 1080p BluCollecting videos  [####################################]  100%                                                                            
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Lost in Translation 2003 1080p Bluray x265 10Bit AAC 5.1 - GetSchwifty.mkv
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/core.py", line 211, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/providers/opensubtitles.py", line 98, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'movie'}))
  File "/usr/local/lib/python3.5/dist-packages/subliminal/subtitle.py", line 235, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
```

System details:

```
~$ python3 -V
Python 3.5.2
~$ uname -a
Linux tux 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
~$ subliminal --version
subliminal, version 2.0.5
```

Please let me know if you need any other information.

Awesome utility, by the way! :+1:

**Comment by trillex** [comment]
https://github.com/Diaoul/subliminal/pull/822 did the trick for me, give that a go. :)

**Comment by fernandog** [comment]
https://github.com/Diaoul/subliminal/issues/761
