### ISSUE TITLE
Download subtitles using hash check from OpenSubtitles

### ISSUE THREAD

**Issue by jarun** [Diaoul/subliminal#828]
It [seems](https://sourceforge.net/p/smplayer/bugs/728/) SMPlayer doesn't depend on the file name for downloading subtitles from OpenSubtitles.org. I was expecting the same behaviour from subliminal but noticed it doesn't find anything if the filename is changed to something like `E01.mp4`. If I add the episode name it downloads the subtitle.

Can you please support the hash match for opensubtitles?

**Comment by Diaoul** [comment]
It does already match with hash. Please provide debug logs as described [here](https://github.com/Diaoul/subliminal/blob/master/CONTRIBUTING.md).

**Comment by jarun** [comment]
Please find the details below:

```
$ sha256sum E08.\ Rixty\ Minutes.mkv 
e9ace93f7bbff070cb4709148924fb5dc506a1bf5c7e37d008d08874c8afc4bc  E08. Rixty Minutes.mkv

$ sha256sum E08.mkv 
e9ace93f7bbff070cb4709148924fb5dc506a1bf5c7e37d008d08874c8afc4bc  E08.mkv

$ subliminal --debug download -l en E08.mkv
Collecting videos  [####################################]  100%  E08.mkvDEBUG:subliminal.cli:Collecting path E08.mkv
INFO:subliminal.core:Scanning video 'E08.mkv' in ''
ERROR:subliminal.cli:Unexpected error while collecting path E08.mkv
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/subliminal/cli.py", line 352, in download
    video = scan_video(p)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/core.py", line 380, in scan_video
    video = Video.fromguess(path, guessit(path))
  File "/usr/local/lib/python3.5/dist-packages/subliminal/video.py", line 93, in fromguess
    return Episode.fromguess(name, guess)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/video.py", line 166, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
Collecting videos  [####################################]  100%         
0 video collected / 0 video ignored / 1 error

$ subliminal --debug download -l en E08.\ Rixty\ Minutes.mkv 2>&1 | tee debug_correct.log
Collecting videos
DEBUG:subliminal.cli:Collecting path E08. Rixty Minutes.mkv
INFO:subliminal.core:Scanning video 'E08. Rixty Minutes.mkv' in ''
DEBUG:subliminal.core:Size is 197689796
DEBUG:subliminal.core:Computed hashes {'thesubdb': '87231eda0c04ada906d179c71d861556', 'napiprojekt': '6370f22871f5e8d09d5bb9427b40795e', 'opensubtitles': '3a8d748cf6edf626', 'shooter': 'fb40812ba77ab6a2b4eaa6399bb5d707;f4a89182f1884c22cada2da84d18fca5;c26cc03161b16948ae2ec7b8d9b12feb;3f2c61a1ad4b57aee72dc0a20154a54a'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found resolution 1080p
DEBUG:subliminal.refiners.metadata:Found audio_codec AAC
DEBUG:subliminal.refiners.metadata:Found embedded subtitle {<Language [und]>}
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'Rixty Minutes'
WARNING:subliminal.refiners.tvdb:No results for series
INFO:subliminal.core:Refining video with omdb
ERROR:subliminal.core:Failed to refine video
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/subliminal/core.py", line 542, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/refiners/omdb.py", line 115, in refine
    results = search(video.series, 'series', video.year)
  File "/usr/local/lib/python3.5/dist-packages/dogpile/cache/region.py", line 1231, in decorate
    should_cache_fn)
  File "/usr/local/lib/python3.5/dist-packages/dogpile/cache/region.py", line 833, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python3.5/dist-packages/dogpile/lock.py", line 154, in __enter__
    return self._enter()
  File "/usr/local/lib/python3.5/dist-packages/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python3.5/dist-packages/dogpile/lock.py", line 145, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python3.5/dist-packages/dogpile/cache/region.py", line 800, in gen_value
    created_value = creator()
  File "/usr/local/lib/python3.5/dist-packages/dogpile/cache/region.py", line 1227, in creator
    return fn(*arg, **kw)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/refiners/omdb.py", line 76, in search
    results = omdb_client.search(title, type, year)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/refiners/omdb.py", line 59, in search
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://www.omdbapi.com/?r=json&v=1&s=Rixty+Minutes&page=1&type=series
1 video collected / 0 video ignored / 0 error
Downloading subtitles
INFO:subliminal.core:Listing subtitles with provider 'tvsubtitles' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider tvsubtitles
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider podnapisi
INFO:subliminal.providers.podnapisi:Searching subtitles {'sL': 'en', 'sXML': 1, 'sTE': 8, 'sK': 'Rixty Minutes', 'sTS': 1}
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
INFO:subliminal.providers.tvsubtitles:Searching show id for 'Rixty Minutes'
INFO:subliminal.core:Skipping provider 'subscenter': no language to search for
INFO:subliminal.core:Listing subtitles with provider 'shooter' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider shooter
INFO:subliminal.core:Listing subtitles with provider 'thesubdb' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider thesubdb
INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': '87231eda0c04ada906d179c71d861556'}
INFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages {<Language [en]>}
DEBUG:subliminal.providers.shooter:Searching subtitles {'filehash': 'fb40812ba77ab6a2b4eaa6399bb5d707;f4a89182f1884c22cada2da84d18fca5;c26cc03161b16948ae2ec7b8d9b12feb;3f2c61a1ad4b57aee72dc0a20154a54a', 'pathinfo': '/home/vaio/Downloads/torrents/Rick and Morty (2013-)/S01/E08. Rixty Minutes.mkv', 'lang': 'eng', 'format': 'json'}
INFO:subliminal.core:Initializing provider addic7ed
DEBUG:subliminal.providers.addic7ed:Getting show id
WARNING:subliminal.providers.addic7ed:Series not found in show ids
ERROR:subliminal.providers.tvsubtitles:No show id found for 'Rixty Minutes' ({'year': None})
INFO:subliminal.providers.addic7ed:Searching show ids with {'search': 'Rixty Minutes', 'Submit': 'Search'}
ERROR:subliminal.core:Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/providers/addic7ed.py", line 273, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/providers/addic7ed.py", line 228, in query
    show_id = self.get_show_id(series, year, country)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/providers/addic7ed.py", line 222, in get_show_id
    show_id = self._search_show_id(series)
  File "/usr/local/lib/python3.5/dist-packages/dogpile/cache/region.py", line 1231, in decorate
    should_cache_fn)
  File "/usr/local/lib/python3.5/dist-packages/dogpile/cache/region.py", line 833, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python3.5/dist-packages/dogpile/lock.py", line 154, in __enter__
    return self._enter()
  File "/usr/local/lib/python3.5/dist-packages/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python3.5/dist-packages/dogpile/lock.py", line 145, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python3.5/dist-packages/dogpile/cache/region.py", line 800, in gen_value
    created_value = creator()
  File "/usr/local/lib/python3.5/dist-packages/dogpile/cache/region.py", line 1227, in creator
    return fn(*arg, **kw)
  File "/usr/local/lib/python3.5/dist-packages/subliminal/providers/addic7ed.py", line 170, in _search_show_id
    raise TooManyRequests()
subliminal.exceptions.TooManyRequests
INFO:subliminal.providers.legendastv:Searching title 'rixty minutes'
DEBUG:subliminal.providers.shooter:No subtitles found
DEBUG:subliminal.providers.legendastv:Found 0 titles
DEBUG:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '87231eda0c04ada906d179c71d861556-en' [en]>
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'Hx-38XwedHWeVlFnNY9gHDqii40'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviehash': '3a8d748cf6edf626', 'moviebytesize': '197689796', 'sublanguageid': 'eng'}, {'sublanguageid': 'eng', 'tag': 'E08. Rixty Minutes.mkv'}, {'episode': 8, 'query': 'Rixty Minutes', 'season': 1, 'sublanguageid': 'eng'}]
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1954353688' [en]> by moviehash
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1954359713' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1954841522' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1954369758' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1954353688' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1954365520' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1954898502' [en]> by fulltext
DEBUG:subliminal.providers.podnapisi:No subtitles found
INFO:subliminal.core:Discarding provider addic7ed
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1954353688' [en]> for video <Episode ['Rixty Minutes', 1x8]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hearing_impaired': 1, 'year': 90, 'release_group': 15, 'hash': 359, 'season': 30, 'resolution': 2, 'episode': 30, 'audio_codec': 3, 'video_codec': 2, 'format': 7, 'series': 180}
DEBUG:subliminal.providers.opensubtitles:Match on hash discarded
DEBUG:subliminal.score:Found matches {'episode', 'year', 'season'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 151 with final matches {'episode', 'year', 'season', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1954359713' [en]> for video <Episode ['Rixty Minutes', 1x8]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hearing_impaired': 1, 'year': 90, 'release_group': 15, 'hash': 359, 'season': 30, 'resolution': 2, 'episode': 30, 'audio_codec': 3, 'video_codec': 2, 'format': 7, 'series': 180}
DEBUG:subliminal.score:Found matches {'episode', 'year', 'season'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 151 with final matches {'episode', 'year', 'season', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1954841522' [en]> for video <Episode ['Rixty Minutes', 1x8]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hearing_impaired': 1, 'year': 90, 'release_group': 15, 'hash': 359, 'season': 30, 'resolution': 2, 'episode': 30, 'audio_codec': 3, 'video_codec': 2, 'format': 7, 'series': 180}
DEBUG:subliminal.score:Found matches {'episode', 'year', 'season'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 151 with final matches {'episode', 'year', 'season', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1954369758' [en]> for video <Episode ['Rixty Minutes', 1x8]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hearing_impaired': 1, 'year': 90, 'release_group': 15, 'hash': 359, 'season': 30, 'resolution': 2, 'episode': 30, 'audio_codec': 3, 'video_codec': 2, 'format': 7, 'series': 180}
DEBUG:subliminal.score:Found matches {'episode', 'year', 'season'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 151 with final matches {'episode', 'year', 'season', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1954353688' [en]> for video <Episode ['Rixty Minutes', 1x8]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hearing_impaired': 1, 'year': 90, 'release_group': 15, 'hash': 359, 'season': 30, 'resolution': 2, 'episode': 30, 'audio_codec': 3, 'video_codec': 2, 'format': 7, 'series': 180}
DEBUG:subliminal.score:Found matches {'episode', 'year', 'season'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 151 with final matches {'episode', 'year', 'season', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1954365520' [en]> for video <Episode ['Rixty Minutes', 1x8]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hearing_impaired': 1, 'year': 90, 'release_group': 15, 'hash': 359, 'season': 30, 'resolution': 2, 'episode': 30, 'audio_codec': 3, 'video_codec': 2, 'format': 7, 'series': 180}
DEBUG:subliminal.score:Found matches {'episode', 'year', 'season'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 151 with final matches {'episode', 'year', 'season', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1954898502' [en]> for video <Episode ['Rixty Minutes', 1x8]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hearing_impaired': 1, 'year': 90, 'release_group': 15, 'hash': 359, 'season': 30, 'resolution': 2, 'episode': 30, 'audio_codec': 3, 'video_codec': 2, 'format': 7, 'series': 180}
DEBUG:subliminal.score:Found matches {'episode', 'year', 'season'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 151 with final matches {'episode', 'year', 'season', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <TheSubDBSubtitle '87231eda0c04ada906d179c71d861556-en' [en]> for video <Episode ['Rixty Minutes', 1x8]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hearing_impaired': 1, 'year': 90, 'release_group': 15, 'hash': 359, 'season': 30, 'resolution': 2, 'episode': 30, 'audio_codec': 3, 'video_codec': 2, 'format': 7, 'series': 180}
DEBUG:subliminal.score:Found matches {'hash'}
DEBUG:subliminal.score:Keeping only hash match
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 360 with final matches {'hash', 'hearing_impaired'}
INFO:subliminal.core:Downloading subtitle <TheSubDBSubtitle '87231eda0c04ada906d179c71d861556-en' [en]>
INFO:subliminal.providers.thesubdb:Downloading subtitle <TheSubDBSubtitle '87231eda0c04ada906d179c71d861556-en' [en]>
INFO:subliminal.subtitle:Guessing encoding for language en
DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'latin-1']
INFO:subliminal.subtitle:Guessed encoding utf-8
INFO:subliminal.subtitle:Guessing encoding for language en
DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'latin-1']
INFO:subliminal.subtitle:Guessed encoding utf-8
DEBUG:subliminal.core:All languages downloaded
Some providers have been discarded due to unexpected errors: addic7ed
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider podnapisi
INFO:subliminal.core:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
INFO:subliminal.core:Terminating provider shooter
INFO:subliminal.core:Terminating provider thesubdb
INFO:subliminal.core:Terminating provider tvsubtitles
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.core:Terminating provider addic7ed
INFO:subliminal.core:Saving <TheSubDBSubtitle '87231eda0c04ada906d179c71d861556-en' [en]> to 'E08. Rixty Minutes.en.srt'
Downloaded 1 subtitle
```

**Comment by jarun** [comment]
As I mentioned earlier, SMPlayer finds the subtitle in both the cases.

**Comment by Diaoul** [comment]
1. Subliminal doesn't even attempt to download the subtitles because there is not enough information in the video file to ensure minimal coherence of results.
2. Subliminal cannot check if the hash is a sane match `DEBUG:subliminal.providers.opensubtitles:Match on hash discarded` by cross checking with other informations: https://github.com/Diaoul/subliminal/blob/master/subliminal/providers/opensubtitles.py#L81-L85

**Comment by jarun** [comment]
I understand point 1, the name is far too short.

However, can you please explain the problem with hash match, my understanding is it should be unique for a file. If you think the cross verification is really important, why not:

- provide a override option or,
- notify the user that the subtitle is based on a hash match and may not be the correct one. If the user still agrees to download it, get it?

**Comment by Diaoul** [comment]
Opensubtitles hashes are not unique, this is why we need this extra check. You are the first to report that subliminal is too strict.
I can see two problems with your solutions:

* This issue is only related to opensubtitles and subliminal is provider agnostic, I'm not a big fan of introducing different behaviors on a provider basis. The scoring should take care of this.
* Subliminal is non interactive by design, it's not possible to "ask the user". Maybe I'll consider an interactive mode in the future but it's a lot of work.

/cc @pannal

**Comment by jarun** [comment]
> I'm not a big fan of introducing different behaviors on a provider basis

I think I was looking for a distinction between hash/non-hashed providers by the program option... not specifically opensubtitles.

**Comment by Diaoul** [comment]
Only opensubtitles hash has problems, haven't heard of issues with other hashes..

**Comment by jarun** [comment]
> Only opensubtitles hash has problems, haven't heard of issues with other hashes..

From your response my understanding is the code doesn't do *only* hash check for files whose names are too short for *any* provider, not only opensubtitles.

**Comment by jarun** [comment]
Anyway, here's a little background: I wanted to replace SMPlayer with mpv media player. The only issue blocking me was this feature. I tend to arrange the series in the S0n->E0n hierarchy without names. Many series doesn't have any names per episodes as well (e.g. House of Cards). Found subliminal dowsn't work with these.

I found a good alternative in [OpenSubtitlesDownload](https://github.com/emericg/OpenSubtitlesDownload) and hr back and it's working well for me so far.

I leave it up to your good judgment on whether you would support this feature or not. *Personally* I think it would be a good feature to have because regarding the subs SMPlayer was doing quiet well for me over the past 3 years.

**Comment by pannal** [comment]
Chiming in here.

Well, I have a pretty big sample size with Sub-Zero and over the years it's proven good to be even more strict when it comes to OpenSubtitles hash data, than subliminal itself currently is.

Those hashes can be and are being fed into the system by humans. Humans fail, thus creating wrong hash matches for subtitles on OS. I had to go as far as sanity-checking the hashes against certain portions of the media file (movie name, series, etc.), because it became such a problem for SZ users.

I've thought about explicit provider ordering; perhaps one could set a flag to prioritize hash-based providers over non-hash-based ones.

**Comment by Diaoul** [comment]
Subliminal guesses the name using the given path, you can try to feed more information to subliminal by running it from your video folder:
```
subliminal download -l en House of Cards/S03/E05.mkv
```
Also note that subliminal won't attempt to download subtitles for videos that already have some so you can run it on the whole video folder if you want.

**Comment by ptrcnull** [comment]
as with #744, can't reproduce anymore; matching subtitles by hash on `opensubtitles.org` works even with the most vague filename:
```
$ ~/dev/subliminal/subliminal.py --debug download -p opensubtitles -r hash -l en movie.mkv      
Collecting videos  [------------------------------------]    0%  movie.mkvDEBUG:subliminal.cli:Collecting path movie.mkv
INFO:subliminal.core:Scanning video 'movie.mkv' in ''
DEBUG:subliminal.core:Size is 3141729583
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with hash
DEBUG:subliminal.refiners.hash:Computing hashes for 'movie.mkv'
DEBUG:subliminal.refiners.hash:Computed hashes {'opensubtitles': 'b0352ce66d08c62f'}
INFO:subliminal.core:Refining video with hash
DEBUG:subliminal.refiners.hash:Computing hashes for 'movie.mkv'
DEBUG:subliminal.refiners.hash:Computed hashes {'opensubtitles': 'b0352ce66d08c62f'}
Collecting videos  [####################################]  100%           
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [------------------------------------]    0%  movie.mkvINFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'URr3MLZrmNTTvOrmDSTzt70ng96'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviehash': 'b0352ce66d08c62f', 'moviebytesize': '3141729583', 'sublanguageid': 'eng'}, {'tag': 'movie.mkv', 'sublanguageid': 'eng'}, {'query': 'movie', 'sublanguageid': 'eng'}]
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955298518' [en]> by moviehash
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955307575' [en]> by moviehash
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955293023' [en]> by moviehash

< snip >

DEBUG:subliminal.score:Found matches {'country'}
INFO:subliminal.score:Computed score 45 with final matches {'country'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1952304620' [en]> for video <Movie [movie]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 269, 'title': 135, 'year': 45, 'country': 45, 'release_group': 15, 'streaming_service': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'country'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 46 with final matches {'hearing_impaired', 'country'}
INFO:subliminal.core:Downloading subtitle <OpenSubtitlesSubtitle '1956395986' [en]>
INFO:subliminal.providers.opensubtitles:Downloading subtitle <OpenSubtitlesSubtitle '1956395986' [en]>
DEBUG:subliminal.core:All languages downloaded
Downloading subtitles  [####################################]  100%           
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
INFO:subliminal.core:Saving <OpenSubtitlesSubtitle '1956395986' [en]> to 'movie.en.srt'
Downloaded 1 subtitle
```
