### ISSUE TITLE
Error in tvdb refiner for multi episode files

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#872]
Error because episode can now be a list instead of number.

```
2018-01-23 20:38:21,917 ERROR Failed to refine video u'C:\\Temp\\autosubliminal\\completed\\Marvels.Agents.of.S.H.I.E.L.D.S05E01-E02.720p.HDTV.x264-AVS.mkv'
Traceback (most recent call last):
  File "c:\tools\python27\Lib\logging\handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "C:/Tools/GitHub/Auto-Subliminal\autosubliminal\logger.py", line 157, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "c:\tools\python27\Lib\logging\__init__.py", line 732, in format
    return fmt.format(record)
  File "C:/Tools/GitHub/Auto-Subliminal\autosubliminal\logger.py", line 52, in format
    return super(_LogFormatter, self).format(record)
  File "c:\tools\python27\Lib\logging\__init__.py", line 471, in format
    record.message = record.getMessage()
  File "c:\tools\python27\Lib\logging\__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not list
Logged from file tvdb.py, line 341
```

**Comment by fernandog** [comment]
Will fix that soon

**Comment by h3llrais3r** [comment]
Closed since we only have single-ep for now.
