### ISSUE TITLE
subliminal don't found existing subtitle

### ISSUE THREAD

**Issue by eephyne** [Diaoul/subliminal#878]
Hello
After changing user agent because addic7ed is blocking subliminal, I search for an episode I know for sure there is a subtitle, but It don't found anything, here the debug log 

```
/usr/bin/subliminal --debug --addic7ed eephyne ****** download -l fr /data/media/tvshow/Young\ Sheldon/Season\ 1/Young\ Sheldon\
 -\ S01E08\ -\ Cape\ Canaveral,\ Shrodinger\'s\ Cat\ and\ Cyndi\ Lauper\'s\ Hair\ HDTV-720p\ AVS.mkv -v                                                                   
Collecting videos  [####################################]  100%  /data/media/tvshow/Young Sheldon/Season 1/Young Sheldon - S01E08 - Cape Canaveral, Shrodinger's Cat and C
yndi Lauper's Hair HDTV-720p AVS.mkvDEBUG:subliminal.cli:Collecting path /data/media/tvshow/Young Sheldon/Season 1/Young Sheldon - S01E08 - Cape Canaveral, Shrodinger's C
at and Cyndi Lauper's Hair HDTV-720p AVS.mkv                                                                                                                              
INFO:subliminal.core:Scanning video "Young Sheldon - S01E08 - Cape Canaveral, Shrodinger's Cat and Cyndi Lauper's Hair HDTV-720p AVS.mkv" in '/data/media/tvshow/Young She
ldon/Season 1'                                                                                                                                                            
DEBUG:subliminal.core:Size is 481067586                                                                                                                                   
DEBUG:subliminal.core:Computed hashes {'opensubtitles': 'f8ab7bf97f97ef0f', 'shooter': '0bc198e7299974c85fb1d3b662e123ae;c0e2a4d81d6a4c3b12e497070ae082b8;12204fdbd0ac6bb5
4633576bcaebd388;8181166133e8206510a27ce8ba6c0fd4', 'thesubdb': '209bc20eef7742fd27e49a4355b77d1e', 'napiprojekt': '9953d1e4557cefddbc724d57a49a28d8'}                    
DEBUG:subliminal.core:Found subtitles {}                                                                                                                                  
INFO:subliminal.core:Refining video with metadata                                                                                                                         
DEBUG:subliminal.refiners.metadata:Found video_codec h264                                                                                                                 
DEBUG:subliminal.refiners.metadata:Found audio_codec AC3                                                                                                                  
DEBUG:subliminal.refiners.metadata:MKV has no subtitle track                                                                                                              
INFO:subliminal.core:Refining video with tvdb                                                                                                                             
INFO:subliminal.refiners.tvdb:Searching series 'Young Sheldon'                                                                                                            
DEBUG:subliminal.refiners.tvdb:Found 1 results                                                                                                                            
DEBUG:subliminal.refiners.tvdb:Found exact match on series 'Young Sheldon'                                                                                                
DEBUG:subliminal.refiners.tvdb:Found series {'id': 328724, 'seriesName': 'Young Sheldon', 'aliases': [], 'banner': 'graphical/328724-g2.jpg', 'seriesId': '203706', 'statu
s': 'Continuing', 'firstAired': '2017-09-25', 'network': 'CBS', 'networkId': '', 'runtime': '25', 'genre': ['Comedy', 'Family'], 'overview': 'The early life of child geni
us Sheldon Cooper, later seen in The Big Bang Theory (2007).', 'lastUpdated': 1516966048, 'airsDayOfWeek': 'Thursday', 'airsTime': '8:30 PM', 'rating': 'TV-PG', 'imdbId':
 'tt6226232', 'zap2itId': 'EP02642239', 'added': '2017-05-17 22:39:31', 'addedBy': 400886, 'siteRating': 8.8, 'siteRatingCount': 14}                                      
INFO:subliminal.refiners.tvdb:Getting series episode 1x8                                                                                                                  
DEBUG:subliminal.refiners.tvdb:Found episode {'id': 6353554, 'airedSeason': 1, 'airedSeasonID': 712814, 'airedEpisodeNumber': 8, 'episodeName': "Cape Canaveral, Schröding
er's Cat, and Cyndi Lauper's Hair", 'firstAired': '2017-12-14', 'guestStars': [], 'director': 'Howie Deutch', 'directors': ['Howie Deutch'], 'writers': [], 'overview': "W
hile Mary, Memaw and Missy have their girls night at the salon, the three Cooper men plan their road trip to see the space launcher, but it doesn't go as well as they pla
n.", 'language': {'episodeName': 'en', 'overview': 'en'}, 'productionCode': 'T12.15558', 'showUrl': '', 'lastUpdated': 1516966903, 'dvdDiscid': '', 'dvdSeason': 1, 'dvdEp
isodeNumber': 8, 'dvdChapter': None, 'absoluteNumber': 8, 'filename': 'episodes/328724/6353554.jpg', 'seriesId': 328724, 'lastUpdatedBy': 357436, 'airsAfterSeason': None,
 'airsBeforeSeason': None, 'airsBeforeEpisode': None, 'thumbAuthor': 468845, 'thumbAdded': '2017-12-08 04:39:45', 'thumbWidth': '400', 'thumbHeight': '225', 'imdbId': 'tt
7607908', 'siteRating': 7.3, 'siteRatingCount': 3}                                                                                                                        
INFO:subliminal.core:Refining video with omdb                                                                                                                             
DEBUG:subliminal.refiners.omdb:No need to search
Collecting videos  [####################################]  100%

1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Young Sheldon - S01E08 - Cape Canaveral, Shrodinger's Cat and Cyndi Lauper's Hair HDTV-720p AVS.mkvIN
FO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages {<Language [fr]>}
INFO:subliminal.core:Initializing provider addic7ed
INFO:subliminal.providers.addic7ed:Logging in
INFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages {<Language [fr]>}
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [fr]>}
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages {<Language [fr]>}
INFO:subliminal.providers.opensubtitles:Logging in
INFO:subliminal.core:Skipping provider 'shooter': no language to search for
INFO:subliminal.core:Initializing provider podnapisi                                                                                                                      
INFO:subliminal.core:Listing subtitles with provider 'thesubdb' and languages {<Language [fr]>}                                                                           
INFO:subliminal.providers.podnapisi:Searching subtitles {'sXML': 1, 'sL': 'fr', 'sK': 'Young Sheldon', 'sTS': 1, 'sTE': 8, 'sY': 2017}                                    
ERROR:subliminal.core:Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/subliminal/providers/legendastv.py", line 173, in __init__
    rarfile.custom_check(rarfile.UNRAR_TOOL)
  File "/usr/lib/python3.6/site-packages/rarfile.py", line 2826, in custom_check
    raise RarExecError("Check-run failed")
rarfile.RarExecError: Check-run failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/lib/python3.6/site-packages/subliminal/core.py", line 71, in __getitem__
    provider = provider_manager[name].plugin(**self.provider_configs.get(name, {}))
  File "/usr/lib/python3.6/site-packages/subliminal/providers/legendastv.py", line 175, in __init__
    raise ConfigurationError('UNRAR tool not available')
subliminal.exceptions.ConfigurationError: UNRAR tool not available
INFO:subliminal.core:Listing subtitles with provider 'tvsubtitles' and languages {<Language [fr]>}
INFO:subliminal.core:Initializing provider thesubdb
INFO:subliminal.core:Initializing provider tvsubtitles
INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': '209bc20eef7742fd27e49a4355b77d1e'}
INFO:subliminal.providers.tvsubtitles:Getting the page for episode 68773
DEBUG:subliminal.providers.addic7ed:Logged in
DEBUG:subliminal.providers.addic7ed:Getting show id with year
DEBUG:subliminal.providers.addic7ed:Getting show id
INFO:subliminal.providers.addic7ed:Getting the page of show id 6406, season 1
DEBUG:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '209bc20eef7742fd27e49a4355b77d1e-en' [en]>
DEBUG:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '209bc20eef7742fd27e49a4355b77d1e-pt-BR' [pt-BR]>
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'Kmr2jpfN1ztaudgEazgugCYyoT6'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviehash': 'f8ab7bf97f97ef0f', 'moviebytesize': '481067586', 'sublanguageid': 'fre'}, {'imdbid': '7607908'
, 'season': 1, 'episode': 8, 'sublanguageid': 'fre'}, {'tag': "Young Sheldon - S01E08 - Cape Canaveral, Shrodinger's Cat and Cyndi Lauper's Hair HDTV-720p AVS.mkv", 'subl
anguageid': 'fre'}, {'query': 'Young Sheldon', 'season': 1, 'episode': 8, 'sublanguageid': 'fre'}]
DEBUG:subliminal.providers.podnapisi:No subtitles found
DEBUG:subliminal.providers.opensubtitles:No subtitles found
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/127672/0' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/127672/1' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/127672/6' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/127672/7' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/128970/0' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/128970/1' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/128970/5' [en]>
INFO:subliminal.core:Initializing provider podnapisi                                                                                                                      
INFO:subliminal.core:Listing subtitles with provider 'thesubdb' and languages {<Language [fr]>}                                                                           
INFO:subliminal.providers.podnapisi:Searching subtitles {'sXML': 1, 'sL': 'fr', 'sK': 'Young Sheldon', 'sTS': 1, 'sTE': 8, 'sY': 2017}                                    
ERROR:subliminal.core:Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/subliminal/providers/legendastv.py", line 173, in __init__
    rarfile.custom_check(rarfile.UNRAR_TOOL)
  File "/usr/lib/python3.6/site-packages/rarfile.py", line 2826, in custom_check
    raise RarExecError("Check-run failed")
rarfile.RarExecError: Check-run failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/lib/python3.6/site-packages/subliminal/core.py", line 71, in __getitem__
    provider = provider_manager[name].plugin(**self.provider_configs.get(name, {}))
  File "/usr/lib/python3.6/site-packages/subliminal/providers/legendastv.py", line 175, in __init__
    raise ConfigurationError('UNRAR tool not available')
subliminal.exceptions.ConfigurationError: UNRAR tool not available
INFO:subliminal.core:Listing subtitles with provider 'tvsubtitles' and languages {<Language [fr]>}
INFO:subliminal.core:Initializing provider thesubdb
INFO:subliminal.core:Initializing provider tvsubtitles
INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': '209bc20eef7742fd27e49a4355b77d1e'}
INFO:subliminal.providers.tvsubtitles:Getting the page for episode 68773
DEBUG:subliminal.providers.addic7ed:Logged in
DEBUG:subliminal.providers.addic7ed:Getting show id with year
DEBUG:subliminal.providers.addic7ed:Getting show id
INFO:subliminal.providers.addic7ed:Getting the page of show id 6406, season 1
DEBUG:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '209bc20eef7742fd27e49a4355b77d1e-en' [en]>
DEBUG:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle '209bc20eef7742fd27e49a4355b77d1e-pt-BR' [pt-BR]>
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'Kmr2jpfN1ztaudgEazgugCYyoT6'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviehash': 'f8ab7bf97f97ef0f', 'moviebytesize': '481067586', 'sublanguageid': 'fre'}, {'imdbid': '7607908'
, 'season': 1, 'episode': 8, 'sublanguageid': 'fre'}, {'tag': "Young Sheldon - S01E08 - Cape Canaveral, Shrodinger's Cat and Cyndi Lauper's Hair HDTV-720p AVS.mkv", 'subl
anguageid': 'fre'}, {'query': 'Young Sheldon', 'season': 1, 'episode': 8, 'sublanguageid': 'fre'}]
DEBUG:subliminal.providers.podnapisi:No subtitles found
DEBUG:subliminal.providers.opensubtitles:No subtitles found
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/127672/0' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/127672/1' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/127672/6' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/127672/7' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/128970/0' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/128970/1' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/128970/5' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/131392/0' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/131392/1' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/131392/6' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/131392/7' [en]>
INFO:subliminal.core:Discarding provider legendastv
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '332807' [en]>
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '332832' [ro]>
Downloading subtitles  [####################################]  100%
Some providers have been discarded due to unexpected errors: legendastv
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider podnapisi
INFO:subliminal.core:Terminating provider thesubdb
INFO:subliminal.core:Terminating provider tvsubtitles
INFO:subliminal.core:Terminating provider addic7ed
INFO:subliminal.providers.addic7ed:Logging out
DEBUG:subliminal.providers.addic7ed:Logged out
INFO:subliminal.core:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
0 subtitle downloaded for Young Sheldon - S01E08 - Cape Canaveral, Shrodinger's Cat and Cyndi Lauper's Hair HDTV-720p AVS.mkv

```
youn can see here http://www.addic7ed.com/serie/Young%20Sheldon/1/8/0
there are french version of AVS.
Maybe I'm doing something wrong, but I don't know how to debug it further.

**Comment by eephyne** [comment]
nevermind I found out why… (feel stupid right now)

In case that could be useful to someone else, when you logged in in addic7ed, it take you filter preference (in the addic7ed settings page), by default its english… put all or your language and you're good to go
