### ISSUE TITLE
AttributeError: 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Asher256** [Diaoul/subliminal#880]
Hi,

subliminal version: 2.0.5

I got this error when I tried to download the french subtitle of a video:
```
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/python3-venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/python3-venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/python3-venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/python3-venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/python3-venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/python3-venv/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/python3-venv/lib/python3.5/site-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/python3-venv/lib/python3.5/site-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/python3-venv/lib/python3.5/site-packages/subliminal/core.py", line 211, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/python3-venv/lib/python3.5/site-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/python3-venv/lib/python3.5/site-packages/subliminal/providers/podnapisi.py", line 76, in get_matches
    matches |= guess_matches(video, guessit(release, {'type': 'movie'}))
  File "/python3-venv/lib/python3.5/site-packages/subliminal/subtitle.py", line 235, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
```

guess['format'] cannot call ".lower()" because it contains a list:
```
['WEB-DL', 'HDTV']
```

Thanks.

Regards,
Asher256

**Comment by fernandog** [comment]
https://github.com/Diaoul/subliminal/issues/761
