### ISSUE TITLE
Error in omdb refiner with non ascii characters

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#887]
When scanning a file with name `Un conte de Noël (2008).mkv`, the omdb refiner seems to fail on non ascii characters. It seems to be a problem with dogpile cache.

```
2018-02-17 23:39:12,530 INFO     [SubChecker :: subliminal.core] Refining video with omdb
2018-02-17 23:39:12,532 ERROR    [SubChecker :: subliminal.core] Failed to refine video u'\\\\LAPTOP\\completed\\Un conte de No\xebl (2008).mkv'
2018-02-17 23:39:12,532 DEBUG    [SubChecker :: subliminal.core] Refiner exception:
Traceback (most recent call last):
  File "C:\Tools\GitHub\Auto-Subliminal\lib\subliminal\core.py", line 598, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\subliminal\refiners\omdb.py", line 155, in refine
    results = search(video.title, 'movie', video.year)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\dogpile\cache\region.py", line 1223, in decorate
    key = key_generator(*arg, **kw)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\dogpile\cache\util.py", line 42, in generate_key
    return namespace + "|" + " ".join(map(to_str, args))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 14: ordinal not in range(128)
```

**Comment by h3llrais3r** [comment]
Same problem will happen on all places where we use `@region.cache_on_arguments` and values can contain non ascii characters. 
I suppose we should convert all unicode params to byte params when use the dogpile cache?
Or perhaps it's better to fix it directly in dogpile cache itself?

**Comment by fernandog** [comment]
@h3llrais3r `all unicode params to byte params when using the dogpile cache` - how would you do that?

**Comment by h3llrais3r** [comment]
@fernandog Perhaps making a custom decorator for the caching that converts the unicode string params (encode with utf-8) to byte string params before doing the caching?
Not sure if this is a good approach and if it's feasible...

**Comment by h3llrais3r** [comment]
I got something working for omdb, but did not test with others.
Idea is to use a custom `function_key_generator`:

```python
def v2b(value):
    """Convert a value to the binary type value."""
    if isinstance(value, six.text_type):
        return value.encode('utf-8')
    else:
        return six.binary_type(value)


def my_function_key_generator(namespace, fn, to_str=v2b):
    """Return a function that generates a string
    key, based on a given function as well as
    arguments to the returned function itself.

    This is used by :meth:`.CacheRegion.cache_on_arguments`
    to generate a cache key from a decorated function.

    An alternate function may be used by specifying
    the :paramref:`.CacheRegion.function_key_generator` argument
    for :class:`.CacheRegion`.

    .. seealso::

        :func:`.kwarg_function_key_generator` - similar function that also
        takes keyword arguments into account

    """

    if namespace is None:
        namespace = '%s:%s' % (fn.__module__, fn.__name__)
    else:
        namespace = '%s:%s|%s' % (fn.__module__, fn.__name__, namespace)

    args = inspect.getargspec(fn)
    has_self = args[0] and args[0][0] in ('self', 'cls')

    def generate_key(*args, **kw):
        if kw:
            raise ValueError(
                "dogpile.cache's default key creation "
                "function does not accept keyword arguments.")
        if has_self:
            args = args[1:]

        return namespace + "|" + " ".join(map(to_str, args))

    return generate_key


region = make_region(function_key_generator=my_function_key_generator)
```

This in the `cache.py`

**Comment by fernandog** [comment]
@ratoaq2 ideas?

**Comment by h3llrais3r** [comment]
@fernandog, @ratoaq2 What do you think?
Do I create a PR with the proposed changes to fix the dopgpile caching for keys with non-ascii characters?

**Comment by fernandog** [comment]
Sure
