### ISSUE TITLE
Docker Sublimininal - `.lower()` error thrown on certain videos

### ISSUE THREAD

**Issue by abescalamis** [Diaoul/subliminal#889]
I been using the latest docker subliminal image and I get the error related to the `.lower()` error thrown on certain videos.

I read that this issue was fixed #800 but I don't think that the docker image has this change, it looks like it hasn't been merge yet, I'm using a docker image and was wondering if someone knows how to edit the image and add this fix.

also related to #761 #769 

Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    load_entry_point('subliminal', 'console_scripts', 'subliminal')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/src/app/subliminal/cli.py", line 400, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/src/app/subliminal/core.py", line 261, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/src/app/subliminal/core.py", line 261, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/src/app/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/src/app/subliminal/providers/opensubtitles.py", line 81, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/usr/src/app/subliminal/subtitle.py", line 235, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'

**Comment by pando85** [comment]
:+1:

**Comment by Waester** [comment]
Actually, there are currently no commit(s) that have fixed this problem yet.
(https://github.com/Diaoul/subliminal/commits/develop/subliminal/subtitle.py)

There are some pull requests, but none that have been approved yet.

**Comment by abescalamis** [comment]
The fix is supposed to be this, and is in the pull request
https://github.com/Diaoul/subliminal/pull/800/files/c9586d9f589a8bb3bdc70448bf628e1eadaac22e

**Comment by Waester** [comment]
@Diaoul 

Any update on this? As this seems to affect quite many videos (atleast in my library).

**Comment by jackkiej** [comment]
So guys...
Could you please fix this? We have an issue with this on Sickrage:
https://github.com/SickRage/SickRage/issues/4546

**Comment by monster400** [comment]
Should we fork subliminal so we can get a working version, since Diaoul haven't done anything since 2016

**Comment by Diaoul** [comment]
Contributors are welcome to step up, I can grant push access to this repository.

**Comment by monster400** [comment]
@Diaoul im not that skilled at all but i managed to fork, build and upload to docker hub

**Comment by ratoaq2** [comment]
Fixed by https://github.com/Diaoul/subliminal/commit/3121a75499779c7cc9eba059a4fa123cf5541027
