### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by dima-vy** [Diaoul/subliminal#892]
It's some days already when i can't download subtitles from Addic7ed. Is anybody having trouble also? The error as following:
ERROR:subliminal.core:Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/opt/lib/python2.7/site-packages/subliminal-2.0.5-py2.7.egg/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/opt/lib/python2.7/site-packages/subliminal-2.0.5-py2.7.egg/subliminal/providers/addic7ed.py", line 273, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/opt/lib/python2.7/site-packages/subliminal-2.0.5-py2.7.egg/subliminal/providers/addic7ed.py", line 228, in query
    show_id = self.get_show_id(series, year, country)
  File "/opt/lib/python2.7/site-packages/subliminal-2.0.5-py2.7.egg/subliminal/providers/addic7ed.py", line 222, in get_show_id
    show_id = self._search_show_id(series)
  File "/opt/lib/python2.7/site-packages/dogpile.cache-0.6.1-py2.7.egg/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/opt/lib/python2.7/site-packages/dogpile.cache-0.6.1-py2.7.egg/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/opt/lib/python2.7/site-packages/dogpile.cache-0.6.1-py2.7.egg/dogpile/lock.py", line 154, in __enter__
    return self._enter()
  File "/opt/lib/python2.7/site-packages/dogpile.cache-0.6.1-py2.7.egg/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(createdtime)
  File "/opt/lib/python2.7/site-packages/dogpile.cache-0.6.1-py2.7.egg/dogpile/lock.py", line 145, in _enter_create
    created = self.creator()
  File "/opt/lib/python2.7/site-packages/dogpile.cache-0.6.1-py2.7.egg/dogpile/cache/region.py", line 625, in gen_value
    created_value = creator()
  File "/opt/lib/python2.7/site-packages/dogpile.cache-0.6.1-py2.7.egg/dogpile/cache/region.py", line 1049, in creator
    return fn(*arg, **kw)
  File "/opt/lib/python2.7/site-packages/subliminal-2.0.5-py2.7.egg/subliminal/providers/addic7ed.py", line 170, in _search_show_id
    raise TooManyRequests()
TooManyRequests

Thank you guys

**Comment by fernandog** [comment]
Fixed in develop

**Comment by darzur** [comment]
Hi,
What do you mean by "fixed in develop"? Develop wasn't updated since 8 days and issue still exists.

**Comment by CyberMew** [comment]
I also haven't been able to get the subtitles from them as well for the past week. Not sure what happened.

**Comment by fernandog** [comment]
@CyberMew addic7ed active block subliminal. you might consider user another providers or keep trying.

**Comment by dima-vy** [comment]
@fernandog You wrote that it was fixed in develop, so was it fixed or there is still a problem?

Thank you

**Comment by fernandog** [comment]
We can't fix the addic7ed block
