### ISSUE TITLE
Issue when trying to download subtitles - expected string or bytes-like object

### ISSUE THREAD

**Issue by gergesh** [Diaoul/subliminal#894]
The command I'm running is `subliminal download -l en Videos/Office1080/The\ Office\ \(US\)\ \(2005\)\ Season\ 2\ S02\ +\ Extras\ \(1080p\ AMZN\ WEB-DL\ x265\ HEVC\ 10bit\ AAC\ 2.0\ LION\)/The\ Office\ \(US\)\ \(2005\)\ -\ S02E12\ -\ The\ Injury\ \(1080p\ AMZN\ WEB-DL\ x265\ LION\).mkv`
Output:
```
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  The Office (US) (2005) - S02E12 - The Injury (1080p AMZN WEB-DL x265 LION).mkv
Traceback (most recent call last):
  File "/usr/bin/subliminal", line 11, in <module>
    load_entry_point('subliminal==2.0.5', 'console_scripts', 'subliminal')()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/lib/python3.6/site-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/lib/python3.6/site-packages/subliminal/core.py", line 211, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/lib/python3.6/site-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/lib/python3.6/site-packages/subliminal/providers/podnapisi.py", line 52, in get_matches
    if video.series and sanitize(self.title) == sanitize(video.series):
  File "/usr/lib/python3.6/site-packages/subliminal/utils.py", line 111, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```
Cleaning my cache changed nothing, what am I doing wrong?

**Comment by ratoaq2** [comment]
This is a guessit bug. I opened an issue in guessit: https://github.com/guessit-io/guessit/issues/593

**Comment by ratoaq2** [comment]
You can update to latest guessit develop to fix the issue
