### ISSUE TITLE
Error with file extensions in capital characters

### ISSUE THREAD

**Issue by tigre-bleu** [Diaoul/subliminal#896]
I use subliminal as part of [Bazaar](https://github.com/morpheus65535/bazarr)

Unfortunately, it does not work with files that have a capital extension. For instance it works for test.mkv but not for test.MKV

```
# subliminal --debug download -l en /tmp/Test.MKV 
Collecting videos  [####################################]  100%  /tmp/Test.MKVDEBUG:subliminal.cli:Collecting path /tmp/Test.MKV
ERROR:subliminal.cli:Unexpected error while collecting path /tmp/Test.MKV
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 352, in download
    video = scan_video(p)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 374, in scan_video
    raise ValueError('%r is not a valid video extension' % os.path.splitext(path)[1])
ValueError: '.MKV' is not a valid video extension
Collecting videos  [####################################]  100%               
0 video collected / 0 video ignored / 1 error
```

**Comment by fernandog** [comment]
Fix already in works

**Comment by morpheus65535** [comment]
Take a look at #861 . Unfortunately, it's only in dev branch of Subliminal.

@fernandog Are you going to release another v2.x version or we have to wait for v3?
