### ISSUE TITLE
Unexpected error in provider "thesubdb"

### ISSUE THREAD

**Issue by Rwanou88** [Diaoul/subliminal#903]
**Soft/Branch/Commit:**
SickBeard Custom / master / `d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe`
**OS:**
Linux-4.4.15+-x86_64-with-glibc2.2.5
**What you did:**
Automatic search
**What happened:**
I had this error
**What you expected:**
Subs search on this provider

**Logs:**
```
2018-03-23 15:57:10 WARNING  FINDSUBTITLES :: [d6eb72d] Unexpected error in provider u'thesubdb'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/thesubdb.py", line 80, in list_subtitles
    return [s for s in self.query(video.hashes['thesubdb']) if s.language in languages]
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/thesubdb.py", line 60, in query
    r = self.session.get(self.server_url, params=params, timeout=10)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='api.thesubdb.com', port=80): Max retries exceeded with url: /?action=search&hash=faf62ce6e47e7797b9508b2bd96720c7 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f00799ea350>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

**Comment by ratoaq2** [comment]
This is an issue with your network that was temporary unavailable:

`Failed to establish a new connection: [Errno -3] Temporary failure in name resolution`
