### ISSUE TITLE
[shooter] json.decoder.JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by marcelpaulo** [Diaoul/subliminal#914]
Provider **shooter** is generating this error, whether the series episode has subtitles or not:

```
ERROR:subliminal.core:Unexpected error in provider 'shooter'
Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/core.py", line 134, in list_subtitles_provider                                                 
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/providers/shooter.py", line 76, in list_subtitles                                              
    return [s for l in languages for s in self.query(l, video.name, video.hashes.get('shooter'))]                                                                                                
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/providers/shooter.py", line 76, in <listcomp>                                                  
    return [s for l in languages for s in self.query(l, video.name, video.hashes.get('shooter'))]                                                                                                
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/providers/shooter.py", line 70, in query                                                       
    results = json.loads(r.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:subliminal.core:Discarding provider shooter
```

I tried with these episodes, and the error was exactly the same:

```
deep.state.s01e02.hdtv.x264-mtb.mkv
imposters.s02e02.web.x264-tbs.mkv
In.The.Long.Run.S01E04.HDTV.x264-MTB[eztv].mkv
```

I'm running subliminal from branch develop (22c5a9ecc2b00d43f84d84ccd63c4b1068b18fb2), on Xubuntu 17.10, with guessit guessit-io/guessit@994bdba5e62ce2fa02dc544e520ab058c0931274

Here's the full `--debug` from _In.The.Long.Run.S01E04.HDTV.x264-MTB[eztv].mkv_:

```
+paulo@monk:~/watch/stage$ subliminal --debug download --verbose --language en --single --refiner metadata --refiner tvdb --min-score 96 In.The.Long.Run.S01E04.HDTV.x264-MTB\[eztv\].mkv
Collecting videos  [####################################]  100%  In.The.Long.Run.S01E04.HDTV.x264-MTB[eztv].mkvDEBUG:subliminal.cli:Collecting path In.The.Long.Run.S01E04.HDTV.x264-MTB[eztv].mkv
INFO:subliminal.core:Scanning video 'In.The.Long.Run.S01E04.HDTV.x264-MTB[eztv].mkv' in ''
DEBUG:subliminal.core:Size is 205460337
DEBUG:subliminal.core:Computed hashes {'opensubtitles': '350718acf68972bc', 'shooter': 'fc78edae3214902740c26e4280d09875;0abf2abd77fcd651ed50101e1f395f3a;5d685dbe76f628b9d0ef6f5890d2fb57;a72971cc64c72f0b79d200318fb271de', 'thesubdb': '5efbcdc273044e37f0c030b7f55158e3', 'napiprojekt': 'fb9d07d20f4054e8fc3d79d5f38f05d1'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found video_codec h264
DEBUG:subliminal.refiners.metadata:Found audio_codec AAC
DEBUG:subliminal.refiners.metadata:MKV has no subtitle track
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'In The Long Run'
DEBUG:subliminal.refiners.tvdb:Found 1 results
DEBUG:subliminal.refiners.tvdb:Found exact match on series 'In The Long Run'
DEBUG:subliminal.refiners.tvdb:Found series {'id': 336739, 'seriesName': 'In The Long Run', 'aliases': [], 'banner': 'graphical/336739-g2.jpg', 'seriesId': '', 'status': 'Continuing', 'firstAired': '2018-03-29', 'network': 'Sky1', 'networkId': '', 'runtime': '30', 'genre': ['Comedy'], 'overview': 'The Easmon family living in London in 1985 sees their quiet life disrupted when their relative from Sierra Leone moves in.\r\n\r\nThe comedy, inspired by the childhood memories of Idris Elba follows the story of Walter and Agnes Easmon whose life is all about quiet routine. They arrived from Sierra Leone 13 years ago and work hard to pay the bills, raise son Kobna as well as support their family back home.', 'lastUpdated': 1522701804, 'airsDayOfWeek': 'Thursday', 'airsTime': '22:00', 'rating': '', 'imdbId': 'tt7464074', 'zap2itId': '', 'added': '2017-10-21 15:43:02', 'addedBy': 369062, 'siteRating': 0, 'siteRatingCount': 0}
INFO:subliminal.refiners.tvdb:Getting series episode 1x4
DEBUG:subliminal.refiners.tvdb:Found episode {'id': 6589210, 'airedSeason': 1, 'airedSeasonID': 747125, 'airedEpisodeNumber': 4, 'episodeName': 'Episode 4', 'firstAired': '2018-04-12', 'guestStars': [], 'director': '', 'directors': [], 'writers': [], 'overview': "Walter and Agnes step in to save goddaughter Cynthia's engagement party. But when it comes to the ceremony, things don't exactly go smoothly...", 'language': {'episodeName': 'en', 'overview': 'en'}, 'productionCode': '', 'showUrl': '', 'lastUpdated': 1522560284, 'dvdDiscid': '', 'dvdSeason': None, 'dvdEpisodeNumber': None, 'dvdChapter': None, 'absoluteNumber': None, 'filename': '', 'seriesId': 336739, 'lastUpdatedBy': 369062, 'airsAfterSeason': None, 'airsBeforeSeason': None, 'airsBeforeEpisode': None, 'thumbAuthor': 1, 'thumbAdded': '', 'thumbWidth': None, 'thumbHeight': None, 'imdbId': '', 'siteRating': 0, 'siteRatingCount': 0}
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  In.The.Long.Run.S01E04.HDTV.x264-MTB[eztv].mkvINFO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider addic7ed
DEBUG:subliminal.providers.addic7ed:Getting show id with year
INFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages {<Language [en]>}
DEBUG:subliminal.providers.addic7ed:Getting show id
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [en]>}
INFO:subliminal.providers.addic7ed:Getting the page of show id 6835, season 1
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages {<Language [en]>}
INFO:subliminal.core:Listing subtitles with provider 'shooter' and languages {<Language [en]>}
INFO:subliminal.core:Listing subtitles with provider 'thesubdb' and languages {<Language [en]>}
INFO:subliminal.providers.opensubtitles:Logging in
INFO:subliminal.core:Listing subtitles with provider 'tvsubtitles' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider podnapisi
INFO:subliminal.core:Initializing provider shooter
INFO:subliminal.core:Initializing provider thesubdb
INFO:subliminal.core:Initializing provider tvsubtitles
INFO:subliminal.providers.podnapisi:Searching subtitles {'sXML': 1, 'sL': 'en', 'sK': 'In The Long Run', 'sTS': 1, 'sTE': 4, 'sY': 2018}
INFO:subliminal.providers.legendastv:Searching episode title 'in the long run' for season 1
INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': '5efbcdc273044e37f0c030b7f55158e3'}
DEBUG:subliminal.providers.shooter:Searching subtitles {'filehash': 'fc78edae3214902740c26e4280d09875;0abf2abd77fcd651ed50101e1f395f3a;5d685dbe76f628b9d0ef6f5890d2fb57;a72971cc64c72f0b79d200318fb271de', 'pathinfo': '/home/paulo/watch/stage/In.The.Long.Run.S01E04.HDTV.x264-MTB[eztv].mkv', 'format': 'json', 'lang': 'eng'}
ERROR:subliminal.providers.tvsubtitles:No show id found for 'In The Long Run' ({'year': 2018})
DEBUG:subliminal.providers.thesubdb:No subtitles found
DEBUG:subliminal.providers.opensubtitles:Logged in with token '2DlW1XY,ajRfl6sI0pvgXWVm09b'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviehash': '350718acf68972bc', 'moviebytesize': '205460337', 'sublanguageid': 'eng'}, {'tag': 'In.The.Long.Run.S01E04.HDTV.x264-MTB[eztv].mkv', 'sublanguageid': 'eng'}, {'query': 'In The Long Run', 'season': 1, 'episode': 4, 'sublanguageid': 'eng'}]
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/133618/0' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/133618/1' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/133618/2' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/8/133618/2' [fr]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/133618/3' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/8/133618/4' [fr]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/133632/0' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/133632/1' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/133632/2' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/8/133632/2' [fr]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/133632/3' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/8/133632/4' [fr]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/134031/0' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/134031/1' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/134031/2' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/134031/3' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/134031/4' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/1/134031/5' [en]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/8/134031/6' [fr]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/8/134031/7' [fr]>
DEBUG:subliminal.providers.addic7ed:Found subtitle <Addic7edSubtitle 'updated/8/134031/8' [fr]>
DEBUG:subliminal.providers.legendastv:Found 0 titles
DEBUG:subliminal.providers.podnapisi:No subtitles found
DEBUG:subliminal.providers.opensubtitles:No subtitles found
ERROR:subliminal.core:Unexpected error in provider 'shooter'
Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/providers/shooter.py", line 76, in list_subtitles
    return [s for l in languages for s in self.query(l, video.name, video.hashes.get('shooter'))]
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/providers/shooter.py", line 76, in <listcomp>
    return [s for l in languages for s in self.query(l, video.name, video.hashes.get('shooter'))]
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/providers/shooter.py", line 70, in query
    results = json.loads(r.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:subliminal.core:Discarding provider shooter
Downloading subtitles  [####################################]  100%
Some providers have been discarded due to unexpected errors: shooter
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider addic7ed
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.core:Terminating provider podnapisi
INFO:subliminal.core:Terminating provider shooter
INFO:subliminal.core:Terminating provider thesubdb
INFO:subliminal.core:Terminating provider tvsubtitles
INFO:subliminal.core:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
0 subtitle downloaded for In.The.Long.Run.S01E04.HDTV.x264-MTB[eztv].mkv
+
```

**Comment by marcelpaulo** [comment]
This is not reproducible anymore. It looks like it was a temporary problem with the `shooter` provider.
