### ISSUE TITLE
SyntaxError: Non-ASCII character

### ISSUE THREAD

**Issue by Guduche** [Diaoul/subliminal#919]
I have an error when I use subliminal, could you help me please ?
I use this command:

```subliminal -l en /nas/videos/Series/```

And this the traceback of the error:

```Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 7, in <module>
    from subliminal.cli import subliminal
  File "/usr/local/lib/python2.7/dist-packages/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 13, in <module>
    from guessit import guessit
  File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 6, in <module>
    from .api import guessit, GuessItApi
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 13, in <module>
    import six
  File "/usr/lib/python2.7/dist-packages/six.py", line 260
SyntaxError: Non-ASCII character '\xe2' in file /usr/lib/python2.7/dist-packages/six.py on line 260, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Thank you

**Comment by ratoaq2** [comment]
Try to reinstall it

**Comment by Guduche** [comment]
It works, now that I've reinstalled it, I don't now what was the problem
