### ISSUE TITLE
Catch "HTTPError: 503 Server Error" exceptions and show error message

### ISSUE THREAD

**Issue by marcelpaulo** [Diaoul/subliminal#923]
The TheTVDB service was unavailable right now and, as expected, subliminal threw an exception:

```
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'Carter'
ERROR:subliminal.core:Failed to refine video 'Carter.S01E03.HDTV.x264-aAF[ettv].mkv'
DEBUG:subliminal.core:Refiner exception:
Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/core.py", line 607, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/refiners/tvdb.py", line 267, in refine
    results = search_series(video.series.lower())
  File "/home/paulo/.local/lib/python3.6/site-packages/dogpile.cache-0.6.5-py3.6.egg/dogpile/cache/region.py", line 1250, in decorate
    should_cache_fn)
  File "/home/paulo/.local/lib/python3.6/site-packages/dogpile.cache-0.6.5-py3.6.egg/dogpile/cache/region.py", line 844, in get_or_create
    async_creator) as value:
  File "/home/paulo/.local/lib/python3.6/site-packages/dogpile.cache-0.6.5-py3.6.egg/dogpile/lock.py", line 154, in __enter__
    return self._enter()
  File "/home/paulo/.local/lib/python3.6/site-packages/dogpile.cache-0.6.5-py3.6.egg/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(createdtime)
  File "/home/paulo/.local/lib/python3.6/site-packages/dogpile.cache-0.6.5-py3.6.egg/dogpile/lock.py", line 145, in _enter_create
    created = self.creator()
  File "/home/paulo/.local/lib/python3.6/site-packages/dogpile.cache-0.6.5-py3.6.egg/dogpile/cache/region.py", line 811, in gen_value
    created_value = creator()
  File "/home/paulo/.local/lib/python3.6/site-packages/dogpile.cache-0.6.5-py3.6.egg/dogpile/cache/region.py", line 1246, in creator
    return fn(*arg, **kw)
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/refiners/tvdb.py", line 206, in search_series
    return tvdb_client.search_series(name)
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/refiners/tvdb.py", line 24, in wrapper
    self.login()
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/refiners/tvdb.py", line 101, in login
    r.raise_for_status()
  File "/home/paulo/.local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.thetvdb.com/login
```

But I wondered: shouldn't exceptions like this one be caught and an error message be shown instead ?

I'm running an up-to-date subliminal develop (22c5a9e) on Xubuntu 18.04.

**Comment by ratoaq2** [comment]
Fixed by ebe2784d52d471e39db711dcd43cb7c12193c661

Just to note that the exception was only shown when in debug mode.
