### ISSUE TITLE
Allow passing options (-T and -t) to guessit so that movie names with string "season" are correctly parsed

### ISSUE THREAD

**Issue by marcelpaulo** [Diaoul/subliminal#926]
Trying to download subtitles for movie _The.Delinquent.Season.2017.720p.WEBRip.x264-[YTS.AM].mp4_:

```
paulo:~/tmp$ subliminal --debug download -l en The.Delinquent.Season.2017.720p.WEBRip.x264-\[YTS.AM\].mp4
Collecting videos  [####################################]  100%  The.Delinquent.Season.2017.720p.WEBRip.x264-[YTS.AM].mp4DEBUG:subliminal.cli:Collecting path The.Delinquent.Season.2017.720p.WEBRip.x264-[YTS.AM].mp4
INFO:subliminal.core:Scanning video 'The.Delinquent.Season.2017.720p.WEBRip.x264-[YTS.AM].mp4' in ''
ERROR:subliminal.cli:Unexpected error while collecting path The.Delinquent.Season.2017.720p.WEBRip.x264-[YTS.AM].mp4
Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/cli.py", line 349, in download
    video = scan_video(p)
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/core.py", line 430, in scan_video
    video = Video.fromguess(path, guessit(path))
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/video.py", line 93, in fromguess
    return Episode.fromguess(name, guess)
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/video.py", line 170, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
Collecting videos  [####################################]  100%
0 video collected / 0 video ignored / 1 error
```

I suspected and confirmed that `guessit` might be parsing the movie as en episode because of the string _season_:

```
paulo:~/tmp$ guessit The.Delinquent.Season.2017.720p.WEBRip.x264-\[YTS.AM\].mp4
For: The.Delinquent.Season.2017.720p.WEBRip.x264-[YTS.AM].mp4
GuessIt found: {
    "title": "The Delinquent",
    "season": 2017,
    "year": 2017,
    "screen_size": "720p",
    "source": "Web",
    "other": "Rip",
    "video_codec": "H.264",
    "release_group": "YTS.AM",
    "container": "mp4",
    "mimetype": "video/mp4",
    "type": "episode"
}
```

To make `guessit` parse it correctly, I found out I had to explicitly say it was a movie:

```
paulo:~/tmp$ guessit -t movie The.Delinquent.Season.2017.720p.WEBRip.x264-\[YTS.AM\].mp4
For: The.Delinquent.Season.2017.720p.WEBRip.x264-[YTS.AM].mp4
GuessIt found: {
    "title": "The Delinquent Season",
    "year": 2017,
    "screen_size": "720p",
    "source": "Web",
    "other": "Rip",
    "video_codec": "H.264",
    "release_group": "YTS.AM",
    "container": "mp4",
    "mimetype": "video/mp4",
    "type": "movie"
}
```

But then I couldn't find any `subliminal` option to pass `-t movie` to `guessit`. If it isn't indeed possible, could I ask that as a feature request ?

**PS:** For this particular movie, a workaround was renaming it to _The.Delinquent.Season.720p.WEBRip.x264-[YTS.AM].mp4_: `guessit` then parsed it correctly as a movie, and `subliminal` could go along with that.

**Comment by ratoaq2** [comment]
You can create a guessit config file with the expected titles that you need:

https://github.com/guessit-io/guessit/blob/develop/docs/configuration.rst

This is the default config file guessit uses (so you can see the options that you can tweak):
https://github.com/guessit-io/guessit/blob/develop/guessit/config/options.json/

**Comment by ratoaq2** [comment]
Closing it, since it's already possible to define expected titles for guessit when using subliminal
