### ISSUE TITLE
[podnapisi] ProviderError: More than one file to unzip

### ISSUE THREAD

**Issue by marcelpaulo** [Diaoul/subliminal#929]
I'm running latest subliminal from git develop (22c5a9e), on Xubuntu 18.04.

I've just tried to download English subtitles for _Next.Stop,.Greenwich.Village.1976.720p.BluRay.x264-[YTS.AM].mp4_ using this command line (I've omitted login information)

```
subliminal --debug download --refiner metadata --refiner tvdb -l en -m 0 -s Next.Stop,.Greenwich.Village.1976.720p.BluRay.x264-[YTS.AM].mp4
```

and got this error:

```
INFO:subliminal.score:Computed score 91 with final matches {'hearing_impaired', 'year', 'title'}
INFO:subliminal.core:Downloading subtitle <PodnapisiSubtitle 'lDIC' [en]>
INFO:subliminal.providers.podnapisi:Downloading subtitle <PodnapisiSubtitle 'lDIC' [en]>
ERROR:subliminal.core:Unexpected error in provider 'podnapisi', discarding it
Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/core.py", line 199, in download_subtitle
    self[subtitle.provider_name].download_subtitle(subtitle)
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/providers/podnapisi.py", line 195, in download_subtitle
    raise ProviderError('More than one file to unzip')
subliminal.exceptions.ProviderError: More than one file to unzip
```

The full output is [here](https://paste.ee/p/Kojtq).

**Comment by ratoaq2** [comment]
I tried the same command with latest development 3f32e8a5734876ae373c2c5614db77a03ae5d391, and I was able to properly download the subtitle.

Could you confirm that's not an issue anymore?

**Comment by yardenac** [comment]
I'm seeing this same error with 160ea63.
