### ISSUE TITLE
Issue downloading subtitles

### ISSUE THREAD

**Issue by Cylae** [Diaoul/subliminal#933]
Hello, I encounter this issue, there is any way to fix it ? 

Thank you very much for your help

```subliminal download -l en -l fr /home/plex/movies/*
Collecting videos  [####################################]  100%
20 videos collected / 34 videos ignored / 0 error
Downloading subtitles  [##################------------------]   50%  0d 00:00:47  Amélie (2001) Bluray-1080p.mp4           /usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py:351: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if sanitize(t['title']) != sanitize(title):
/usr/local/lib/python2.7/dist-packages/subliminal/providers/podnapisi.py:69: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if video.title and sanitize(self.title) == sanitize(video.title):
/usr/local/lib/python2.7/dist-packages/subliminal/subtitle.py:224: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if video.title and 'title' in guess and sanitize(guess['title']) == sanitize(video.title):
Downloading subtitles  [#########################-----------]   70%  0d 00:00:29  Austin Powers International Man of Mystery (1997) Bluray-1080p.mp4
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/opensubtitles.py", line 99, in get_matches
    matches |= guess_matches(video, guessit(self.filename, {'type': 'movie'}))
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 69, in guessit
    return default_api.guessit(string, options)
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 182, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.0.0
string=[HDTeam] Austin.Powers.Misterioso.Agente.Internacional.1997.[1080p].[BluRay].[Dual].[Subs].[x264]-by
options={'type': 'movie'}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 170, in guessit
    matches = self.rebulk.matches(string, options)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/usr/local/lib/python2.7/dist-packages/guessit/rules/processors.py", line 220, in then
    if match.raw[0] in seps_no_groups and (len(match.raw) < 3 or match.raw[2] not in seps_no_groups):
IndexError: string index out of range
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
```

**Comment by spider1163** [comment]
Hello,
are PIP + subliminal up-to-date ?

**Comment by Cylae** [comment]
Hello @spider1163,

I tried to install via apt, apt-get, pip, pip3...

I also deleted the cache file under the .root folder but the issue still here...

**Comment by alanaasmaa** [comment]
I had problems with spaces in folder names.

I created this alias for this
`alias subs="subliminal --opensubtitles {{REPLACEWITHUSERNAME}} \"{{REPLACEWITHPASSWORD}}\" download -l fi -l en -v -w 8 \"`pwd -W`\""
`

**Comment by ratoaq2** [comment]
This looks a guessit issue and you were using guessit 3.0.0
Try updating it to guessit 3.0.3 and let me know if that's still an issue
