### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by nicolabeghin** [Diaoul/subliminal#974]
Hi everyone
I'm currently experiencing an issue with subliminal used through official Docker image. I already made sure guessit is updated as in #894 and #775. 

> subliminal, version 2.1.0.dev
> guessit, version 3.0.4

    Traceback (most recent call last):
      File "/usr/local/bin/subliminal", line 11, in <module>
        load_entry_point('subliminal', 'console_scripts', 'subliminal')()
      File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/usr/src/app/subliminal/cli.py", line 436, in download
        hearing_impaired=hearing_impaired, only_one=single)
      File "/usr/src/app/subliminal/core.py", line 260, in download_best_subtitles
        for s in subtitles], key=operator.itemgetter(1), reverse=True)
      File "/usr/src/app/subliminal/core.py", line 260, in <listcomp>
        for s in subtitles], key=operator.itemgetter(1), reverse=True)
      File "/usr/src/app/subliminal/score.py", line 106, in compute_score
        matches = subtitle.get_matches(video)
      File "/usr/src/app/subliminal/providers/podnapisi.py", line 53, in get_matches
        sanitize(name) for name in [video.series] + video.alternative_series)):
      File "/usr/src/app/subliminal/providers/podnapisi.py", line 53, in <genexpr>
        sanitize(name) for name in [video.series] + video.alternative_series)):
      File "/usr/src/app/subliminal/utils.py", line 111, in sanitize
        string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
      File "/usr/local/lib/python3.7/re.py", line 192, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object

any hint on this? Below an example filename.

- S02E01 Undercover.mkv

thanks
nicola

**Comment by guss77** [comment]
I have the same issue with Python 3.6, though a somewhat different stack trace:

```
Traceback (most recent call last):
  File "/home/media/.local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/home/media/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/media/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/media/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/media/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/media/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/media/.local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/media/.local/lib/python3.6/site-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/home/media/.local/lib/python3.6/site-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/home/media/.local/lib/python3.6/site-packages/subliminal/core.py", line 211, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/home/media/.local/lib/python3.6/site-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/home/media/.local/lib/python3.6/site-packages/subliminal/providers/podnapisi.py", line 52, in get_matches
    if video.series and sanitize(self.title) == sanitize(video.series):
  File "/home/media/.local/lib/python3.6/site-packages/subliminal/utils.py", line 111, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

For me the problem was that the show name returned from guessit is sometimes an array, and subliminal code (and specifically how some providers are written) does not take that into consideration.

I'll issue a PR a bit later with code that solved the problem for me.

**Comment by ratoaq2** [comment]
This should already be fixed in the latest version. Please reopen if not

**Comment by guss77** [comment]
I cannot repro with version 2.1.0. Thank you!
