### ISSUE TITLE
traceback when running

### ISSUE THREAD

**Issue by jrwren** [Diaoul/subliminal#978]
Traceback (most recent call last):
  File "/home/jrwren/sublimvenv/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/home/jrwren/sublimvenv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jrwren/sublimvenv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jrwren/sublimvenv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jrwren/sublimvenv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jrwren/sublimvenv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jrwren/sublimvenv/local/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/jrwren/sublimvenv/local/lib/python2.7/site-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/home/jrwren/sublimvenv/local/lib/python2.7/site-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/home/jrwren/sublimvenv/local/lib/python2.7/site-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/home/jrwren/sublimvenv/local/lib/python2.7/site-packages/subliminal/providers/opensubtitles.py", line 99, in get_matches
    matches |= guess_matches(video, guessit(self.filename, {'type': 'movie'}))
  File "/home/jrwren/sublimvenv/local/lib/python2.7/site-packages/subliminal/subtitle.py", line 235, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'

**Comment by ratoaq2** [comment]
This issue was fixed long time ago in develop branch. With the new release 2.1.0, this is also fixed in master
