### ISSUE TITLE
Error with latest version of guessit/regex

### ISSUE THREAD

**Issue by gkatev** [Diaoul/subliminal#992]
The last couple days subliminal has not been working at all for me, on Arch Linux. The debug log shows it's to do with an error in guessit:

```
DEBUG:subliminal.cli:Collecting path Vikings.S06E01.720p.HDTV.x265-MiNX.mkv
INFO:subliminal.core:Scanning video 'Vikings.S06E01.720p.HDTV.x265-MiNX.mkv' in ''
ERROR:subliminal.cli:Unexpected error while collecting path Vikings.S06E01.720p.HDTV.x265-MiNX.mkv
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/lib/python3.8/site-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/python3.8/site-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/python3.8/site-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/python3.8/site-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/python3.8/site-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/python3.8/site-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'private_parent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/subliminal/cli.py", line 352, in download
    video = scan_video(p)
  File "/usr/lib/python3.8/site-packages/subliminal/core.py", line 380, in scan_video
    video = Video.fromguess(path, guessit(path))
  File "/usr/lib/python3.8/site-packages/guessit/api.py", line 71, in guessit
    return default_api.guessit(string, options)
  File "/usr/lib/python3.8/site-packages/guessit/api.py", line 222, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=Vikings.S06E01.720p.HDTV.x265-MiNX.mkv
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/lib/python3.8/site-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/python3.8/site-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/python3.8/site-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/python3.8/site-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/python3.8/site-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/python3.8/site-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'private_parent'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
0 video collected / 0 video ignored / 1 error
```
I came across a similar issue in guessit's repo: https://github.com/guessit-io/guessit/issues/633, and indeed it appears downgrading python-regex (2020.1.8-1 => 2019.12.20-1) makes the error go away.
The environ workaround mention in the issue (eg. in /usr/bin/subliminal) also makes the error go away, with the latest version of python-regex.

I'm posting this here for others that may encounter the same problem, sorry if it's not relevant.
Or perhaps the workaround in https://github.com/guessit-io/guessit/issues/633 could also be added to subliminal.

**Comment by dkasak** [comment]
Interestingly, the environment variable workaround is not working for me. I'm also on Arch Linux.

**Comment by phiresky** [comment]
more relevant issues: https://github.com/guessit-io/guessit/issues/639

https://github.com/Toilal/rebulk/issues/20

The root issue is this change in the `regex` library: https://bitbucket.org/mrabarnett/mrab-regex/issues/357/new-exception-valueerror-unused-keyword

The fix will probably need to be in rebulk adding the `ignore_unused`.

**Comment by ratoaq2** [comment]
Fixed in latest rebulk.
Update rebulk to 2.0.1
https://github.com/Toilal/rebulk/releases/tag/2.0.1
