### ISSUE TITLE
Error while trying to download subtitles

### ISSUE THREAD

**Issue by ickam** [Diaoul/subliminal#994]
While trying to download subtitles I get the following error
```bash
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 10, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1965, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1589, in full_process_value
    value = self.process_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1579, in process_value
    return self.type_cast_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1568, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1566, in _convert
    return tuple(_convert(x, level - 1) for x in value or ())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1566, in <genexpr>
    return tuple(_convert(x, level - 1) for x in value or ())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1565, in _convert
    return self.type(value, self, ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/types.py", line 46, in __call__
    return self.convert(value, param, ctx)
  File "/usr/local/lib/python3.7/dist-packages/subliminal/cli.py", line 173, in convert
    return Language.fromietf(value)
  File "/usr/local/lib/python3.7/dist-packages/babelfish/language.py", line 126, in fromietf
    language = cls(language_subtag)
  File "/usr/local/lib/python3.7/dist-packages/babelfish/language.py", line 82, in __init__
    raise ValueError('%r is not a valid language' % language)
ValueError: '=en' is not a valid language
```
I tried both pip and pip3 installations and there doesn't seem to be a difference

**Comment by ickam** [comment]
I've been putting an "=" mark after l, which was wrong.
