### ISSUE TITLE
Crash on 93% of scanning a folder on Ubuntu 18.04

### ISSUE THREAD

**Issue by taladro** [Diaoul/subliminal#997]
Hi for the first time I used SUBLIMINAL and got this error. I´m running Ubuntu 18.04 and my knowledge of Linux is very limited. Thanks

Downloading subtitles  [#################################---]   93%  00:01:27  the.tragedy.of.macbeth.1971.1080p.bluray.x264-cinefile.mkv
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/podnapisi.py", line 76, in get_matches
    matches |= guess_matches(video, guessit(release, {'type': 'movie'}))
  File "/usr/local/lib/python2.7/dist-packages/subliminal/subtitle.py", line 229, in guess_matches
    get_equivalent_release_groups(sanitize_release_group(video.release_group))):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/utils.py", line 138, in sanitize_release_group
    string = re.sub(r'\[\w+\]', '', string)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by ratoaq2** [comment]
This was fixed long time ago in develop. With the release 2.1.0 this is also fixed on lastest release
