### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by flick1999** [Diaoul/subliminal#999]
Per https://github.com/pymedusa/Medusa/issues/7988, told to report this here:

2020-04-19 14:15:01 ERROR    POSTPROCESSOR :: [94fae84] Exception generated: expected string or bytes-like object
Traceback (most recent call last):
  File "/app/medusa/medusa/scheduler.py", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/medusa/process_tv.py", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/app/medusa/medusa/process_tv.py", line 187, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/medusa/process_tv.py", line 378, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 599, in process_media
    self.result = processor.process()
  File "/app/medusa/medusa/post_processor.py", line 1254, in process
    cur_ep.download_subtitles()
  File "/app/medusa/medusa/tv/episode.py", line 503, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self, lang=lang)
  File "/app/medusa/medusa/subtitles.py", line 446, in download_subtitles
    scored_subtitles = score_subtitles(subtitles_list, video)
  File "/app/medusa/medusa/subtitles.py", line 312, in score_subtitles
    result = sorted([(s, compute_score(s, video, hearing_impaired=app.SUBTITLES_HEARING_IMPAIRED),
  File "/app/medusa/medusa/subtitles.py", line 312, in <listcomp>
    result = sorted([(s, compute_score(s, video, hearing_impaired=app.SUBTITLES_HEARING_IMPAIRED),
  File "/app/medusa/ext/subliminal/score.py", line 112, in compute_score
    matches = subtitle.get_matches(video)
  File "/app/medusa/ext/subliminal/providers/tvsubtitles.py", line 61, in get_matches
    matches |= guess_matches(video, guessit(self.rip, {'type': 'episode'}), partial=True)
  File "/app/medusa/ext/subliminal/matches.py", line 226, in guess_matches
    if key in matches_manager and matches_manager[key](video, partial=partial, **guess):
  File "/app/medusa/ext/subliminal/matches.py", line 20, in series_matches
    return video.series and sanitize(title) in (
  File "/app/medusa/ext/subliminal/matches.py", line 21, in <genexpr>
    sanitize(name) for name in [video.series] + video.alternative_series
  File "/app/medusa/ext/subliminal/utils.py", line 122, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/lib/python3.8/re.py", line 208, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by flick1999** [comment]
[application.log](https://github.com/Diaoul/subliminal/files/4500383/application.log)

**Comment by dirkr07** [comment]
Ah yes, this seems to be mainly with episodes that have a year in them?
At least that is what i'm noticing

**Comment by ratoaq2** [comment]
This was an issue in medusa and was fixed there
